### ISSUE TITLE
integrate with iSpot - southern africa: your place to share nature

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#100]
Sent following email to the iSpot team using http://www.ispot.org.za/contact_us 

----
Hi!

I was hoping to integrate the species interaction data as recorded on iSpot into Global Biotic Interactions (GloBI, http://globalbioticinteractions.org). This way, the iSpot interaction data can be easily used by others for scientific and educational purposes. I've created an issue (https://github.com/jhpoelen/eol-globi-data/issues/100) to keep track of this. Please feel free to comment on the issue. 

---

**Comment by jhpoelen** [comment]
At Citizen Science Conference 2015 11-12 Feb 2015 in San Jose, California, USA, I got the opportunity to talk to Jonathan Silvertown. He said that iSpot data is currently shared with the UK National Biodiversity Network (UK NBN), and UK NBN shares with GBIF. However this includes occurrence data, not interaction data. No current plans exist to include machine readable interaction data records.

**Comment by jhpoelen** [comment]
@ZekeMarshall integration with iSpot sounds excellent! Curious to hear what they have to say about it . . .

**Comment by ZekeMarshall** [comment]
Absolutely - email sent!
