### ISSUE TITLE
Thieltges et al. 2011. Food web including metazoan parasites for a tidal basin in Germany and Denmark. Ecology 92:2005.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#106]
http://esapubs.org/archive/ecol/E092/172/
David W. Thieltges, Karsten Reise, Kim N. Mouritsen, John P. McLaughlin, and Robert Poulin. 2011. Food web including metazoan parasites for a tidal basin in Germany and Denmark. Ecology 92:2005.

**Comment by millerse** [comment]
I can help with this one, if you would like.

**Comment by jhpoelen** [comment]
Hi Sarah! @millerse - good to hear from you and thanks for offering to help integrate this dataset. This particular reference seems structured enough to be mapped programmatically. The advantage of doing this, is that whenever changes come in, or correction are made (either in data or the mapping), it is easy to redo the work. Would you happen to have programming experience? If so, please let me know which programming languages you are familiar with. If not, then there's a much more challenging set of rich datasets that several folks have been asking for. You can find one in issue #69 (parasites of starfish) and/or #65 (a big collection of various interaction datasets, written down in all sorts of different formats). Let me know what you think! I'd be happy to schedule a chat if you need more info. . .

**Comment by jhpoelen** [comment]
Data now discoverable through GloBI.
