### ISSUE TITLE
[FEATURE] Web API method for for interaction sources

### ISSUE THREAD

**Issue by coding46** [jhpoelen/eol-globi-data#113]
For the generic implementation of the eol-globi-js widget it would be helpful if the is a method which retrieves *distinct* taxon names for sources of observed interactions (including the usual parameters for type and location).

http://api.globalbioticinteractions.org/taxon?type=xyz would be great.

For sure there are other ways right now. But for initial data retrieval of big areas the result would be too large and time intensive to parse for a simple select box.

Or do I miss a method which does it right now.

**Comment by coding46** [comment]
Nevermind, parsing of whole world data is quick enough to do it in real time browser based via http://api.globalbioticinteractions.org/interaction. I'll implement a method in eol-globi-data-js.

**Comment by coding46** [comment]
Sorry for spamming, but there is no way to do this in a browser based manner, because if the huge amounts of data. My first try looked hopefully until I realized that I only got 1024 results. :) Raising the limit parameter is not an option amount of data runs high to soon.

**Comment by jhpoelen** [comment]
@coding46 thanks for your suggestion 

Just to be sure: by ```sources of observed interactions``` do you mean _locations_ of observed interactions?

**Comment by jhpoelen** [comment]
@coding46 I made a first pass at the functionality that I think you are asking for. 

You can now do things like:

http://api.globalbioticinteractions.org/taxon?bbox=-67.87,12.79,-57.08,23.32

http://api.globalbioticinteractions.org/taxon?bbox=-67.87,12.79,-57.08,23.32&interactionType=parasiteOf

and distinct taxa are returned. Note that paging is enabled by default, so you might have to consider going to the next page for information dense areas.

Is this what you were looking for? If so, please close this issue. Otherwise, let me know how I can make it better!

**Comment by coding46** [comment]
@jhpoelen Thanks for the functionality. I'm trying out if it fits our needs.

First thing I discovered is an issue for type=json.v2 which returns the correct structure, even then length of the result is correct. But there are no values in it. Looks like a caching issue.

http://api.globalbioticinteractions.org/taxon?bbox=-67.87,12.79,-57.08,23.32&interactionType=parasiteOf&type=json.v2

**Comment by coding46** [comment]
I did first checks. Here are the results and follow up questions. I transformed the example into the json.v2:

Exerpt:
```json
[
  {
    "name": "Chrysothrix candelaris",
    "common_names": "dust lichen @en | Tammenrikkijäkälä @fi | ",
    "external_id": "EOL:302235",
    "taxon_path": "Fungi | Ascomycota | Arthoniomycetes | Arthoniales | Chrysothricaceae | Chrysothrix | Chrysothrix candelaris",
    "taxon_path_ids": "EOL:5559 | EOL:5577 | EOL:2858522 | EOL:5583 | EOL:5585 | EOL:16811 | EOL:302235",
    "taxon_path_names": "kingdom | phylum | class | order | family | genus | species"
  }
]
```
This could be a lot shorter for our current needs. F.x. 'name' and 'external_id' are redundant date cause they appear in 'taxon_path' and 'taxon_path_ids'. And the 'taxon_path_names' is nothing we currently in need. But nevertheless one might need all those data for another purpose. So let them in it.

Is there a way to configure by request the list of fields I'd like to get in the response?

Kinda:
http://api.globalbioticinteractions.org/taxon?bbox=-67.87,12.79,-57.08,23.32&fields=common_names,taxon_path 

Response:
```json
[
  {
    "common_names": "dust lichen @en | Tammenrikkijäkälä @fi | ",
    "taxon_path": "Fungi | Ascomycota | Arthoniomycetes | Arthoniales | Chrysothricaceae | Chrysothrix | Chrysothrix candelaris",
  }
]
```

This will lower the result size a lot and as we're have to use the paging it speeds up the things.

**Comment by jhpoelen** [comment]
@coding46  Thanks for your feedback. 

Now, something like:

http://api.globalbioticinteractions.org/taxon?bbox=-67.86,12.79,-57.08,23.32&field=taxon_common_names&field=taxon_path

will return something like: 

```json
[ 
  {
    "taxon_common_names": "one @en | zwei @de | drie @nl",
    "taxon_path": "a | b | c |"
  }
]
```

I hope this suits your needs. Please close issue unless you have some more suggestions.

PS Note that older request urls will return cached responses, they should go away in 24 hours or so. So, for testing, please make sure to use "fresh" request urls.
Please let me know if

**Comment by coding46** [comment]
@jhpoelen This is great, thanks a lot.

**Comment by cmungall** [comment]
Very minor comment, so I'm not reopening. How set in stone is the json format? Can we `s/taxon_path_names/taxon_path_ranks/`

**Comment by coding46** [comment]
@cmungall From my frontend only perspective - if it fits better into the terminology - it's okay changing it.

**Comment by jhpoelen** [comment]
[taxon_path_names] is now [taxon_path_ranks] 

hope this makes it a bit cleaner.
