### ISSUE TITLE
provide API that to enable iNaturalist to list external site links by observation.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#115]
as suggested by @loarie at Citizen Science conference http://citizenscienceassociation.org/conference/ :

Currently, iNaturalist annotates observations that are shared with GBIF with a little icon. (see attached screenshot from http://www.inaturalist.org/observations/563486). GloBI includes iNaturalist records that describe interactions and these shared records are used by EOL (among others). The idea of this feature is to provide iNaturalist with a list of iNaturalist observations ids that are shared with EOL (for now) and point to the url where this information is available (see attached eol screenshot, http://eol.org/pages/317369/data#data_point_16695406).

in iNaturalist:
![screen shot 2015-02-13 at 12 20 42 pm](https://cloud.githubusercontent.com/assets/1084872/6194635/ea9f37e8-b37a-11e4-8268-d0aceedf38a1.png)

in EOL:
![screen shot 2015-02-13 at 12 27 12 pm](https://cloud.githubusercontent.com/assets/1084872/6194732/a9caf80a-b37b-11e4-9c7b-f6a5cd2536b3.png)

@kueda let me know what you think about this . . . would a simple json array of id -> url maps do ?

**Comment by kueda** [comment]
That would work. And it can be paginated, pretty sure that's how the GBIF system works. Does GLOBI store the data themselves, or do you guys just store your data on EOL? We could just link to you guys instead, or as well.

**Comment by jhpoelen** [comment]
Great! I'll get an initial version up and running so that you can poke and give feedback. My current thinking is to provide a GloBI endpoint with redirects to GloBI data consumers (like EOL).

**Comment by jhpoelen** [comment]
@jrice @jhammock Other than resorting to html-scraping, does EOL provide a method to list all data points associated to a specific reference? For instance, for reference pointing to http://inaturalist.org/observations/563486, I'd like to list all data point uri's available. In this case, that would include http://eol.org/pages/317369/data#data_point_16695406 .

**Comment by JRice** [comment]
We do not have a way to get that query (from the outside world).

It's not a bad idea, though, so I'll keep this in mind as we work on the
API for traits...

**Comment by jhpoelen** [comment]
@JRice Thanks for your prompt reply! 

@jhammock you might also be interested in being able to link back into eol on the trait level in context of upcoming projects.

Just to be complete:

We need is a way to translate a trait id retrieved from http://eol.org/api/traits/317369 (see snippet below) into some URL that resolves / redirects (e.g. http://eol.org/pages/317369/data#data_point_16695406) . The piece that is missing is the (internal?) data point id ```16695406 ```. Alternatively, I can to mine each and every data tab page with something like phanthom js, have a robot click on "show more info" and retrieve associated ids including  ```16695406``` this way: if you can't bring the horse to the stream, why not bring the stream to the horse? Fun stuff! 

Thanks for listening!

```json
{
            "@id": "http://eol.org/resources/713/associations/globi:assoc:2073313-eol:34543-ate-eol:317369",
            "@type": "eol:Association",
            "dwc:taxonID": "http://eol.org/pages/317369",
            "eol:associationType": {
                "rdfs:label": {
                    "en": "has predator"
                },
                "@id": "http://eol.org/schema/terms/HasPredator"
            },
            "eol:targetTaxonID": "http://eol.org/pages/34543",
            "source": "<a href=\"http://iNaturalist.org\">http://iNaturalist.org</a> is a place where you can record what you see in nature, meet other nature lovers, and learn about the natural world. Accessed at <a href=\"http://inaturalist.org\">http://inaturalist.org</a> on 18 Jan 2015.",
            "Scientific name": "Enhydra"
        }
``` 

PS Could you point me to a downloadable traitbank archive?

**Comment by JRice** [comment]
>
> PS Could you point me to a downloadable traitbank archive?
>

If you are willing to install Virtuoso, you can download our entire
TraitBank triple-store <http://opendata.eol.org/eol_virtuoso/>.

**Comment by jhpoelen** [comment]
I'll have a look . . . thanks!

**Comment by JRice** [comment]
>
> Just to be complete:
>
> We need is a way to translate a trait id retrieved from
> http://eol.org/api/traits/317369 (see snippet below) into some URL that
> resolves / redirects (e.g.
> http://eol.org/pages/317369/data#data_point_16695406) . The piece that is
> missing is the (internal?) data point id 16695406. Alternatively, I can
> to mine each and every data tab page with something like phanthom js, have
> a robot click on "show more info" and retrieve associated ids including
> 16695406 this way: if you can't bring the horse to the stream, why not
> bring the stream to the horse? Fun stuff!
>
Oh! I see, now. That's easy.  :D  (Sorry for not parsing this last night.)

That ID you're looking for is called the data_point_uri_id (and I didn't
add it because, as you say, it's mainly an internal id) ...I'll try and add
it to the API for our next deploy, since it should be quite simple to do so.

Also, counterintuitively, that ID will NOT be in the Virtuoso database I
pointed you to last night; that ID is actually kept in MySQL. (It's a long
story, but *essentially *boils down to the need to translate URIs to a
human-readable string*, and we do that in MySQL.)

Thanks.


* It's actually wildly more complicated than that, but that's outside of
the scope of this email.

**Comment by jhpoelen** [comment]
@JRice thanks for re-parsing my comment - I am looking forward to being able to link directly into an EOL trait to enable a link between iNaturalist interaction records and EOL taxon trait. 

Two questions:
1. Which API will it be added to? Traits or non-trait api?
2. When will be the next deploy?

**Comment by JRice** [comment]
>
> Two questions:
> 1. Which API will it be added to? Traits or non-trait api?
>
Traits. Again, it should show up as a "data_point_uri" field on each of the
traits for a page.

> 2. When will be the next deploy?
>
It *should* be live tomorrow after 9 ET.

Don't get used to a 48-hour feature implementation.  ;)

**Comment by jhpoelen** [comment]
Thanks! 

No worries about the feature delay - I know we'll get faster at implementing new features ; ) .

**Comment by jhpoelen** [comment]
I got around to collecting  provider / consumer url pairs (see sample below). It turned out to be quite laborious . . .  

Here's a subset of the url map:

provider url | consumer url
 --- | ---
http://inaturalist.org/observations/1110546 | http://eol.org/pages/70995/data#data_point_17809879
http://inaturalist.org/observations/1070857 | http://eol.org/pages/70995/data#data_point_17955668
http://inaturalist.org/observations/1070837 | http://eol.org/pages/70995/data#data_point_17268685
http://inaturalist.org/observations/349424 | http://eol.org/pages/70995/data#data_point_17710998
http://inaturalist.org/observations/125384 | http://eol.org/pages/70995/data#data_point_16968228
http://inaturalist.org/observations/115438 | http://eol.org/pages/70995/data#data_point_18421631


The list was generated by:
 1. getting a list of all naturalist observations from GloBI (~seconds) 
 2. getting traits from EOL for each these pages (~hours)
 3. parsing traits json, extracting association id as well as data point uri  (~ seconds)
 4. building table of provider url (e.g. naturalist observation url, but can also be doi or other provider link) and associated link into the data reference as available through EOL.

@kueda if I publish this file, would you be able to harvest this daily or so to check for update? Alternatively, I can provide a list of inaturalist ids and direct to relevant page(s) some GloBI endpoint.  Let me know what implementation you prefer.

@JRice Thanks again for adding the data point uris in to the traits. Without this, I would not have been able to get this far. Here some of my questions about data point uris:
 1.  - it often take about a minute for EOL to respond to a request like [this](http://eol.org/pages/70995/data#data_point_17955668), is this expected? 
 2. Also, sometimes an error (see attached) appears after about 60s wait. Is this a known issue?
![screen shot 2015-02-25 at 11 34 32 am](https://cloud.githubusercontent.com/assets/1084872/6378772/55d479cc-bce2-11e4-9775-77567e369a11.png)
 3. If GloBI refreshes, it is correct that the data point uris are no longer valid/available? 

I am eager to get this feature, because I think it help to connect two active communities and to give more visible credit to those that provide observations. 

Thanks for listening and looking forward to hear your thoughts.

**Comment by JRice** [comment]
>
>
>    1. - it often take about a minute for EOL to respond to a request like
>    this <http://eol.org/pages/70995/data#data_point_17955668>, is this
>    expected?
>
> I suppose "expected" is fair. I'd call it a "known problem." It's not
something we're happy about, but clearly it's the case. :\ There's nothing
"wrong" with the query, it's just something that needs serious work in
terms of the efficiency of the algorithm.  Sorry!  :S

>
>    1. Also, sometimes an error (see attached) appears after about 60s
>    wait. Is this a known issue?
>
> No, actually, it's not. THAT said, we have been having lots of timeout
errors in the past 48 hours due to some seriously heavy queries we're
running. ...Probably will be for the next two days, too.  :\

> Thanks for listening and looking forward to hear your thoughts.
>
I am really sorry this is such a hassle, and I really appreciate your
patience. We're really trying to improve things... there's just... a LOT to
improve. :|

**Comment by kueda** [comment]
Well, I don't just want a static file of iNat IDs that you email me or something. I want that list published online where I can harvest it regularly, so I think that corresponds to your first implementation. Are there no globi URLs for these things? If we get EOL URLs we will show that an observation has been integrated into EOL, not globi. If you'd prefer globi, I'll need a mapping to globi URLs, if they exist.

**Comment by jhpoelen** [comment]
You can find the most recent provider-consumer url pairs here: 
https://raw.githubusercontent.com/jhpoelen/backwarden/master/provider-consumer.csv

GloBI does not provide any URIs at this point, so until we do, please feel free to link to EOL directly. The data tab on EOL does say where the data comes from, so the link with GloBI is not entirely lost.

Note that the pairs also include non-inaturalist observation urls, so you might want to skip those.

Let me know if this works for you.

**Comment by kueda** [comment]
I can use that. How often do you plan to update it? Also, is it safe
to assume iNat observations that are not in that file are *not* on
EOL?

**Comment by jhammock** [comment]
Good question, Ken-Ichi. EOL does also have images from all your Research Grade observations which are appropriately licensed. Shall I have our connector guru, Eli construct a similar list for those? They would point to EOL image pages, eg: http://eol.org/data_objects/31533815
You will likely end up with some observations appearing in both lists. Would that be a problem?

**Comment by kueda** [comment]
Not a problem if they have different URLs, but the same requirements:

1. Need access to a file or a paginated API endpoint where we can retrieve a mapping of iNat observation IDs to stable URLs on the other site
1. Either need to be able to assume the data available from this source represents all the iNat data integrated into the collection so we can delete linkages for iNat observations that were in the collection but aren't anymore
1. Need to know how often it's updated.

**Comment by jhpoelen** [comment]
@kueda We can setup a GitHub commit hook to hit a iNaturalist URL each time the links change. I would expect this to happen at about a monthly schedule, but can't guarantee exact timing. Would this be practical? 

Also, about the completeness of the iNaturalist observations that appear on EOL as shared through GloBI - currently, I am relying on GloBI to pick the candidate taxon pages on which iNaturalist interaction observations might appear. This is a pragmatic choice with the alternative being to request the traits of all 1,358,805 EOL pages one by one. . . taking probably a week or more with current trait api response times. So, I'd say its a pretty good estimate, but without some improvements in EOL plumbing (see requests below), I can't be 100% sure. I can totally understand if you'd like to hold off until I can provide complete coverage of the iNaturalist interaction data. But hey, I figured that pretty good is better than not at all.

@JRice So, while I enjoy the mental and semi-physical exercise to get a reasonably complete picture of links between iNaturalist <> EOL. . . these are two EOL API features requests:

1. Have a way to get a (machine readable) notification after a successful ingestion (e.g. webhook perhaps?). Right now I have to eye ball some webpage to see whether a new version of GloBI is up.
2. (more importantly) get a list of all data point uris that are based on GloBI provided data

Thanks again for listening . . . and @kueda let me know how you'd like to proceed.

**Comment by JRice** [comment]
>
>
>    1. Have a way to get a (machine readable) notification after a
>    successful ingestion (e.g. webhook perhaps?). Right now I have to eye ball
>    some webpage to see whether a new version of GloBI is up.
>
>
Hmmmn. An interesting idea which I hadn't considered before. Not too
difficult to implement, but not sure where it would fall in priorities. Let
me make a ticket for it, regardless.

>
>    1. (more importantly) get a list of all data point uris that are based
>    on GloBI provided data
>
> I see. Okay, another ticket; will make it higher priority.

**Comment by jhammock** [comment]
@kueda Just checking: the images on EOL currently carry source links back to the photo page on iNat, eg: http://www.inaturalist.org/photos/1234032. You'd rather have a list of observation IDs to post these links on, not photo IDs? I can imagine, now that I think about it, you getting a stack of records for an observation which bears 6 photos, all sent to EOL. Would you rather have that, or would you prefer to post these to the photo pages? Or should we hold off on doing this? Thanks!

**Comment by kueda** [comment]
@jhpoelen no need for a commit hook, we'll just keep it simple and retrieve it on regular schedule.

**Comment by jhpoelen** [comment]
@kueda sounds good. Pls poke me if the integration is ready/ causing troubles.

**Comment by kueda** [comment]
Hm, now that I'm tested this there are a couple issues.

1. One observation documenting a single interaction seems to map to multiple interactions on EOL, e.g. http://www.inaturalist.org/observations/1158453 maps to http://eol.org/pages/5870542/data#data_point_16720422, http://eol.org/pages/32539/data#data_point_16720192, and http://eol.org/pages/472631/data#data_point_17585196, even though they're all basically the same interaction with different taxonomic ranks and cardinality. We really just want to provide a single link to show "Hey, this other site is making use of your data!" as opposed to an arbitrary number of links that like, "GloBI, GloBI, GloBI." We can just choose a single interaction per observation, but it would be nicer to have a URL that represents the single interaction documented on iNat as seen on your system, maybe with links from that page to the derivative interactions at different ranks and cardinalities.
1. What's up with the "interacts with" interaction type? My impression as a user is, "I put some effort into documenting a specific interaction, but this other site abstracted that into something that has less specific meaning." Maybe you guys could include the interaction type in your CSV and we could just choose them selectively.
1. Why isn't this http://www.inaturalist.org/observations/1158453 represented on EOL as the interaction between the two taxa documented on iNat? I'm seeing "Ferraria interacts with Camponotus," "Camponotus niveosetosus interacts with Iridaceae," and "Camponotus interacts with Iridaceae," but *not* "Camponotus niveosetosus interacts with Ferraria," which is the actual interaction documented on iNat, or any of the other possible combinations of ranks and cardinality.

**Comment by jhpoelen** [comment]
Thanks for sharing these issues! 

**Re 1. one-to-many mapping** of iNaturalist observations. I can see your point and agree it is a bit strange to have multiple icons pointing to all the places where the inat interaction is referenced. A GloBI page pointing to all the different customer urls would provide a nice way to show folks how their interaction is used without cluttering the iNaturalist UI, I've created a separate issue #120 . Let me know if I captured your idea properly. Also, the reason why a single observation is referenced many times is because of interaction inversion (e.g. bunny -[:eats]-> carrot and  carrot -[:eaten by] -> bunny) in combination with a bit of taxonomic reasoning as described in issue #79 . 

**Re 2. interaction mapping** - I was hoping you were going to ask how interaction types are mapped! GloBI is using a controlled vocabulary whenever possible ([obo relation ontology (RO)](http://www.ontobee.org/browser/term.php?o=RO&iri=http://www.w3.org/2002/07/owl%23ObjectProperty&graph=http://purl.obolibrary.org/obo/merged/RO)), I manually have to create the mapping between the iNaturalist observation field and subset of RO terms (see  http://api.globalbioticinteractions.org/interactionTypes, note that we can add new interaction types whenever needed). My current interaction map can be found [here]( https://github.com/jhpoelen/eol-globi-data/blob/master/eol-globi-data-sources/src/main/java/org/eol/globi/data/StudyImporterForINaturalist.java#L36). Ideally, I would like to have this mapping sit closer to the user, ideally, have a way to associate these terms to "standard" terms in iNaturalist itself. Is there a way for curators (or curator bots?) to add observations fields or annotate existing ones with pointers to GloBI interaction terms? 

**Re 3. missing references** - Some references were missing due to a bug in my code. I have made a change and regenerated the provider consumer links. Let me know if the links are now complete.

Would you like to hold off with integration until #120 is implemented?

**Comment by kueda** [comment]
1. Cool, #120 looks good
1. We don't have bots, but you can add any additional fields you want, and add them to any observation. I suppose in theory you could write your own bot that uses our API to do this, but it would basically be performing the same mapping you're doing in https://github.com/jhpoelen/eol-globi-data/blob/master/eol-globi-data-sources/src/main/java/org/eol/globi/data/StudyImporterForINaturalist.java#L36. The Tricky part is convincing people to use your controlled vocab.
1. Cool

Yes, I'd like to see #120 complete before creating these links on iNat.

**Comment by jhpoelen** [comment]
@kueda Because inaturalist observations can now be linked to GloBI using #120, I am closing this issue. Please feel free to re-open the issue if there's something blocking from making the link.

PS I hope to add links to specific EOL traits derived from interaction shared through GloBI (e.g. inaturalist observations) at some point in the future.
