### ISSUE TITLE
integrate with American Gut Project

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#116]
from [American Gut Project](http://americangut.org):
"You’ve probably heard by now that the trillions of microbes living on and in our bodies are changing both the way we think about health and disease and even how we define Self. Ever wonder what’s in your gut? Ever wonder how your diet might shift your gut microbes (for better or worse), or how simple lifestyle decisions may have a dramatic impact on your gut and overall health? Ever wonder which microbes on your husband sometimes make him smell funny?"

open access data available through:
https://github.com/biocore/American-Gut/tree/master/data

**Comment by cmungall** [comment]
There are a lot of gut microbial datasets out there, and more broadly metagenome.

In theory we could use these to derive microbe-microbe pairs (e.g. based on finding in the same body part) but this would explode globi and it's not clear what the use case would be

But I assume you're thinking more of microbe to host associations, possibly also qualified with environment (here a body part from uberon) and any additional useful metadata (e.g. inferred to give rise to a particular disease). This could be quite interesting. There are a number of other potential sources of this data, e.g. https://gold.jgi-psf.org/biosamples?Biosample.Ecosystem=Host-associated

**Comment by jhpoelen** [comment]
Thanks for peeking at the data and yep, I was thinking about microbe to host associations within host environment. Remaining question: (a) should we pursue host-microbe interactions at this point? and (b) if we do, which available dataset would be informative to link to the existing body of species interactions? Curious to hear your thoughts.

**Comment by jhpoelen** [comment]
Closing issue - American Gut project seems a bit outside of GloBI's scope.
