### ISSUE TITLE
integrate with National Biodiversity Network taxonomy webservice

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#117]
https://data.nbn.org.uk/Documentation/Web_Services/Web_Services_Examples/REST/Taxon_Search/

Now that Malcolm Storey (http://bioinfo.org.uk) has linked his taxa to NBN taxon ids, GloBI can cross-reference the taxa with the National Biodiversity Network taxonomy.

@jhammock any plan of EOL to integrate with NBN taxonomy?

**Comment by jhammock** [comment]
No recent communication with NBN, though we may well have talked with them back in the early days. I don't see anything about terms of use, though that might mean they default to not asserting copyright. Have you heard anything explicit?

**Comment by jhpoelen** [comment]
I haven't heard anything explicit. I am assuming that the API is open for anyone to use, since no account is required for access. If it were the case, it is trivial to remove the integration.

**Comment by jhammock** [comment]
that is usually a good sign. I'll ask Eli to have a look :)

**Comment by jhpoelen** [comment]
NBN integration added to GloBI. Whenever a NBN taxon code/id is encountered, the taxon is cross referenced with NBN.
