### ISSUE TITLE
Do Sea Otters really eat American Beavers?

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#118]
This question came up during http://blog.globalbioticinteractions.org/2015/02/11/tea-at-berkeley-institute-for-data-science/ . 

The interaction data originated from Animal Diversity Web (ADW, http://animaldiversity.org) through the Semantic Prototypes in Research Ecoinformatics (SPIRE) provided by Joel Sachs and Cyndy Parr.

After reaching out to Joel and Cyndy, @csparr determined that Sea Otters (Enhydra) do not eat American Beavers (_Castor canadensis_) and marked the data as untrusted on eol.org.  Cyndy mentioned that the SPIRE is archived and suggested to replace the ADW part of it as a separate resource mined directly from ADW. If this is not feasible, GloBI can exclude the specific datapoint and reference Cyndy's opinion as an expert.

@diatomsRcool Could you please remove the offending interaction from your dataset at http://github.com/EOL/pseudonitzchia ? Or perhaps, rerun the program to get an updated version of the text mined interactions? 

Thank you all for helping to highlight and address data issues in GloBI!

**Comment by diatomsRcool** [comment]
I think the problem is the assumption that this is a predator prey 
interaction. More likely it is some sort of competition. The 
interactions in this data set do not imply interaction type, only that 
an association exists.
a

On 2/18/2015 1:37 PM, Jorrit Poelen wrote:
>
> This question came up during 
> http://blog.globalbioticinteractions.org/2015/02/11/tea-at-berkeley-institute-for-data-science/ 
> .
>
> The interaction data originated from Animal Diversity Web (ADW, 
> http://animaldiversity.org) through the Semantic Prototypes in 
> Research Ecoinformatics (SPIRE) provided by Joel Sachs and Cyndy Parr.
>
> After reaching out to Joel and Cyndy, @csparr 
> <https://github.com/csparr> determined that Sea Otters (Enhydra) do 
> not eat American Beavers (/Castor canadensis/) and marked the data as 
> untrusted on eol.org. Cyndy mentioned that the SPIRE is archived and 
> suggested to replace the ADW part as a separate resource mined 
> directly from ADW. If this is not feasible, GloBI can exclude the 
> specific datapoint and reference Cyndy's opinion as an expert.
>
> @diatomsRcool <https://github.com/diatomsRcool> Could you please 
> remove the offending interaction from your dataset at 
> http://github.com/EOL/pseudonitzchia 
> <https://github.com/EOL/pseudonitzchia> ? Or perhaps, rerun the 
> program to get an updated version of the text mined interactions?
>
> Thank you all for helping to highlight and address data issues in GloBI!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jhpoelen/eol-globi-data/issues/118>.
>

-- 
Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by jhpoelen** [comment]
@diatomsRcool More likely than not, the interaction data was mined from this data object: http://eol.org/data_objects/10540245 (see attached image). I am not aware of any other location on eol that mentions the disputed interaction. Please do let me know if the interaction was mined for another source. 

Now that the data object in question has been hidden by @csparr , I would expect that the interaction would no longer appear in (an updated version of) data at http://github.com/EOL/pseudonitzchia . 

![screen shot 2015-02-18 at 10 49 09 am](https://cloud.githubusercontent.com/assets/1084872/6254253/18fd77d2-b75c-11e4-972f-d7a0ab376f22.png)

**Comment by diatomsRcool** [comment]
Fix made. You can update whenever you want.
a

On 2/18/2015 1:54 PM, Jorrit Poelen wrote:
>
> @diatomsRcool <https://github.com/diatomsRcool> More likely than not, 
> the interaction data was mined from this data object: 
> http://eol.org/data_objects/10540245 (see attached image). I am not 
> aware of any other location on eol that mentions the disputed 
> interaction. Please do let me know if the interaction was mined for 
> another source.
>
> Now that the data object in question has been hidden by @csparr 
> <https://github.com/csparr> , I would expect that the interaction 
> would no longer appear in (an updated version of) data at 
> http://github.com/EOL/pseudonitzchia 
> <https://github.com/EOL/pseudonitzchia> .
>
> screen shot 2015-02-18 at 10 49 09 am 
> <https://cloud.githubusercontent.com/assets/1084872/6254253/18fd77d2-b75c-11e4-972f-d7a0ab376f22.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jhpoelen/eol-globi-data/issues/118#issuecomment-74923729>.
>

-- 
Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by jhpoelen** [comment]
@diatomsRcool thanks for acting so quickly on this! the changes should propagate in GloBI within a day or so.

**Comment by csparr** [comment]
And to be fair, it can't be taken as a given that the error was ever on ADW. We could have messed up when we originally dumped the predator-prey data for SPIRE, or at some point subsequent to that.

ADW doesn't have any specifically machine readable endpoint other than the current export for EOL (see below).  At one point Joel generated RDF for each of the pages, but I think that's been taken down (would have been curious to see if it had the error in it). 

There is a human-oriented query interface for ADW structured data here: https://animaldiversity.ummz.umich.edu/quaardvark/

Roger Espinosa (roger@umich.edu) created the ADW export for EOL which is regularly updated but includes only text output. These objects could be parsed for the predator and the prey info as the lists are generated in a standard way.  Anne's text mining caught them but didn't parse out the specifics of the relationships but that would be possible to tailor knowing how those particular partner's objects are structured.

**Comment by jhpoelen** [comment]
@csparr thanks for giving some context to the situation. 

I've sent an email to Roger and requested access to a machine readable version of ADW. I am hoping it can be as simple as downloading an archive (ms access db perhaps?). 

Meanwhile, I'll prevent the offending record to be ingested from SPIRE by GloBI. Since the process is automated and the SPIRE resource has been archived, this is not too much trouble. 

Closing issue for now.

**Comment by diatomsRcool** [comment]
I know this issue is closed, but while working on the yellowstone project, I see text stating that otters do eat beavers when they are young. Do we want to put that interaction back in and qualify it somehow?

**Comment by jhpoelen** [comment]
Interesting! What is your source?

**Comment by jhpoelen** [comment]
@diatomsRcool if the source is something other than SPIRE, we can include this piece of information in a separate archive with a reference to the original source text / paper. if it comes from SPIRE, I can undo the changes I made.

**Comment by diatomsRcool** [comment]
The source is the National Park Service information web page about 
Yellowstone
http://www.nps.gov/yell/learn/nature/river-otter.htm
If we want to be really careful, we could probably ask some of the park 
scientists for confirmation.

On 5/20/2015 4:01 PM, Jorrit Poelen wrote:
>
> Interesting! What is your source?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jhpoelen/eol-globi-data/issues/118#issuecomment-104018056>.
>

-- 
Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by diatomsRcool** [comment]
Here is an actual published source 
Seton, E.T. (1929) Lives of Game Animals. Doubleday, Doran & Co., Garden City N.Y., 506 pp.

**Comment by jhpoelen** [comment]
@diatomsRcool thank you for providing the references. I've created a separate issue #142 to document this reference to species interaction data. The plot thickens. . .
