### ISSUE TITLE
Interactions from Smithsonian Botany Department

### ISSUE THREAD

**Issue by millerse** [jhpoelen/eol-globi-data#119]
There are a few publications on the Smithsonian site that I think globi could use:
https://repository.si.edu/handle/10088/18379

**Comment by jhpoelen** [comment]
@millerse Looks like a nice integration dataset. Just curious - why did you close it?

**Comment by millerse** [comment]
I thought it was too small.

**Comment by jhpoelen** [comment]
Thanks @millerse for your contributions ! On another note - assuming that our GitHub/GloBI method of sharing data is useful, how do you think we can best share and improve our methods in the ecology community? Blog? Article? Curious to hear your thoughts . . .

**Comment by millerse** [comment]
@jhpoelen I can't think of anything at the moment.  I think you have a great system right now.
