### ISSUE TITLE
create a way to show usage of contributed data by data consumers / tools

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#120]
Create a page / method to show those sharing data (i.e. data providers) how the data is used by data consumers (e.g. Encyclopedia of Life) or how to find the data using GloBI tools (e.g. rglobi, web api). 

If data provider resource can be accessible through a url, this landing page should contain a relation between this url and provider urls. For instance, an inaturalist observations accessible at some url is referenced by eol pages x, y, z accessible through url x, url y, url z respectively.

Suggested by @kueda  in #115 .

**Comment by kueda** [comment]
Yup, this is what I was describing. Actually, the primary information I'd like to see on such a page is the interaction supported by the source evidence, so that as an iNat user, I can go to GloBI and say, "I know my observation helped GloBI know that raccoons eat crayfish." Links out to EOL would be good too, but mostly the benefit for us at iNat is public, visible proof that our data helped you guys out and contributed to a larger understanding how ecosystems.

**Comment by jhpoelen** [comment]
@kueda I have a first pass to show interaction according to a specific study or source. The idea to to add a query field ```accordingTo``` like: 

http://www.globalbioticinteractions.org/#sourceTaxon=&interactionType=interactsWith&accordingTo=http%3A%2F%2Finaturalist.org%2Fobservations%2F196159

This now shows something like:
![screen shot 2015-03-16 at 12 35 15 pm](https://cloud.githubusercontent.com/assets/1084872/6674731/fe97280c-cbd8-11e4-8449-3775e806beea.png)

The UI needs some work (know anyone that actually would like to work on this?), but I'd say that the information elements are in there: source, target, interaction type, citation and link back to observation.

You can retrieve all inaturalist observations by using the following (paged) query:

http://api.globalbioticinteractions.org/interaction?accordingTo=http%3A%2F%2Finaturalist.org&field=study_url&includeObservations=true&limit=10&skip=5

Note that duplicate URLs exist because inverse mappings are also created (e.g. eats, eatenBy). 

Let me know if this helps make a first pass at an inaturalist <> globi integration! Curious to hear what you think.

PS the accordingTo field is now pretty flexible and also allows for searches like ```Ken-ichi Ueda```.

**Comment by jhpoelen** [comment]
@kueda please let me know if there's anything else you need to introduce the iNaturalist > GloBI link. I think this link would motivate folks to annotate their iNaturalist interactions and will (hopefully) help improve the translation of custom interaction fields into "standardized" interaction terms using ontologies like [RO](http://www.ontobee.org/browser/term.php?o=RO&iri=http://www.w3.org/2002/07/owl%23ObjectProperty&graph=http://purl.obolibrary.org/obo/merged/RO) . Please re-open the issue if you need anything else to complete this loop.

**Comment by kueda** [comment]
Just sat down to work on this, but it doesn't look like http://www.globalbioticinteractions.org/#sourceTaxon=&interactionType=interactsWith&accordingTo=http%3A%2F%2Finaturalist.org%2Fobservations%2F196159 is working. I see a blank page:

![screen shot 2015-04-05 at 5 12 55 pm](https://cloud.githubusercontent.com/assets/22691/6999243/099b2166-dbb7-11e4-9451-3121d4dc5770.png)

**Comment by jhpoelen** [comment]
@kueda thanks for letting me know. I was able to reproduce and identify the root of the problem. Should be fixed now. 
![screen shot 2015-04-05 at 6 12 53 pm](https://cloud.githubusercontent.com/assets/1084872/6999428/6d67a680-dbbf-11e4-86f9-488cf66c55a5.png)

**Comment by kueda** [comment]
Thanks. Would it also be possible to use http://www.inaturalist.org/observations/xxxx instead of http://inaturalist.org/observations/xxxx, or at least have the Globi endpoint respond the same to both?

**Comment by jhpoelen** [comment]
@kueda just updated the inaturalist observations references to your suggested format http://www.inaturalist.org/observations/xxx . This should take a couple of days to propagate. Hope this helps.

**Comment by jhpoelen** [comment]
@kueda changes have been propagated (attached image) . . . let me know if there's anything else you need to complete the inaturalist <> GloBI integration. 
![screen shot 2015-04-14 at 8 31 17 am](https://cloud.githubusercontent.com/assets/1084872/7140634/3e9a451a-e281-11e4-90f0-8070c0fae666.png)

**Comment by kueda** [comment]
URL seems stable now, so I'll proceed, but another bug:

http://www.globalbioticinteractions.org/#interactionType=interactsWith&accordingTo=http%3A%2F%2Fwww.inaturalist.org%2Fobservations%2F131

links to

http://www.inaturalist.org/observations/1310192
http://www.inaturalist.org/observations/1310685
http://www.inaturalist.org/observations/131732
http://www.inaturalist.org/observations/131767

**Comment by kueda** [comment]
https://raw.githubusercontent.com/jhpoelen/backwarden/master/provider-consumer.csv also seems to have a bunch of blanks in the provider column. Is that still the file you want me to use?

**Comment by kueda** [comment]
Aaand one more: http://www.inaturalist.org/observations/432688 seems like it was in yoru CSV, but http://www.globalbioticinteractions.org/#interactionType=interactsWith&accordingTo=http%3A%2F%2Fwww.inaturalist.org%2Fobservations%2F432688 is blank.

**Comment by jhpoelen** [comment]
@kueda thanks for noting that bug - should be fixed now: if a valid url is provided in the accordingTo, strict matching is applied.

Also, the reason why http://www.inaturalist.org/observations/131 didn't show is because the observation is not research grade. Only research grade observations are included.

**regarding linking directly into EOL** I'd suggest to hold off on the ```provider-consumer.csv``` integration. If I understand it correctly, the EOL team is working on providing an API that makes it workable to resolve the EOL URLs. My workaround using ```backwarden``` is a bit crazy (i.e. scrape individual jsonld pages for each taxon that might have GloBI data on it), take a ton of time to complete and produce URLs that are stable until a new GloBI refresh occurs. The refresh schedule is set to monthly and there's currently not a way for me to know exactly when it occurs. I wouldn't want to submit inaturalist users to links that might not work part of the month.

**Comment by jhpoelen** [comment]
@kueda another good catch - http://www.inaturalist.org/observations/432688 should work now. Apologies for the blanks.

![screen shot 2015-04-14 at 7 21 27 pm](https://cloud.githubusercontent.com/assets/1084872/7151221/a7e049fc-e2db-11e4-96df-1355eb0cefce.png)

**Comment by kueda** [comment]
I'm not planning on linking to EOL at all, but I am using https://raw.githubusercontent.com/jhpoelen/backwarden/master/provider-consumer.csv to determine which iNat observations have been integrated into GloBI, i.e. ignoring the EOL URLs but using the presence of an iNat URL to know when to create a link from iNat to GloBI. Isn't that what you want, or is there another way I should be getting that data?

**Comment by jhpoelen** [comment]
One way to get the urls is to use something like:

http://api.globalbioticinteractions.org/interaction?accordingTo=inaturalist&field=study_url&includeObservations=true&limit=10&skip=0

or, if you like csv:
http://api.globalbioticinteractions.org/interaction.csv?accordingTo=inaturalist&field=study_url&includeObservations=true&limit=10&skip=0

The result is expected to list all studies (or observation) urls that mention ```inaturalist``` somewhere in the citation. Here's a result I just created:
```csv
"study_url"
"http://www.inaturalist.org/observations/404096"
"http://www.inaturalist.org/observations/404096"
"http://www.inaturalist.org/observations/757612"
"http://www.inaturalist.org/observations/757612"
"http://www.inaturalist.org/observations/758573"
"http://www.inaturalist.org/observations/758573"
"http://www.inaturalist.org/observations/760632"
"http://www.inaturalist.org/observations/760632"
"http://www.inaturalist.org/observations/662233"
"http://www.inaturalist.org/observations/662233"
```
Note that duplication is expected because of inverted interaction and that pagination is provided using the ```limit``` and ```skip``` parameters.

**Comment by kueda** [comment]
Ok, just created a little over 4000 links, e.g. http://www.inaturalist.org/observations/404096. So far looks pretty good. New links will be added weekly.

Just a few more heads-ups: some observations that should have been indexed were not, e.g. http://www.inaturalist.org/observations/1150861. Some people don't really know how to use observation fields on iNat: http://www.inaturalist.org/observations/565304. This is a problem on our side, but you might be able to automatically filter out things like this by reject interactions between the same taxon. Though I guess you do want to document things like cannibalism.

Sorry this took so long.

**Comment by jhpoelen** [comment]
@kueda thanks for making this work! 

re: http://www.inaturalist.org/observations/1150861 - this observation is not (yet) research grade, so GloBI doesn't index it. Please do let me know if you find any research grade observations that GloBI didn't pick up.

I hope that our integration will help to identify suspect interactions that folks support and use the inaturalist comments to discuss them. Here's a query that lists the 81 inaturalist intraspecific (interacts between same species/taxa) interactions: http://tinyurl.com/intraspecificInteractionsINat (also see list below) . I am hoping the GloBI can remain as neutral as possible while allowing users to apply filters to remove (or detect!) suspect interactions.

Perhaps another way to go about this it to introduce quality grades for observation fields (e.g. a research grade "host" interaction).

intraspecific inaturalist observations on/around 17 Apr 2015 :

 | intraspecific inaturalist observations
--- | ---
1 | Anita. 2005. Mikania scandens insect nectar plant Mikania scandens. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/508909 on 17 Apr 2015.
2 | BJ Stacey. 2013. Gutierrezia insect nectar plant Gutierrezia. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/388912 on 17 Apr 2015.
3 | BJ Stacey. 2014. Anisotremus davidsonii eating Anisotremus davidsonii. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/901492 on 17 Apr 2015.
4 | Bryn Williams. 2014. Vanessa itea associated species with names lookup Vanessa itea. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/989870 on 17 Apr 2015.
5 | Chris Cook. 2013. Asclepias californica flower species Asclepias californica. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/256890 on 17 Apr 2015.
6 | Elliot Goldstein. 2013. Rubus parviflorus flower species Rubus parviflorus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/198058 on 17 Apr 2015.
7 | Harold Brown. 2007. Cyanocitta cristata host Cyanocitta cristata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/490718 on 17 Apr 2015.
8 | Harold Brown. 2007. Poecile atricapillus host Poecile atricapillus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/490736 on 17 Apr 2015.
9 | Harold Brown. 2012. Turdus migratorius host Turdus migratorius. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/489750 on 17 Apr 2015.
10 | Harold Brown. 2013. Cyanocitta cristata host Cyanocitta cristata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/490697 on 17 Apr 2015.
11 | Harold Brown. 2014. Sciurus niger host Sciurus niger. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/494501 on 17 Apr 2015.
12 | Harold Brown. 2014. Spinus tristis host Spinus tristis. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/494286 on 17 Apr 2015.
13 | Harold Brown. 2014. Sturnus vulgaris host Sturnus vulgaris. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/504345 on 17 Apr 2015.
14 | James M. Bryant. 2013. Strymon melinus insect nectar plant Strymon melinus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/397431 on 17 Apr 2015.
15 | Joe. 2013. Enallagma civile host Enallagma civile. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/299486 on 17 Apr 2015.
16 | Joe. 2013. Limenitis archippus host Limenitis archippus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/282033 on 17 Apr 2015.
17 | Joe. 2013. Lycaena phlaeas americana host Lycaena phlaeas americana. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/282021 on 17 Apr 2015.
18 | Joe. 2013. Plathemis lydia host Plathemis lydia. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/295154 on 17 Apr 2015.
19 | Joe. 2013. Polygonia comma host Polygonia comma. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/299221 on 17 Apr 2015.
20 | Joe. 2013. Sisyrinchium angustifolium host Sisyrinchium angustifolium. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/283964 on 17 Apr 2015.
21 | Jon Sullivan. 2014. Fuchsia excorticata associated species with names lookup Fuchsia excorticata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1106386 on 17 Apr 2015.
22 | Judith Lopez Sikora. 2015. Lithospermum incisum insect nectar plant Lithospermum incisum. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1380664 on 17 Apr 2015.
23 | Liam O'Brien. 2014. Heracleum maximum insect nectar plant Heracleum maximum. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/578668 on 17 Apr 2015.
24 | Marco A. Romero. 1994. Psychotria elata flower species Psychotria elata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/841682 on 17 Apr 2015.
25 | Marta. 2013. Himantoglossum robertianum flower species Himantoglossum robertianum. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/518008 on 17 Apr 2015.
26 | Marta. 2013. Ruscus aculeatus flower species Ruscus aculeatus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/517807 on 17 Apr 2015.
27 | Marv Elliott. 2013. Colias philodice insect nectar plant Colias philodice. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/380386 on 17 Apr 2015.
28 | Marv Elliott. 2013. Speyeria cybele insect nectar plant Speyeria cybele. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/380393 on 17 Apr 2015.
29 | Matt Rung. 2014. Agalinis purpurea flower species Agalinis purpurea. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1080008 on 17 Apr 2015.
30 | Michele Roman. 2013. Heliotropium curassavicum insect nectar plant Heliotropium curassavicum. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/454304 on 17 Apr 2015.
31 | Ron Edwards. 2013. Monarda fistulosa insect nectar plant Monarda fistulosa. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/334596 on 17 Apr 2015.
32 | Todd Plummer. 2013. Quercus lobata host Quercus lobata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/449494 on 17 Apr 2015.
33 | WeaselRM. 2013. Tropaeolum majus flower species Tropaeolum majus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/381267 on 17 Apr 2015.
34 | alberto.echeverraserur. 2012. Plumeria rubra flower species Plumeria rubra. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1107614 on 17 Apr 2015.
35 | bernard smith. 2014. Felis catus eaten by Felis catus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1159925 on 17 Apr 2015.
36 | biketandem. 2014. Agelaius phoeniceus host Agelaius phoeniceus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/554026 on 17 Apr 2015.
37 | biketandem. 2014. Aix sponsa host Aix sponsa. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/539164 on 17 Apr 2015.
38 | biketandem. 2014. Anas clypeata host Anas clypeata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/541309 on 17 Apr 2015.
39 | biketandem. 2014. Anas clypeata host Anas clypeata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/565282 on 17 Apr 2015.
40 | biketandem. 2014. Anas rubripes host Anas rubripes. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/539159 on 17 Apr 2015.
41 | biketandem. 2014. Anas strepera host Anas strepera. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/571902 on 17 Apr 2015.
42 | biketandem. 2014. Ardea herodias host Ardea herodias. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/565310 on 17 Apr 2015.
43 | biketandem. 2014. Aythya collaris host Aythya collaris. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/541575 on 17 Apr 2015.
44 | biketandem. 2014. Aythya marila host Aythya marila. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/541564 on 17 Apr 2015.
45 | biketandem. 2014. Aythya valisineria host Aythya valisineria. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/543766 on 17 Apr 2015.
46 | biketandem. 2014. Bucephala albeola host Bucephala albeola. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/539155 on 17 Apr 2015.
47 | biketandem. 2014. Buteo lineatus host Buteo lineatus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/565290 on 17 Apr 2015.
48 | biketandem. 2014. Buteo lineatus host Buteo lineatus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/571907 on 17 Apr 2015.
49 | biketandem. 2014. Certhia americana host Certhia americana. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/543784 on 17 Apr 2015.
50 | biketandem. 2014. Euphagus carolinus host Euphagus carolinus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/539172 on 17 Apr 2015.
51 | biketandem. 2014. Fulica americana host Fulica americana. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/539156 on 17 Apr 2015.
52 | biketandem. 2014. Gallinago delicata host Gallinago delicata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/632075 on 17 Apr 2015.
53 | biketandem. 2014. Lophodytes cucullatus host Lophodytes cucullatus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/541550 on 17 Apr 2015.
54 | biketandem. 2014. Melanerpes carolinus host Melanerpes carolinus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/543800 on 17 Apr 2015.
55 | biketandem. 2014. Melanitta fusca host Melanitta fusca. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/565305 on 17 Apr 2015.
56 | biketandem. 2014. Mergus merganser host Mergus merganser. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/555563 on 17 Apr 2015.
57 | biketandem. 2014. Mergus serrator host Mergus serrator. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/550993 on 17 Apr 2015.
58 | biketandem. 2014. Ondatra host Ondatra. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/541259 on 17 Apr 2015.
59 | biketandem. 2014. Ondatra host Ondatra. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/565301 on 17 Apr 2015.
60 | biketandem. 2014. Picoides pubescens host Picoides pubescens. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/543808 on 17 Apr 2015.
61 | biketandem. 2014. Podiceps auritus host Podiceps auritus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/571911 on 17 Apr 2015.
62 | biketandem. 2014. Podiceps grisegena host Podiceps grisegena. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/554018 on 17 Apr 2015.
63 | biketandem. 2014. Podilymbus podiceps host Podilymbus podiceps. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/565304 on 17 Apr 2015.
64 | biketandem. 2014. Quiscalus quiscula host Quiscalus quiscula. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/539160 on 17 Apr 2015.
65 | biketandem. 2014. Sayornis phoebe host Sayornis phoebe. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/603922 on 17 Apr 2015.
66 | biketandem. 2014. Setophaga coronata host Setophaga coronata. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/639600 on 17 Apr 2015.
67 | biketandem. 2014. Setophaga palmarum host Setophaga palmarum. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/639599 on 17 Apr 2015.
68 | biketandem. 2014. Spizella passerina host Spizella passerina. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/624562 on 17 Apr 2015.
69 | biketandem. 2014. Trachemys scripta elegans host Trachemys scripta elegans. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/565297 on 17 Apr 2015.
70 | camelcreek. 2014. Daucus carota insect nectar plant Daucus carota. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1171066 on 17 Apr 2015.
71 | gabo. 2014. Tagetes erecta flower species Tagetes erecta. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/896308 on 17 Apr 2015.
72 | gabo. 2014. Tagetes erecta flower species Tagetes erecta. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/909446 on 17 Apr 2015.
73 | getznature. 2013. Sialia sialis host Sialia sialis. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/484573 on 17 Apr 2015.
74 | ggriffiths. 2014. Solidago caesia flower species Solidago caesia. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/899381 on 17 Apr 2015.
75 | ggriffiths. 2014. Staphylea trifolia flower species Staphylea trifolia. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/899595 on 17 Apr 2015.
76 | icosahedron. 2014. Buddleja davidii insect nectar plant Buddleja davidii. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/846762 on 17 Apr 2015.
77 | monivillanueva. 2014. Rosales flower species Rosales. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1022120 on 17 Apr 2015.
78 | sat53. 2013. Hyla versicolor host Hyla versicolor. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/321378 on 17 Apr 2015.
79 | sat53. 2013. Plethodon cinereus host Plethodon cinereus. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/321385 on 17 Apr 2015.
80 | skiman1016. 2013. Rudbeckia hirta insect nectar plant Rudbeckia hirta. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/640661 on 17 Apr 2015.
81 | xinleiliu. 2014. Gallirallus australis associated species with names lookup Gallirallus australis. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/993854 on 17 Apr 2015.
