### ISSUE TITLE
Weidinger et al. 2009. Nest predators of woodland open-nesting songbirds in central Europe

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#121]
As found in http://io9.com/yes-this-is-a-photo-of-a-weasel-riding-a-woodpecker-in-1689046593?utm_campaign=socialflow_io9_twitter&utm_source=io9_twitter&utm_medium=socialflow .

http://onlinelibrary.wiley.com/doi/10.1111/j.1474-919X.2009.00907.x/abstract?systemMessage=Wiley+Online+Library+will+be+disrupted+on+7th+March+from+10%3A00-13%3A00+GMT+%2806%3A00-09%3A00+EST%29+for+essential+maintenance.++Apologies+for+the+inconvenience.&userIsAuthenticated=false&deniedAccessCustomisedMessage=

@millerse something for you?

**Comment by millerse** [comment]
@jhpoelen 

Happy to do this!

**Comment by millerse** [comment]
@jhpoelen 

So I have the online publication ready to go: https://github.com/millerse/Weidinger-et-al.-2009

**Comment by jhpoelen** [comment]
Nice! You are quite fast . . . I'll let you know when the dataset in available and close issue after that.

**Comment by jhpoelen** [comment]
Data now discoverable through GloBI.
