### ISSUE TITLE
Normalize field names for different result type settings

### ISSUE THREAD

**Issue by coding46** [jhpoelen/eol-globi-data#122]
Given the following resources:
(1) http://api.globalbioticinteractions.org/interaction?type=json&interactionType=hasPathogen&limit=1
(2) http://api.globalbioticinteractions.org/interaction?type=json.v2&interactionType=hasPathogen&limit=1

Returned Fieldnames/-paths:
(1) "source_taxon_external_id", "source_taxon_name", "source_taxon_path", "source_specimen_life_stage", "interaction_type", "target_taxon_external_id", "target_taxon_name", "target_taxon_path", "target_specimen_life_stage", "latitude", "longitude", "study_title"
(2) "source.id", "source.name", "source.path", [n.a.], "type", "target.id", "target.name", "target.path", [n.a.], [n.a.], [n.a.], "study"

There should be a normal form of field names so we can transform them automagically without mapping.

**!!! Attention: This is about to break things.**

**Comment by jhpoelen** [comment]
Thanks for sharing your idea. Just added name/value pairs for jsonv2 consistent with the json response. In order to make transition smooth, the old values in the json.v2 are still around. This means that some data will be duplicated. The result for api.globalbioticinteractions.org/interaction?type=json.v2&interactionType=hasPathogen&limit=2 looks like:


```json
[{"study_title":null,"study":null,"target_taxon_external_id":"EOL:4965326","latitude":null,"interaction_type":"hasPathogen","source":{"path":"Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens","name":"Homo sapiens","id":"NBN:NHMSYS0000376773"},"type":"hasPathogen","source_taxon_path":"Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens","target":{"path":"Cellular organisms | Eukaryota | Opisthokonta | Metazoa | Eumetazoa | Bilateria | Protostomia | Ecdysozoa | Nematoda | Chromadorea | Spirurida | Thelazioidea | Thelaziidae | Thelazia | Thelazia callipaeda","name":"Thelazia callipaeda","id":"EOL:4965326"},"target_specimen_life_stage":null,"target_taxon_path":"Cellular organisms | Eukaryota | Opisthokonta | Metazoa | Eumetazoa | Bilateria | Protostomia | Ecdysozoa | Nematoda | Chromadorea | Spirurida | Thelazioidea | Thelaziidae | Thelazia | Thelazia callipaeda","source_taxon_external_id":"NBN:NHMSYS0000376773","source_specimen_life_stage":null,"source_taxon_name":"Homo sapiens","target_taxon_name":"Thelazia callipaeda","longitude":null},{"study_title":null,"study":null,"target_taxon_external_id":"NBN:BMSSYS0000017767","latitude":null,"interaction_type":"hasPathogen","source":{"path":"Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens","name":"Homo sapiens","id":"NBN:NHMSYS0000376773"},"type":"hasPathogen","source_taxon_path":"Animalia | Chordata | Mammalia | Primates | Hominidae | Homo | Homo sapiens","target":{"path":"Ascomycota | Sordariomycetes | Ophiostomatales | Ophiostomataceae | Sporothrix | Sporothrix schenckii","name":"Sporothrix schenckii","id":"NBN:BMSSYS0000017767"},"target_specimen_life_stage":null,"target_taxon_path":"Ascomycota | Sordariomycetes | Ophiostomatales | Ophiostomataceae | Sporothrix | Sporothrix schenckii","source_taxon_external_id":"NBN:NHMSYS0000376773","source_specimen_life_stage":null,"source_taxon_name":"Homo sapiens","target_taxon_name":"Sporothrix schenckii","longitude":null}]
```

Once we settle on a data representation, we can phase out the "old" parameter names. 

Curious to hear your thoughts on this.

**Comment by coding46** [comment]
Hmm, now it's getting more complicated, cause of 2 different representations without a normalizing aspect if I get it right.

I thought more of a way like (just a raw idea):

json | json.v2
-----|--------
source_taxon_external_id | source_taxon.external_id
source_taxon_path | source_taxon.path
source_taxon_name | source_taxon.name
... | ...

I really like the idea of the deprecating strategy until we found nice fitting representation.
