### ISSUE TITLE
two decapoda taxon pages present in EOL - should they be merged?

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#125]
In GloBI, two separate Decapoda taxa are reported in EOL:

Decapoda http://eol.org/pages/10948079
Decapoda http://eol.org/pages/1183

@jhammock @KatjaSchulz should these two pages be merged?

**Comment by KatjaSchulz** [comment]
Indeed, fixed, at least for now: http://eol.org/pages/10948079

**Comment by jhpoelen** [comment]
@KatjaSchulz Thanks for your quick response . . . closing issue.
