### ISSUE TITLE
Access TTD-TCN data from Darwin Core Archive?

### ISSUE THREAD

**Issue by seltmann** [jhpoelen/eol-globi-data#126]
I have two darwin core files of specimen data now online for testing by idigbio, using our aec:associatedTaxa extension. 

http://amnh.begoniasociety.org/dwc/

First step toward getting these interactions into EOL? I can produce a globi specific output, but need guidance. 

This is not the permanent URL but there will be one after some testing is finished.

**Comment by jhpoelen** [comment]
@seltmann took a first pass at integrating the archives you provided (bees and tri-trophic): what a wealth of information! Wow! 

I've built a generic importer for your darwin core archive extension. To incorporate an archive into GloBI, a GitHub repository may be created that contains a pointer to the archive and some minor configuration parameter. I've provided two examples [here](https://github.com/globalbioticinteractions/digital-bee-collections-network) and [here](https://github.com/globalbioticinteractions/tri-trophic-thematic-collection-network). For more information related to the GitHub based extension mechanism see http://github.com/globalbioticinteractions/template-dataset .

Am I correct to assume that the relationship terms / URIs will be populated as some point?

Also, please let me know if you'd like me to either move or reconfigure the bee and tri-trophic archives to upgrade to a more recent archive.

I'll close this issue once the first pass of the data makes it into GloBI. Given the volume of data, this may take awhile.

**Comment by seltmann** [comment]
@jhpoelen 
Sounds great!

---Am I correct to assume that the relationship terms / URIs will be populated as some point?
OOPS. Yes, that field should be populated and I have URI for all of the relations we are presently using. Need to fix and update. Should be able to update in the next few days so the URI appear. Will get back to you.

---Also, please let me know if you'd like me to either move or reconfigure the bee and tri-trophic archives to upgrade to a more recent archive.
A few things. We are continuing to add data to the tri-tropic archive and will be adding/updating through the summer at an advanced pace. I suspect we will add in 40 thousand more records before the end of June and many will be corrected. What do updates in GloBI look like?

The archives and the Associations Extension we are using are waiting for review from @iDigBio @godfoder. Some changes may occur for iDigBio in the process and the final published archive will move to a different server. If these changes are substantial, I can produce a different version of the archive for GloBI and iDigBio. 

So here is a final and perhaps more fun and metaphysical issue. These data come directly from collection records and labels on specimens. So some of the data are wrong! Of course, even published data, based on old observations can be incorrect. Do you use any filtering or confidence methods for the records? I have been working with finding methods for filtering records and binning them based on frequency and a few heuristics. 

In the simplest terms, if you see an association between a species and an associate 3 or > times, and if those are unique collecting events (not specimens at the same event), you can be quite confident in the association. However, this does reduce the number of associations and trims off some of the rarer (and perhaps more interesting) taxa.

**Comment by jhpoelen** [comment]
@seltmann thanks for your detailed response. 

**about updates** GloBI updates every day or so to changes in data sources should propagate in the order of days. It would help if you could publish archives that are available at a stable url (e.g. perhaps tcn...-current.zip ?). This way, we don't have to manually upgrade the urls each time a new version is available. If you have another suggestion on how to automatically point to the most recent archives, please do let me know.

**changes to darwin core archive** no need to make a special GloBI archive: I'd rather use the one that is used by others (e.g. iDigBio) also.

**about detecting suspicious interactions** GloBI attempts to make all interaction data easily available. While GloBI doesn't make any claim on what is a "good" interaction and what is a "bad" interaction, applications can be built on top of GloBI that incorporate certain criteria for using interactions that meet specific criteria (e.g. only names that matched an external taxonomy;  perhaps only include interactions that were reported by two or more studies; or only include interactions that have a collection location and time). These applications can then be used to communicate suspicious data (e.g. interactions, references) to the contributors. If the data contributors cannot apply the corrections for whenever reason, the records in question can be excluded as part of the automated GloBI ingestion process. In your case, you might want to apply data quality algorithms before producing the archive to filter out known "bad" records. And . . . you can use GloBI to poke around a look for more suspicious interactions.

PS Just curious - are you also planning to extract interactions from VertNet (see #63) ?

**Comment by jhpoelen** [comment]
@seltmann TTD-TCN data can now be discovered through GloBI. Since the interaction types were not provided, a generic "interactsWith" has been used to document the associations. I am hoping that future version of the archives will provide more detailed descriptions of the interactions using some interaction vocabulary (e.g. [relation ontology](http://www.ontobee.org/browser/index.php?o=RO)). Ideally we'll figure out some naming convention to allow GloBI to ingest updates without having to do any manual configuration. The interactions are harvested by Encyclopedia of Life every month, so there might be a bit of a delay until you see TTD-TCN data show up on eol.org .

Here's a screenshot from what I discovered at http://www.globalbioticinteractions.org/#sourceTaxon=Hymenoptera&interactionType=interactsWith&accordingTo=amnh.org : 
![screen shot 2015-04-21 at 9 38 21 am](https://cloud.githubusercontent.com/assets/1084872/7257435/94c04320-e80a-11e4-8d93-c0197f93e255.png)

I've like to invite you to poke around a bit and report issues / ideas in separate issues.

**Comment by seltmann** [comment]
Great the the interactions are now searchable from GloBI! And soon on EOL

I am using these URI for our relations:
https://docs.google.com/spreadsheets/d/1GCChIIChXvf98oMFg7OKUznflZiSP_XLdI_6mm0IP2w/edit?usp=docslist_api

You are welcome to use the list to update the interacts with relationship now if you like, or wait until the next update. The archives will only be moved once. At present they are on a development server for idigbio review. I'll move them to the production (and stable) location when that review is complete.

I understand that GloBI provides only raw hypothesis of interactions. Is it filtered for EOL? We also try to provide only the raw data as many of the interactions are unpublished to science and we are in the process of evaluating them. In other words, it is not our objective to clean up the data regarding correct/incorrect information interactions because we do that using statistics in post processing. Not an issue for research, but just curious how it is handled for a consumer product like EOL.
Katja
