### ISSUE TITLE
include "basis of record" information to the interaction data

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#127]
@seltmann suggested that adding basis of record (similar to http://rs.tdwg.org/dwc/terms/#basisOfRecord) would be a useful addition to the existing interaction data information captured by GloBI. In fact, a similar question came up in a recent personal communication, along the lines of: How do I only select interaction records that were obtained through field observation or gut content analysis.

**Comment by ClareGray** [comment]
Hi Jorrit, published papers on food webs often contain a blend of interactions they have discovered themselves, and ones harvested from the literature. Being able to distinguish between the two (sometimes this isn't possible without contacting the author) is important when re-using these links. An interaction that has been re-used many times and published many times might have only been observed (through gut contents analysis or field observation) once. Being able to determine this would be important for me to use GloBI in my research.

**Comment by jhpoelen** [comment]
A first pass of basisOfRecords is now available (see screenshot) for some source data sources (e.g. inaturalist (HumanObservation), Tri-Trophic Thematic Collection Network (PreservedSpecimen/LabelObservation), GoMexSI (Literature, http://gomexsi.tamucc.edu) and Avian Diet Database (Literature, https://github.com/hurlbertlab/dietdatabase/).

@ClareGray @seltmann please let me know if there's other terms that you'd like to see used.

![screen shot 2015-05-04 at 1 18 01 pm](https://cloud.githubusercontent.com/assets/1084872/7461810/8e8b996c-f261-11e4-9f88-5644e41d8ced.png)

**Comment by jhpoelen** [comment]
Re-opening issue - two reasons:

1. Because of #136 we had to revert the version of GloBI prior to the version that introduced basisOfRecord, so technically the functionality is not (yet) available.
1. No (reasonably complete) ontology exists for basis of record. We need some sort of ontology to make the basis of record readable. This came up in a recent discussion with Suzi Lewis et al. (http://tech4measurement.berkeley.edu/2015/05/07/bids-moorea-and-crete.html).

@cmungall could you forward this to Suzi?

**Comment by seltmann** [comment]
Jorrit,
The list for basisOfRecordLabel fills our needs. The only list I know that is available is: http://wiki.tdwg.org/twiki/bin/view/DarwinCore/BasisOfRecord but I agree that it is incomplete.
@egbot you may be interested in this conversation.

**Comment by jhpoelen** [comment]
@seltmann thanks for confirming that terms "Literature", "PreservedSpecimen", "HumanObservation" and "LabelObservation" are sufficient for your purposes, but might not be for others. 

I am hoping that this discussion will spark some interest in creating an hierarchical vocabulary / ontology to describe how a fact / measurements / observations was obtained. 

Something like: 
Observation / { HumanObservation | MachineObservation }
Literature / { ManualLiteratureTranscription | AlgorithmicLiteratureTranscription }
Specimen / { PreservedSpecimen | FossilSpecimen | Image | Video }
Inferred / { Model | Simulation | WordOfMouth? }

The longer I think about this, the more esoteric terms I can come up with. For now, it might be more practical to link to existing terms such as tdwg's basis of record, and create a placeholder for other terms, with the hope that we can link to a more complete list in the (near) future. Perhaps @cmungall and  @selewis have some tips on how to move forward on this.

@seltmann do you have a definition / IRI for the term "LabelObservation"? I didn't see this term in the list provided by tdwg's basis of record.

**Comment by seltmann** [comment]
@jhpoelen LabelObservation is a term we created to distinguish an observation recorded on an insect label that is associated with a Specimen from a HumanObservation that does not have an associated Specimen. Another specialized type of Observation? Typically they are HumanObservations and could be extended to include observations found in the text of field notebooks.

Not sure, but perhaps this is within scope for the Biological Collections Ontology. @robgur may have that answer.

**Comment by jhpoelen** [comment]
Issue #136 has been fixed and the basisOfRecord fields are now available (whenever defined). Whenever a better / more extensive ontology/vocabulary is available, we'll stick with what we have now: something is better than nothing ; ).
