### ISSUE TITLE
select data fields in api using ?fields=one,two,three

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#128]
Currently, data fields in api (see https://github.com/jhpoelen/eol-globi-data/wiki/API) can be selected using repeated ```field``` query parameter like:

http://api.globalbioticinteractions.org/interaction?interactionType=eats&sourceTaxon=Enhydra&field=source_taxon_name&field=target_taxon_name 

However, in https://github.com/danielabar/globi-proto/issues/1#issuecomment-87067444 @danielabar suggested to also use a ```fields``` query parameters, using comma's rather than repeated params like:

http://api.globalbioticinteractions.org/interaction?interactionType=eats&sourceTaxon=Enhydra&fields=source_taxon_name,target_taxon_name

**Comment by danielabar** [comment]
Thanks this would be very useful if could be implemented :-)

**Comment by jhpoelen** [comment]
@danielabar thanks for your suggestion, the functionality is now available as requested. Please re-open this issue if you see any issues / have questions.
