### ISSUE TITLE
missing "has host" reference on eol.org Bumblebee (Bombus) data page 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#130]
It appears that most reference on eol data page http://eol.org/pages/104136 are present, and some are (mysteriously) missing. 

While bumblebee host Spanish Daisy *Helenium amarum* has a source and reference:
![screen shot 2015-04-15 at 9 36 11 am](https://cloud.githubusercontent.com/assets/1084872/7164095/e63fbf1c-e352-11e4-966e-5728e3b6911e.png)

However, another two claims for bumblebee host *Veronica salicifolia* did not have the reference:
![screen shot 2015-04-15 at 9 47 02 am](https://cloud.githubusercontent.com/assets/1084872/7164369/a44426e6-e354-11e4-934e-3cd698cf93d7.png)

Expected references were:
Colin. 2015. Bombus associated species with names lookup Hebe salicifolia. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/1268093 on 14 Apr 2015. 

Sue Mcgaw. 2014. Bombus associated species with names lookup Veronica salicifolia. iNaturalist.org. Accessed at http://www.inaturalist.org/observations/987938 on 14 Apr 2015. 

I tried to troubleshoot by inspecting the jsonld trait info using http://eol.org/api/traits/104136, but unfortunately, the server timed out after exactly 1 minute:

```
$ curl http://eol.org/api/traits/104136 > ~/Desktop/104136.jsonld
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   182  100   182    0     0      3      0  0:01:00  0:01:00 --:--:--    44
$ cat ~/Desktop/104136.jsonld 
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>
```

@jhammock @jrice do you have any idea why these references went missing?

**Comment by jhpoelen** [comment]
For some reason, the problem of the missing references has disappeared. Not sure why. Closing issue.

![screen shot 2015-05-01 at 1 59 57 pm](https://cloud.githubusercontent.com/assets/1084872/7437203/73dc4818-f00a-11e4-9023-04c906059a4f.png)

**Comment by jhammock** [comment]
Weird. Thanks for the update. Sorry we were not more pro-active, stil RFSM (recovering from server move)
