### ISSUE TITLE
include fuzzy taxon name matches to suggest name corrections

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#131]
In personal communication, @ahhurlbert suggested to include fuzzy taxon name matches for names that did not match again external taxonomies. These fuzzy name matches can then be used for data providers / curators to speed up the name correction process.

WIth this feature, a taxon name "health" report can be generated that looks something like:

provided name |  similar name 
--- | --- | --- 
Homo zapiens |  *Homo sapiens* ([ITIS](http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=180092))
Avez |  *Aves* ([ITIS](http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=174371))

@ahhurlbert please confirm I worded this correctly

**Comment by ahhurlbert** [comment]
Yes, this would be great.

**Comment by jhpoelen** [comment]
@ahhurlbert first pass of fuzzy matching is now available. Please run the cypher query here: http://tinyurl.com/hurlbertTaxonNameReportV3 to see the results (see attached screenshot for example). Fuzzy matching algorithms from globalnames.org are used to come up with the candidates. Hopefully this will help expedite the fixing of typos or other name issues. Please re-open the issue if you have any concerns. 

PS note that his feature help provide a basis for a name health report. The report itself is now only available through the provided query for your contributions. This query should be modifiable to include names provided by other contributors.

![screen shot 2015-04-30 at 3 53 21 pm](https://cloud.githubusercontent.com/assets/1084872/7424010/16c26ee6-ef51-11e4-837d-8e35eec70643.png)
