### ISSUE TITLE
Add in Arctos collection specimens interactions

### ISSUE THREAD

**Issue by mkoo** [jhpoelen/eol-globi-data#134]
Arctos (http://arctos.database.museum/SpecimenSearch.cfm) collection management system stores relationships between specimens of 85 collections which we'd like to set up a dynamic integration point for GloBI. 

I'll return with more information about how we can make the databases interact!

Ex. 
http://arctos.database.museum/guid/MVZ:Bird:180448 has relationship of ATE
http://arctos.database.museum/guid/MVZ:Herp:241200

**Comment by jhpoelen** [comment]
@mkoo good to meet you today at BIDS (Berkeley Institute for Data Science) and thanks for your pointer to the arctos interaction data! I am looking forward to integrating your interactions data and make it accessible and searchable through GloBI. Please let me know if there's more information available that help establish this connection. Meanwhile, I'll poke around and see how easy it is to extract the interactions using the existing arctos access methods.

**Comment by jhpoelen** [comment]
@mkoo it sounds like ecoengine is not (yet) providing access to the fields that describe the host-parasite association. However, the host (http://doi.org/10.15468/5o0fct) and parasite (http://doi.org/10.15468/ou1lf2) archives that are available through GBIF do contain the fields. For some reason the archives are published separately. From what I can tell these are beautiful interaction datasets . Thanks for pointing them out!

**Comment by millerse** [comment]
@jhpoelen Hey has anyone taken a stab at this?

**Comment by jhpoelen** [comment]
Not that I know of. Last time I checked (about two years ago), it seemed a bit tricky to get to the interaction data. I think it would be great if you could sprinkle your data magic on it!

**Comment by millerse** [comment]
Well, I'll give it a shot.

**Comment by jhpoelen** [comment]
@mkoo curious to hear updates (if any) on Actos' ability / policy on openly accessing association (e.g., parasite, host) records. The idea is that GloBI would index Arctos to point folks to your records from GloBI.

**Comment by jhpoelen** [comment]
Just noticed that in GBIF, the associations are captured using the "associated occurrences" field with values like ```(eaten by) MVZ:Bird http://arctos.database.museum/guid/MVZ:Bird:180448``` (see https://www.gbif.org/occurrence/1145553661 and attached screenshot).

![Screenshot from 2019-05-09 16-03-09](https://user-images.githubusercontent.com/1084872/57492079-4d4a5280-7274-11e9-976f-2e3546e32fb1.png).

Perhaps a custom integration DwC-A integration can be built using these fields and value structure.

**Comment by jhpoelen** [comment]
This is a slight different approach than those used by Tri-Trophic Thematic Collections Network 
 and https://trias-project.github.io/uredinales-belgium-checklist/ (see https://www.globalbioticinteractions.org/2018/08/16/models-in-fashion/#darwin-core-archives).

**Comment by jhpoelen** [comment]
First pass at integrating Arctos associations via Vertnet resulting in about 68018 interaction records (see [interactions.tsv.gz](https://github.com/jhpoelen/eol-globi-data/files/3357462/interactions.tsv.gz)). These records are extracted line-by-line from dwca's, so includes duplicates like:

```shell
$ zcat interactions.tsv.gz | grep "http://arctos.database.museum/guid/CHAS:Ento:2018.1.106"
http://arctos.database.museum/guid/CHAS:Ento:2018.1.106?seid=4179400		Ixodoidea						http://purl.obolibrary.org/obo/RO_0002444	parasiteOf	http://arctos.database.museum/guid/CHAS:Bird:2018.1.106		Melospiza georgiana										PreservedSpecimen	2017-10-16T00:00:00Z	41.926469	-87.634817		Peggy Notebaert Nature Museum, 2430 North Cannon Drive, Chicago		http://arctos.database.museum/guid/CHAS:Ento:2018.1.106	http://arctos.database.museum/guid/CHAS:Ento:2018.1.106	globalbioticinteractions/vertnet	CHAS Entomology Collection (Arctos) - Version 13.27	http://ipt.vertnet.org:8080/ipt/archive.do?r=chas_ento	2019-07-03T23:44:09.350Z	855a13aca391ce3532ce0aaf5869bcafda5bee3956372aae88b0165686ae0fdd	0.3.5-SNAPSHOT
http://arctos.database.museum/guid/CHAS:Bird:2018.1.106?seid=4179394		Melospiza georgiana					http://purl.obolibrary.org/obo/RO_0002453	hostOf	http://arctos.database.museum/guid/CHAS:Ento:2018.1.106		Ixodoidea	PreservedSpecimen	2017-10-16T00:00:00Z	41.926469	-87.634817		Peggy Notebaert Nature Museum, 2430 North Cannon Drive, Chicago		http://arctos.database.museum/guid/CHAS:Bird:2018.1.106	http://arctos.database.museum/guid/CHAS:Bird:2018.1.106	globalbioticinteractions/vertnet	CHAS Ornithology (Arctos) - Version 2.23	http://ipt.vertnet.org:8080/ipt/archive.do?r=chas_birds	2019-07-03T23:44:09.350Z	855a13aca391ce3532ce0aaf5869bcafda5bee3956372aae88b0165686ae0fdd	0.3.5-SNAPSHOT
```
fyi @dustymc

**Comment by jhpoelen** [comment]
A first pass at a life integration Arctos integration is now available via GloBI . Subsequent improvements  will be recorded in separate issues.

See screenshot below https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fvertnet - 
![Screenshot from 2019-07-08 07-49-09](https://user-images.githubusercontent.com/1084872/60821647-d1c42f00-a158-11e9-87ab-aa74637072a9.png)

Thanks for being patient @mkoo .
