### ISSUE TITLE
candidate interaction terms that need mapping to terms in OBO relations ontology 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#137]
Inspired by meeting at BIDS (http://tech4measurement.berkeley.edu/2015/05/07/bids-moorea-and-crete.html), I compiled a list of interaction terms that are now coarsely mapped existing interaction types, but can probably do with a more specific designation.

The list is mostly listing interaction types used by Malcolm Storey in the http://bioinfo.org.uk dataset.

@cmungall let me know if this list is useful . . . is suzi on github?

| provided term | currently mapped to term label | mappted to uri | source |
| --- | --- | --- | --- |
| Animal / associate | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / carrion / dead animal feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / dung / associate | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / dung / debris feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / dung / oviposition | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / dung / saprobe | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / endozoite | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / epizoite | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / gamete vector / crsss fertilises | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / guest | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / honeydew feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / inquiline | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / kill | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / kleptoparasite | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasite / ectoparasite / blood sucker | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasite / ectoparasite / sweat sucker | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasite / ectoparasite / tear sucker | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasite / ectoparasite | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasite / endoparasite | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasite | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasitoid / ectoparasitoid | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / parasitoid / endoparasitoid | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Animal / phoresy | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / predator / stocks nest with | preys upon | http://purl.obolibrary.org/obo/RO_0002439 | bioinfo.co.uk |
| Animal / resting place / on | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / resting place / under | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / resting place / within | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Animal / sequestreats | http://purl.obolibrary.org/obo/RO_0002470s | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 |
| Animal / slave maker | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Bacterium / farmer | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Bacterium / predator | preys upon | http://purl.obolibrary.org/obo/RO_0002439 | bioinfo.co.uk |
| Foodplant / collects | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / debris feeder | eats | http://purl.obolibrary.org/obo/RO_0002470 | bioinfo.co.uk |
| Foodplant / endophyte | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / false gall | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / gall | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / hemiparasite | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Foodplant / immobile silken tube feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / internal feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / miner | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / mobile cased feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / mutualist | symbiotically interacts with | http://purl.obolibrary.org/obo/RO_0002440 | bioinfo.co.uk |
| Foodplant / mycorrhiza / ectomycorrhiza | symbiotically interacts with | http://purl.obolibrary.org/obo/RO_0002440 | bioinfo.co.uk |
| Foodplant / mycorrhiza / endomycorrhiza | symbiotically interacts with | http://purl.obolibrary.org/obo/RO_0002440 | bioinfo.co.uk |
| Foodplant / mycorrhiza | symbiotically interacts with | http://purl.obolibrary.org/obo/RO_0002440 | bioinfo.co.uk |
| Foodplant / nest | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / open feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / robber | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / roller | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / sap sucker | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / saprobe | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / secondary infection | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / shot hole causer | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / spinner | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / spot causer | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / visitor / nectar | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / visitor | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Foodplant / web feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / associate | http://purl.obolibrary.org/obo/RO_0002470 | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 |
| Fungus / external feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / gall | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / infection vector | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / internal feeder | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / nest | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / parasite / endoparasite | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Fungus / resting place / on | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / resting place / within | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Fungus / saprobe | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Inhibits or restricts the growth of | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Lichen / associate | http://purl.obolibrary.org/obo/RO_0002470 | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 |
| Lichen / gall | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Lichen / grows on or over | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Lichen / kleptoparasite | parasite of | http://purl.obolibrary.org/obo/RO_0002444 | bioinfo.co.uk |
| Lichen / nest | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Lichen / photobiont | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Lichen / saprobe | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Lichen / sequestrate | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / associate | http://purl.obolibrary.org/obo/RO_0002470 | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 |
| Plant / epiphyte | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / grows among | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / grows inside | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / hibernates / on | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / hibernates / under | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / hibernates / within | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / nest | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / resting place / among | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / resting place / on | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / resting place / under | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / resting place / within | biotically interact with | http://purl.obolibrary.org/obo/RO_0002437 | bioinfo.co.uk |
| Plant / vector | has vector | http://purl.obolibrary.org/obo/RO_0002460 | bioinfo.co.uk |

**Comment by cmungall** [comment]
For some of these we can add more specific relations. But at some level it makes sense to store this some other way. For example, the first interaction here:

http://www.bioinfo.org.uk/html/Trichogramma_brassicae.htm
http://www.bioinfo.org.uk/html/b149795.htm

which is actually a causal chain of interactions - the initial mating (within the same species), the following and hitchhiking interaction, and finally the parasiting of the offspring. The first maybe isn't in scope for globi but might be nice to capture one day. For the subsequent two, I don't know from the bioinfo dataset if you would only be able to capture one of these. I would try and capture the more specific nuances using a behavior term (e.g. following pheromone trail), and use relationships at a broader level. There are a few candidates for behavior terms here - NBO covers all animals, but is not actively maintained. However, if we can do a focused set for illustrative purposes I would use the social insect behavior ontology, perhaps generalizing to all insects - https://github.com/obophenotype/sibo

Suzi is @selewis

**Comment by jhpoelen** [comment]
@cmungall should be easy to add new mappings in the future. Perhaps we can focus on species interactions that are relatively straight forward and commonly used (e.g. ecto/endo/klepto-parasitism). Also I could definitely benefit from a second pair of eyes on this. Also shouldn't http://purl.obolibrary.org/obo/RO_0002444 be a trophic interaction? I am assuming that the parasite is extracting some form something from it's host?

**Comment by jhpoelen** [comment]
Most terms have been added.
