### ISSUE TITLE
EOL API throws 503s (service unavailable) or 504s (gateway timeout) in when handling many (sequential) requests

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#138]
GloBI uses EOL api to resolve and link taxonomic names that are included in data sources.

In and around 2015-05-11 19:23:13,938 UTC / 2015-05-11 21:23:13,938 (CEST, central european standard time), the EOL api started to provide 503s (or service unavailable exceptions), at least 11 in a row (see log below).

@jhammock is this expected behavior?

```
2015-05-11 21:19:43,440 [main] WARN  org.eol.globi.service.TaxonEnricherImpl - f
ailed to find a match for [{pathIds=null, path=null, commonNames=null, pathNames
=null, name=Mabea piriri Aubl., rank=null, externalId=EOL:1155504}] in [EOLServi
ce]
org.eol.globi.service.PropertyEnricherException: failed to lookup [http://eol.or
g:80/api/pages/1.0/1155504.json?images=1&videos=0&sounds=0&maps=0&text=0&iucn=fa
lse&subjects=overview&licenses=all&details=false&common_names=true&synonyms=fals
e&references=false&format=json]: http status [503]   
...
2015-05-11 21:20:35,661 [main] WARN  org.eol.globi.service.TaxonEnricherImpl - f
ailed to find a match for [{pathIds=null, path=null, commonNames=null, pathNames
=null, name=Mabea piriri, rank=null, externalId=null}] in [EOLService]
org.eol.globi.service.PropertyEnricherException: failed to lookup [http://eol.or
g:80/api/search/1.0.xml?q=Mabea+piriri&exact=true]: http status [503]  
...
2015-05-11 21:21:28,510 [main] WARN  org.eol.globi.service.TaxonEnricherImpl - f
ailed to find a match for [{pathIds=null, path=null, commonNames=null, pathNames
=null, name=Mabea, rank=null, externalId=null}] in [EOLService]
org.eol.globi.service.PropertyEnricherException: failed to lookup [http://eol.or
g:80/api/search/1.0.xml?q=Mabea&exact=true]: http status [503] 
...
```

**Comment by jhammock** [comment]
Eeek! Sorry, did not see this last night. That'll teach me. We noticed a total API outage this morning, for about 100 minutes, which seems to be resolved now. Jeremy found it somewhat mysterious; I pointed him to this in case it's related.

**Comment by jhpoelen** [comment]
@jhammock thanks for asking around . . . any idea what the root cause was?

**Comment by jhpoelen** [comment]
@jhammock just did some integration testing and the EOL API seems to be unavailable all together. I would really like for this to work, let me know how I can help.

**Comment by jhpoelen** [comment]
@jhammock @jrice I noticed that the EOL twitter feed said that [the API issues were solved](https://twitter.com/eol/status/598113203583905793). For some reason, I am still seeing the failures that I saw earlier. 

It seems that the API is unavailable for some time after a single request is made. This would also explain why the API ping monitor I set up frequently flips from down/up with up to 7-10 minutes of downtime. Also, an automated test suite for EOL APIs fails consistently (e.g. see [a recent build here](https://travis-ci.org/jhpoelen/eol-globi-data/builds/62280873) ).

The current state of the EOL API blocks GloBIs progress (and I am assuming others that use the API). Please let me know what I can do to make use of the EOL API again.

**Comment by JRice** [comment]
Thanks for reporting, Jorrit.

Indeed, the API is intermittently down now (around 5 minutes at a time,
from what I can see)... I'm looking into it, but it is extremely puzzling.
:|

**Comment by jhpoelen** [comment]
@JRice thanks for your response. I've setup a uptimerobot.com notification on http://eol.org/api/ping/1.0.json . Let me know if you'd like to get the email notifications also.

**Comment by jhpoelen** [comment]
@JRice thanks for analyzing and resolving the issue. Apparently, the outages were caused by an overactive EOL api client. This client is no longer active.
