### ISSUE TITLE
prey name corrections

### ISSUE THREAD

**Issue by tmitchell1** [jhpoelen/eol-globi-data#140]
It was brought to our attention that there are a couple of misspellings in the Blewitt data.
Arm mierii should be Armases miersii and
Fun grandis should be Fundulus grandis
@jhpoelen @jsimons9

**Comment by jhpoelen** [comment]
Hi @tmitchell1 ! Thanks for your message. Misspellings you mentioned have been incorporated in the taxon name corrections file (see https://github.com/jhpoelen/eol-globi-data/commit/f15329cbf761815659c0c26e57eb1399c4bdb22a).  I will close this issue when the corrections have been processed by GloBI.

**Comment by jhpoelen** [comment]
@tmitchell1 changes have propagated. Please re-open issue if this is not the case.
