### ISSUE TITLE
Seton, E.T. (1929) Lives of Game Animals. Doubleday, Doran & Co., Garden City N.Y., 506 pp.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#142]
@diatomsRcool mentioned the following text:

Seton, E.T. (1929) Lives of Game Animals. Doubleday, Doran & Co., Garden City N.Y., 506 pp.

in issue #118 . From context, it seems that the text contains species interaction data.  A quick search on http://crossref.org led to http://www.biodiversitylibrary.org/bibliography/82142#/summary . Unfortunately, I was unable to download the text due to some error.

@millerse - are you able to access this resource? If so, would you consider to extract species interaction information from it?

**Comment by millerse** [comment]
@jhpoelen I took a look. I cannot directly download the book, but it appears that the ORC is still there.  I can also looked at the Smithsonain Libraries to see if we have a copy of the book.

**Comment by jhpoelen** [comment]
@millerse I sent a message to BHL folks reporting the issue (see copy below). For the time being, we might have to resort to the physical copy of the book. 

Hey Anne @diatomsRcool would you happen to have a soft copy of Seton 1929 lying around that Sarah @millerse can use? 

```
The Biodiversity Heritage Library has received the following feedback:

Name: Jorrit Poelen (Global Biotic Interactions)
URL: http://www.biodiversitylibrary.org/item/155739

To Whom It May Concern:

In recent discussion (see https://github.com/jhpoelen/eol-globi-data/issues/142) the publication: Seton, E.T. (1929) Lives of Game Animals. Doubleday, Doran & Co., Garden City N.Y., 506 pp. came up. 

I was happy to see that BHL had the publication in the collection, however, it seems that the scans are not available for some reason. Is there anything that can be done to make Seton 1929 available digitally?

Thanks,
-jorrit

http://globalbioticinteractions.org

Thank you for submitting your feedback.  If requested or required, a staff member will contact you shortly.

Requests for scanning are limited to the collections of our BHL member libraries.  While we make every effort to fulfill requests, they are processed in the order they are received.  It may take several weeks to months before scans are available on our website depending on your request.
```

**Comment by diatomsRcool** [comment]
Sorry, don't have a copy...

On 6/25/2015 12:27 PM, Jorrit Poelen wrote:
>
> @millerse <https://github.com/millerse> I sent a message to BHL folks 
> reporting the issue (see copy below). For the time being, we might 
> have to resort to the physical copy of the book.
>
> Hey Anne @diatomsRcool <https://github.com/diatomsRcool> would you 
> happen to have a soft copy of Seton 1929 lying around that Sarah 
> @millerse <https://github.com/millerse> can use?
>
> |The Biodiversity Heritage Library has received the following feedback: 
> Name: Jorrit Poelen (Global Biotic Interactions) URL: 
> http://www.biodiversitylibrary.org/item/155739 To Whom It May Concern: 
> In recent discussion (see 
> https://github.com/jhpoelen/eol-globi-data/issues/142) the 
> publication: Seton, E.T. (1929) Lives of Game Animals. Doubleday, 
> Doran & Co., Garden City N.Y., 506 pp. came up. I was happy to see 
> that BHL had the publication in the collection, however, it seems that 
> the scans are not available for some reason. Is there anything that 
> can be done to make Seton 1929 available digitally? Thanks, -jorrit 
> http://globalbioticinteractions.org Thank you for submitting your 
> feedback. If requested or required, a staff member will contact you 
> shortly. Requests for scanning are limited to the collections of our 
> BHL member libraries. While we make every effort to fulfill requests, 
> they are processed in the order they are received. It may take several 
> weeks to months before scans are available on our website depending on 
> your request. |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jhpoelen/eol-globi-data/issues/142#issuecomment-115309745>.
>

-- 
Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by jhpoelen** [comment]
Here's a reply from BHL:

--------

from: feedback@biodiversitylibrary.org
Thu, 25 Jun 2015 11:45:52 -0700 (PDT)

Dear Jorrit Poelen,

Thank you for submitting your feedback to the Biodiversity Heritage Library concerning the digital scans of Seton, E.T. (1929) Lives of game animals [...]. Your observation that the digital files are missing is much appreciated. 

These scans were created by an institution that is not affiliated with the BHL, and therefore we are not responsible for their content. The files were automatically ingested into the BHL portal from the Internet Archive (IA). Later, IA removed the images from their collection. Therefore, the images were no longer being served to BHL. 

Normally, we would ask a BHL Partner Library to scan this title and replace this record.  However, unfortunately, the publication date for this work is beyond the copyright cut-off date. I have removed the title from the BHL, in accordance with our policies regarding copyright law. We are unable to offer works published in or after 1923 unless we obtain permission from the copyright holder. For more information, see our guide. 

If you have any information that might help us obtain permission to scan this work, please share it with us. We have been able to broker agreements with a number of copyright holders such that the BHL does hold some in-copyright materials.  

From the link you sent us, I can see that there was a question about the holdings of the Smithsonian Libraries (SIL), one of our partners, and where the Secretariat and other staff (including myself) are based.  I can see that this title is held by SIL in the Mammals Library at the National Museum of Natural History under bib 110484. You may also find the text at a number of BHL Partner Institutions and other libraries under OCLC number 11464601. I hope that you and your colleagues find this information of use.

Again, thank you for submitting your feedback to BHL. Users such as yourself help the BHL to improve, and we appreciate our users taking the time to inform us of errors. It is unfortunate that we could not be of more help to you in this instance. I hope that you will continue to find other materials that you require in the BHL and to offer us suggestions for the improvement of our digital collections.

With thanks,

Jacqueline E. Chapman
Digital Collections Librarian

----------

**Comment by millerse** [comment]
@jhpoelen I can.  I'll get on that starting Monday.

**Comment by diatomsRcool** [comment]
World Cat says there is a copy at Smithsonian and at the Library of 
Congress, which is right across the street.

On 6/25/2015 3:16 PM, Jorrit Poelen wrote:
> Lives of game animals

-- 
Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by millerse** [comment]
@diatomsRcool @jhpoelen 
Alright here is the deal.

The SI libraries have a copy of the book, and were kind enough to bring it to the Botany Library for me to pick up.  So here we go:

In the chapter about sea otters, there is no such reference to sea otters of the genus Enhydra.  There are  stomach contents of sea otters that include meat, but no beavers.  So there.  Sea otters do not eat beavers.

However, this came up in the chapter on River Otters (Lutra canadensis).

"In Maine, according to Manly Hardy, the Otters has a long list of foods...'When in a Beaver country, they often kill the young Beaver, and I feel quite sure that they also sometimes kill ducks'."  Lives of Game Animals, Volume II pg 680.

This same chapter, on page 693-4, has an account by Enos A. Mills of a beaver and otter fight when the otter invaded the territory of a beaver.

So if there is more data to back this claim up, then yes, River Otters eat Beaver.  Somewhere in the original text mining, the wrong species was used.

Hope that answers your question.

**Comment by diatomsRcool** [comment]
So this is really interesting and a good example of wrong or vague data 
perpetuating through the literature. I note that is says "kill" and not 
"kill and eat". That might make them competitors. Perhaps we could just 
say that Lutra canadensis interacts with Castor canadensis and reference 
that specific line. I wish I knew who Manly Hardy was.....
Is there a way we can add this information to the ADW text object that 
originally started this whole thing?
a

On 6/29/2015 11:03 AM, millerse wrote:
>
> @diatomsRcool <https://github.com/diatomsRcool> @jhpoelen 
> <https://github.com/jhpoelen>
> Alright here is the deal.
>
> The SI libraries have a copy of the book, and were kind enough to 
> bring it to the Botany Library for me to pick up. So here we go:
>
> In the chapter about sea otters, there is no such reference to sea 
> otters of the genus Enhydra. There are stomach contents of sea otters 
> that include meat, but no beavers. So there. Sea otters do not eat 
> beavers.
>
> However, this came up in the chapter on River Otters (Lutra canadensis).
>
> "In Maine, according to Manly Hardy, the Otters has a long list of 
> foods...'When in a Beaver country, they often kill the young Beaver, 
> and I feel quite sure that they also sometimes kill ducks'." Lives of 
> Game Animals, Volume II pg 680.
>
> This same chapter, on page 693-4, has an account by Enos A. Mills of a 
> beaver and otter fight when the otter invaded the territory of a beaver.
>
> So if there is more data to back this claim up, then yes, River Otters 
> eat Beaver. Somewhere in the original text mining, the wrong species 
> was used.
>
> Hope that answers your question.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jhpoelen/eol-globi-data/issues/142#issuecomment-116720413>.
>

-- 
Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by jhammock** [comment]
I'm afraid there's not much we can do with the ADW resource. Except possibly reconsider it altogether. A significant amount of unreliable information has been found there.

**Comment by jhpoelen** [comment]
hi @diatomsRcool @millerse @jhammock !

It took me a while to figure out how to parse your responses. So . . . here goes. 

**Seton 1929**
@millerse thanks for taking the time to peek into the Seton 1929. Would you like me to create a repository to include the one interaction that you extracted: river otter (_Lutra canadensis_) kills beaver (_Castor canadensis_)? This way we have at least one reference to the Seton 1929 publication.

**Kill interaction**
@diatomsRcool I agree that killing and eating are separate interactions. I've created a separate issue for this in #143 .

**annotating suspicious or dubious interaction**
I imagined that GloBI would take a somewhat neutral stance on what is a "correct" or "incorrect" interaction to limit the scope of the project. I was hoping that GloBI would spur data curators of contributing datasets to take actions (and they have in the past). However in case of static resources or disputed interactions (like the #118 ), I do see the need to filter out, exclude or flag disputed interactions, similar to how GBIF flags records with "spatial issues". I am hoping that the GloBI community can figure out a mechanisms to make this work. I've created a separate issue to continue this discussion in #144 .

**Comment by millerse** [comment]
@jhpoelen Sure.

**Comment by millerse** [comment]
@jhpoelen Sorry for the delay. I have created a repository for the data: https://github.com/millerse/Seton-1929

**Comment by jhpoelen** [comment]
Thanks @millerse for adding the reference! 

![screen shot 2016-01-27 at 9 41 21 am](https://cloud.githubusercontent.com/assets/1084872/12622432/2c757f94-c4da-11e5-8f04-ada5651db8d2.png)

**Comment by arw36** [comment]
FYI - It may be helpful to includ the volume you used of this source as I think there are 4 (or more?) different volumes. HathiTrust does have some digitized and accessible: 

1929 vols 1-4 https://catalog.hathitrust.org/Record/001496609 

There also appear to be some new editions (1937, 1953) but I guess for this purpose not important.

**Comment by jhpoelen** [comment]
hey @arw36 - thanks for sharing your note and reference. Hathi Trust looks pretty neat! 

As I don't have write access to https://github.com/millerse/seton-1929 , I forked the repository and made updates for your review at https://github.com/globalbioticinteractions/seton-1929 .
