### ISSUE TITLE
add interaction type to describe "killing"

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#143]
As discussed in #142 and suggested by @diatomsRcool .

Quote provided by @millerse 
```In Maine, according to Manly Hardy, the Otters has a long list of foods...'When in a Beaver country, they often kill the young Beaver, and I feel quite sure that they also sometimes kill ducks'." Lives of Game Animals, Volume II pg 680.```

The text does not describe that the otter eats young Beavers, but rather kills them. Killing is not a trophic interaction as there's no energy transfer between organisms. Suggest to introduce a new biotic interaction type that captures this specific interaction.

@cmungall As far as I can tell, that OBO Relations ontology does not currently have a term for this interaction. Could you please double check?

**Comment by cmungall** [comment]
It does not, I can add using the [interaction template](https://github.com/oborel/obo-relations/wiki/InteractionRelations). However, it would be good to get input from ecologists. Why do they kill? Honing hunting skills, rough play, they just hate ducks...?

Are you happy with defining this generally such that only one participant is necessarily biotic (e.g. guns kill)? 

note to self: need to add killing to nbo

**Comment by jhpoelen** [comment]
I'd be happy to have a semi-biotic interaction type. In case of the example provided by @millerse from Seton 1929, I believe that the beaver killing by otters resulted from territorial disputes.

**Comment by jhpoelen** [comment]
@jhammock Do you happen to know any ecologist that specializes in territorial disputes between river otters and beavers that could help with the definition of the "killing" interaction?

**Comment by jhammock** [comment]
Killing behavior will often be reported without any certainty about the "why". While it would be a good piece of metadata when available, (and an important plot element in detective novels!) we could use a killing term that is independent of the killer's motivation.

**Comment by jhpoelen** [comment]
@jhammock Perhaps the "why" can be captured in a more specific kind of interaction type when the data is available, perhaps something like a hierarchy would work - 

kill / kill to eat  (similar to preys on, trophic)
kill / kill to hone hunting skill (not trophic) 
kill / kill to protect or expand territorial dispute (also not trophic)
etc

**Comment by jhammock** [comment]
yes, that would work. I can tell you that in practice, when we bring in no interactions data, this is the point at which that kind of detail is rare enough that it's no longer worth making a new term for. That transition is partly because we don't have nice parent child search behavior for terms yet, but "we have found one record that might use this level of detail" is pretty far over the horizon.

**Comment by diatomsRcool** [comment]
Since this is somewhat in dispute, it might be better to use a generic 
"interacts with" interaction and then have a note about it.
There are several reasons one organism might kill another without 
eating, but I think the most common is a competition interaction, i.e. 
territorial dispute or some other resource-related threat. So maybe 
"competes with" would be the appropriate interaction?
a

On 7/6/2015 12:44 PM, Chris Mungall wrote:
>
> It does not, I can add using the interaction template 
> <https://github.com/oborel/obo-relations/wiki/InteractionRelations>. 
> However, it would be good to get input from ecologists. Why do they 
> kill? Honing hunting skills, rough play, they just hate ducks...?
>
> Are you happy with defining this generally such that only one 
> participant is necessarily biotic (e.g. guns kill)?
>
> note to self: need to add killing to nbo
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jhpoelen/eol-globi-data/issues/143#issuecomment-118921616>.
>

-- 
Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by jhpoelen** [comment]
Hey y'all,

I've added the kills/killed_by interaction. This interaction describes one organism killing another (killer,victim). The preysOn interaction is a related interaction, where an organism kills and then eats another organism.

I thought a little more about the competesWith idea and keep coming back to that a competitor is an organism that shares some kind of resource with another. There is no direct observable interaction. If we want to get fancy, we try to capture the reason behind the interaction: killing to cause the other to stop eating shared resource, or killing to practice hunting. Perhaps a nice challenge? (By the way, Malcolm Storey suggested something along these lines in a personal conversation I've had with him some weeks ago).

@cmungall @jhammock could you please add a term for kills, killed by in RO / EOL ? 

Closing issue, because the interaction kills/killedBy has been added

**Comment by jhammock** [comment]
created

http://eol.org/schema/terms/isKilledBy
http://eol.org/schema/terms/kills

in EOL for now. We can map to RO terms when the time comes...

**Comment by millerse** [comment]
@jhpoelen Sorry for the delay.  I have created a repository for the data: https://github.com/millerse/Seton-1929

**Comment by jhpoelen** [comment]
@jhammock Please note that this has been addressed by http://purl.obolibrary.org/obo/RO_0002626 and http://purl.obolibrary.org/obo/RO_0002627 . @cmungall @pbuttigieg thanks!
