### ISSUE TITLE
Visits flowers

### ISSUE THREAD

**Issue by millerse** [jhpoelen/eol-globi-data#146]
@jhpoelen I was wondering if you could add an interaction?  EOL has two terms that I have used in two of my datasets: http://eol.org/schema/terms/VisitsFlowersOf and http://eol.org/schema/terms/FlowersVisitedBy to describe an interaction where it is unclear if pollination was present.

**Comment by jhpoelen** [comment]
@millerse sounds like a good plan - hoping to add this next week when I am back in town. 

@cmungall would you consider this for RO? Perhaps this can be a general "visits" interaction combined with a uberon "flower" body part of involved Plantae.

**Comment by jhpoelen** [comment]
Hi sarah @millerse -

Just poked around a bit in the latest version of GloBI (including the visits flower of) and made a screenshot (see below). Whenever a "visits flower of" is selected, it also includes "pollinates" interactions. I am assuming the more explicit "pollinates" involve a flower being visited at some point. Please let me know if you'd like to discuss this further.

Thanks for all your contributions and let me know if you find any funny data related to the recent flower visit interaction - happy to help and fix.

-jorrit

from http://www.globalbioticinteractions.org/#sourceTaxon=Archilochus%20alexandri&interactionType=visitsFlowersOf : 
![screen shot 2015-07-31 at 10 08 34 am](https://cloud.githubusercontent.com/assets/1084872/9012751/26839d74-376c-11e5-8c28-1d405104e93e.png)
