### ISSUE TITLE
Baskerville, E.B. et al. (2011) Spatial guilds in the Serengeti food web revealed by a Bayesian group model. PLoS Comp. Biol. 7, e1002321

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#147]
After reading Morales-Castilla, I., Matias, M. G., Gravel, D., & Araújo, M. B. (2015). Inferring biotic interactions from proxies. Trends in Ecology & Evolution, 30(6), 347–356. http://dx.doi.org/10.1016/j.tree.2015.03.014 , I noticed that the following study might contain some valuable interaction data:

Baskerville, E.B. et al. (2011) Spatial guilds in the Serengeti food web revealed by a Bayesian group model. PLoS Comp. Biol. 7, e1002321

Note that I haven't read the Baskerville et al. 2011 yet, so this might be a long shot.

**Comment by millerse** [comment]
@jhpoelen I can get the information from Baskerville

**Comment by jhpoelen** [comment]
@millerse great! Curious to hear how it turns out . . .

**Comment by millerse** [comment]
@jhpoelen https://github.com/millerse/Serengeti

**Comment by jhpoelen** [comment]
@millerse wow! that was fast. I had a peek at the data and was wondering whether you could add the lat/lng of Serengeti park as reported by Geonames: http://www.geonames.org/150094/serengeti-national-park.html . I think this might folks that don't have access to geonames to have a machine-readable method to place the interaction at an approximate lat/lng.

**Comment by millerse** [comment]
@jhpoelen Taken care of.

**Comment by jhpoelen** [comment]
@millerse thanks!
