### ISSUE TITLE
Newsome et al. (2015) Foraging ecology of a reintroduced population of breeding Bald Eagles on the Channel Islands, California, USA, inferred from prey remains and stable isotope analysis.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#150]
Newsome SD, Collins PW, Sharpe P. Foraging ecology of a reintroduced population of breeding Bald Eagles on the Channel Islands, California, USA, inferred from prey remains and stable isotope analysis. The Condor [Internet]. Cooper Ornithological Society; 2015 Jul 22;117(3):396–413. Available from: http://dx.doi.org/10.1650/condor-14-213.1

**Comment by jhpoelen** [comment]
Also see https://github.com/hurlbertlab/dietdatabase/issues/21

**Comment by millerse** [comment]
@jhpoelen Done. https://github.com/millerse/Bald-Eagle-Diet/tree/master

**Comment by jhpoelen** [comment]
@millerse thanks for adding this so quickly. Will close once the data makes in into GloBI (might take a couple of days due to processing delays).

**Comment by jhpoelen** [comment]
@millerse data is now available through globi . . . see: http://www.globalbioticinteractions.org/#interactionType=eats&accordingTo=http%3A%2F%2Fdx.doi.org%2F10.1650%2FCONDOR-14-213.1

**Comment by jhpoelen** [comment]
@millerse thanks again!
