### ISSUE TITLE
Dalsgaard, B. et al. 2011. Specialization in plant–hummingbird networks is associated with species richness, contemporary precipitation and Quaternary climate-change velocity. – PLoS One 6: e25891.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#151]
as referenced in Kissling, W.D. & Schleuning, M., 2014. Multispecies interactions across trophic levels at macroscales: retrospective and future directions. Ecography, 38(4), pp.346–357. Available at: http://dx.doi.org/10.1111/ecog.00819. - 

Dalsgaard, B. et al., 2011. Specialization in Plant-Hummingbird Networks Is Associated with Species Richness, Contemporary Precipitation and Quaternary Climate-Change Velocity A. Traveset, ed. PLoS ONE, 6(10), p.e25891. Available at: http://dx.doi.org/10.1371/journal.pone.0025891.

**Comment by millerse** [comment]
So the paper itself does not have the raw data.  The data is in 25 different papers that are cited.  I am currently going through those sources and getting the information.  I will let you know when that is complete.

**Comment by millerse** [comment]
So I was able to gather a number of resources.  There are a few that I was not able to get, but I think we can call this data done.

**Comment by jhammock** [comment]
Hey, @millerse which repository is this?

**Comment by millerse** [comment]
@jhammock right here: https://github.com/millerse/Plant-Pollinator-Web

**Comment by jhammock** [comment]
Oooh, big file... Thanks; this looks great!
