### ISSUE TITLE
Morris, R. J. et al. 2014. Antagonistic interaction networks are structured independently of latitude and host guild. – Ecol. Lett. 17: 340–349.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#154]
as referenced in Kissling, W.D. & Schleuning, M., 2014. Multispecies interactions across trophic levels at macroscales: retrospective and future directions. Ecography, 38(4), pp.346–357. Available at: http://dx.doi.org/10.1111/ecog.00819. -

Trøjelsgaard, K. & Olesen, J.M., 2012. Macroecology of pollination networks B. Shipley, ed. Global Ecology and Biogeography, 22(2), pp.149–162. Available at: http://dx.doi.org/10.1111/j.1466-8238.2012.00777.x.

**Comment by millerse** [comment]
This was another paper that used the resources of other papers.  I got the information from as many papers as I could.  I would consider this one done.

**Comment by jhammock** [comment]
One more set of directions- which repository is this? Thanks!

**Comment by jhpoelen** [comment]
@millerse did you get a chance to point @jhammock to the relevant github repo? Please let me know if you need any help.

**Comment by millerse** [comment]
Yep.
