### ISSUE TITLE
California Current Predator Diet Database on GloBI

### ISSUE THREAD

**Issue by ambosz** [jhpoelen/eol-globi-data#158]
Dear Jorrit, 
We recently published a paper and the data from it on predator diet in the California Current (paper at Ecological Informatics, data at Dryad). We'd like to upload the species interaction dataset to GloBI, but I wanted to touch base with you first about the best possible way to do it. The database hosts diet data for 119 predator species compiled from 193 citations, circa 14K predator-prey links. The data are all geo-referenced with dates of collection, using ITIS for scientific names. If you have any recommendations before I get started, they would be much appreciated. Looking forward to getting the data out there. 
Thanks,
Amber

**Comment by jhpoelen** [comment]
Hi Amber,
Congratulations on your recent publication in _Ecological Informatics_  and thanks for pointing to it. The way you published the data in dryad in csv and shapesfile is very suitable for automated ingestion. This is why I suspecting that your data will be accessible through GloBI sooner rather than later.

I had a brief glance at the data available at http://datadryad.org/resource/doi:10.5061/dryad.nv5d2 and your format should make it relatively easy to automatically ingest the data into GloBI. I have a couple questions:

1. In ```CCPDDlinkdata.csv ``` I noticed that column ```CiteTitle ``` is truncated to 50 characters. For some titles, this seems to drop a chunk of the original title. For example, I assume that CiteTitle value on row 2  ```Feeding ecology of marine cormorants in Southweste``` refers to ```Feeding Ecology of Marine Cormorants in Southwestern North America```. Is there any way to provide an updated version of the csv file with the full citation titles? 

1. Would you happen to have a list of doi associated to your citations? If so, it would be great if you could also include this as a column. GloBI has ways to automatically match a citation to a doi if necessary, but a direct doi "link" would eliminate any ambiguity.

1. In the article, you mention that the taxonomic names are matches against ITIS. Is there a way to include the ITIS tsn for pred/prey in the csv file ? I think this would help make the taxonomic name resolution a little more straight forward and robust: with a single id the entire taxonomic path can be easily from imported from ITIS (or any other system that integrated with ITIS). 

Curious to hear your thoughts on this.

**Comment by ambosz** [comment]
Hi, Jorrit,
Thanks for getting back to me, we're excited to spread the word about this
dataset for predator prey interactions.

I've attached an updated .csv with fixes to CiteTitle, and ITIS data for
predator scientific name, prey group, and prey scientific name. Please note
the PreyGroupTSN is for the data that we published in Ecological
Informatics, which for some taxa are at a higher taxonomic level than
reported in the original citation. I also included the PreySciNameTSN,
which represents the prey data at the taxonomic level reported in the
citation. Do you have a sense of which would be better to use for GloBI?

I don't have the doi list for the citations, so if you have a way to
automate this, that would be the most efficient.

Also, just to be clear, I haven't updated the Dryad data yet.

Amber


On Tue, Aug 18, 2015 at 10:56 AM, Jorrit Poelen <notifications@github.com>
wrote:

> Hi Amber,
> Congratulations on your recent publication in *Ecological Informatics*
> and thanks for pointing to it. The way you published the data in dryad in
> csv and shapesfile is very suitable for automated ingestion. This is why I
> suspecting that your data will be accessible through GloBI sooner rather
> than later.
>
> I had a brief glance at the data available at
> http://datadryad.org/resource/doi:10.5061/dryad.nv5d2 and your format
> should make it relatively easy to automatically ingest the data into GloBI.
> I have a couple questions:
>
>    1.
>
>    In CCPDDlinkdata.csv I noticed that column CiteTitle is truncated to
>    50 characters. For some titles, this seems to drop a chunk of the original
>    title. For example, I assume that CiteTitle value on row 2 Feeding
>    ecology of marine cormorants in Southweste refers to Feeding Ecology
>    of Marine Cormorants in Southwestern North America. Is there any way
>    to provide an updated version of the csv file with the full citation
>    titles?
>    2.
>
>    Would you happen to have a list of doi associated to your citations?
>    If so, it would be great if you could also include this as a column. GloBI
>    has ways to automatically match a citation to a doi if necessary, but a
>    direct doi "link" would eliminate any ambiguity.
>    3.
>
>    In the article, you mention that the taxonomic names are matches
>    against ITIS. Is there a way to include the ITIS tsn for pred/prey in the
>    csv file ? I think this would help make the taxonomic name resolution a
>    little more straight forward and robust: with a single id the entire
>    taxonomic path can be easily from imported from ITIS (or any other system
>    that integrated with ITIS).
>
> Curious to hear your thoughts on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/eol-globi-data/issues/158#issuecomment-132296213>
> .
>



-- 
----------------------------
Farallon Institute
101 H Street, Suite Q
Petaluma CA 94954
707-981-8033

**Comment by jhpoelen** [comment]
Hi Amber:

Thanks for getting back to me so quickly and taking action on the comments that I shared with you. 

I'd prefer using published data from Dryad, and I do want to get your data out there sooner rather than later. When are you expecting the update the Dryad data? 

thx,
-jorrit

PS GitHub doesn't support attachments, so please send the csv file directly to my email address : jhpoelen at xs4all dot nl . Thanks!

**Comment by ambosz** [comment]
Hi, Jorrit,
I sent Dryad a help request a week ago but haven't heard back from them,
it's not clear how to submit revised data. I'm attaching the file here and
ccing your other account. I'll let you know when I hear from Dryad.
Best,
Amber

On Mon, Aug 24, 2015 at 11:44 AM, Jorrit Poelen <notifications@github.com>
wrote:

> Hi Amber:
>
> Thanks for getting back to me so quickly and taking action on the comments
> that I shared with you.
>
> I'd prefer using published data from Dryad, and I do want to get your data
> out there sooner rather than later. When are you expecting the update the
> Dryad data?
>
> thx,
> -jorrit
>
> PS GitHub doesn't support attachments, so please send the csv file
> directly to my email address : jhpoelen at xs4all dot nl . Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/eol-globi-data/issues/158#issuecomment-134334350>
> .
>



-- 
----------------------------
Farallon Institute
101 H Street, Suite Q
Petaluma CA 94954
707-981-8033

**Comment by jhpoelen** [comment]
Hi Amber:

Thanks for sharing the updated csv file by email. I received it in good order. 

I took a first stab at integrating your data. Here are my findings: ```preySciNameTSN``` column is now available and the ```CiteTitle``` are no longer truncated. 

In the readme for the GIS shapefiles, you mention that a column LocatNum is used to join the shapes with the pred-prey links. However, for some reason, I could not find the ```LocatNum``` in the links csv file. Without this column, it would be a bit tricky to extract spatial information in addition to the locale name.

Also, I was wondering whether you could add the ```PredatorSciNameTSN``` column, if it exists.

Hope this helps,
-jorrit

PS If you are sending more csv file, please send to my direct email address also.

**Comment by ambosz** [comment]
Hi, Jorrit,
Sorry about that, somehow the LocatNum field didn't get transferred to the
new version, and PredSciNameTSN was just left out, an oversight on my part.
This new file should have all the fields you are looking for. I've updated
the file but the name is the same so it is consistent with the files for
Dryad.

Let me know if you run into more problems, this is my first effort at this
level of data-sharing.

Apparently Dryad never received my initial message, but we are now in the
process of updating the data files on that end.

Thanks,
Amber

On Mon, Aug 31, 2015 at 3:42 PM, Jorrit Poelen <notifications@github.com>
wrote:

> Hi Amber:
>
> Thanks for sharing the updated csv file by email. I received it in good
> order.
>
> I took a first stab at integrating your data. Here are my findings:
> preySciNameTSN column is now available and the CiteTitle are no longer
> truncated.
>
> In the readme for the GIS shapefiles, you mention that a column LocatNum
> is used to join the shapes with the pred-prey links. However, for some
> reason, I could not find the LocatNum in the links csv file. Without this
> column, it would be a bit tricky to extract spatial information in addition
> to the locale name.
>
> Also, I was wondering whether you could add the PredatorSciNameTSN
> column, if it exists.
>
> Hope this helps,
> -jorrit
>
> PS If you are sending more csv file, please send to my direct email
> address also.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhpoelen/eol-globi-data/issues/158#issuecomment-136520004>
> .
>



-- 
----------------------------
Farallon Institute
101 H Street, Suite Q
Petaluma CA 94954
707-981-8033

CCPDD Version 2.0 September 2015

The California Current Predator Diet Database (CCPDD) package accompanies: Szoboszlai, A.I., J.A. Thayer, S.A. Wood, W.J. Sydeman, L.E. Koehn. 2015 Forage species in predator diets: Synthesis of data from the California Current. Ecological Informatics 29:45-56. DOI: http://dx.doi.org/10.1016/j.ecoinf.2015.07.003. The data package contains a copy of the main data file as used for this paper, as well as the GIS shape files. Additional data are available as appendices and supplements for the published paper, including summaries for citations included and known, data synthesis for each predator species, predators without known published diet data, lists of predator species for each forage category, geographic gap analysis for each predator species, and temporal gap analysis for each predator species. Current predator and prey taxonomy was synchronized with data from itis.gov. Please, contact me if you have suggestions, find errors, inconsistencies, or any other bugs in the file. IÕd like to know of your use of the data, and to receive any manuscripts that utilize it. IÕll be happy to help you, as I am able. We are continuing to update the database since its inception in 2012 and are interested to receive suggestions for new or missed data sources. 

Contents
1. readme.txt (this file)
2. CCPDDlocationdata_v1.zip
3. CCPDDlinkdata_v2.csv

2. CCPDDlocationdata_v1.zip
This file contains the GIS shape files for the location points and polygons for each study. The point files are based on the centroid point for each polygon. The LocatNum field in the shape files can be joined with data from the CCPDDlinkdata_v1.xls file below using the LocatNum field. The coordinate reference system (CRS) for the shape files is WGS 84. 
 
3. CCPDDlinkdata_v2.xls

Column headers are described below, each row in the file represents an individual predator-prey link. 

Note on redundancy. Some authors, for example those publishing long-term datasets have published diet data more than once, or different units for the same data (% # followed by % mass). When using this dataset, you will need to review location, date, and observation type for potential overlaps, and verify you arenÕt using redundant values by consulting the original publication. 

Column Headers: 
PredPreyNum. The unique identifier for a record. Each record is one predator-prey link that represents a predator eating a prey. 
PredatorClassName. We include both class and family level taxonomy because they are necessary to sort among the taxonomic groups. Class works to distinguish bony fishes, cartilaginous fishes, seabirds, mammals and the giant squid. Family is necessary to distinguish marine mammals from pinnipeds. 
PredatorFamilyName. We include both class and family level taxonomy because they are necessary to sort among the taxonomic groups. Class works to distinguish bony fishes, cartilaginous fishes, seabirds, mammals and the giant squid. Family is necessary to distinguish marine mammals from pinnipeds. 
PredatorSciName. Predator scientific name reflects the current taxonomy and has been updated from the original published taxonomy if it was outdated. Current taxonomy is based on the itis.gov standardized taxonomic database. 
PredatorSciNameTSN. The taxonomic code associated with the predator scientific name, linked to the database at the integrated taxonomic information system (itis.gov). 
PredatorCommName. Predator common name based on itis.gov. 
PreyGroup. The complete CCPDD database includes all prey taxa reported in a citation. For this version and the accompanying paper, we focused on a subset of 32 forage taxa (see Table 2 in the accompanying manuscript) that we extracted from the larger database. These forage taxa are represented in the field Òprey groupÓ. In some cases a prey group was at the species level, so it has the same value as PreySciName (e.g., Sardinops sagax). In other cases, prey were not always reported at the same taxonomic level (e.g., Pleuronectidae vs. Lyopsetta exilis) so we had to distinguish between our prey group of interest and the taxonomic level that was reported in the paper. 
PreyGroupTSN. The taxonomic code associated with the prey group name, linked to the database at the integrated taxonomic information system (itis.gov). 
PreySciName. The prey scientific name as it was reported in the original citation, although taxonomy has been updated to the current name from itis.gov. Because of difficulty distinguishing some prey at the species level, many prey were reported at higher than the species level, e.g., Sebastes. Although we did not analyze the data based on PreySciName, it can be helpful to know the name as originally reported in the citation, as opposed to the Prey Group Name we used for our analyses. 
PreySciNameTSN. The taxonomic code associated with the prey scientific name, linked to the database at the integrated taxonomic information system (itis.gov). 
CiteAuth. The citation author names. 
CiteYear. Citation year. 	
CiteTitle. Citation title. 
CiteSource. Citation source name (book, journal, report, thesis). 
CiteVolume. Citation volume. 
CitePages. Citation page numbers. 
LocatName. The location name for each record. Format is: Country, State/Province, specific location as reported in original citation
LocatNum. The unique identifying number for each location in the database. This number is used for linking with the GIS shape file via the field LocatNum. 
LocatSpan. Use this field to identify locations based on the 7 geographic regions in the paper (Canada, Washington, Oregon, California-northern, California-central, California-southern, Mexico). When a study spanned more than one region, this field includes the word ÔspanÕ preceding the regions that it spanned. 
DateName. Study date as reported in the original citation. Format is YYYY/MM/DD-YYYY/MM/DD, where the Ô-Ô indicates duration of the study. In some cases, date was not reported, this is indicated by a Ô<Õ followed by the year of the publication to approximate the era the data came from. 
ObsTypeName. The type of observation that was recorded, includes bill load, burrow load, chemical analysis, dip net, dropped prey, GI tract, pellet, regurgitation, scat, stomach content, tow net, visual observation. 
AdjustedSampleSize. The adjusted sample size is the original sample size with empty samples excluded, when data were provided. In some cases, authors did not report sample size so this field is blank. 
AnnualSeasonal. Annual=1, Seasonal: 2=summer april-sept, 3=winter oct-may, 4=mixed summer and winter months	
Units#. Study has prey data recorded as number of prey items. 
Units%#. Study has prey data recorded as percent number of prey items. 
UnitsFO. Study has prey data recorded as frequency of occurrence of prey items. 
Units%FO. Study has prey data recorded as percent frequency of occurrence of prey items. 	
UnitsMassVol. Study has prey data recorded as mass or volume of prey items. 
Units%MassVol. Study has prey data recorded as percent mass or percent volume of prey items. 
UnitsIndex. Study has prey data recorded as an index (e.g., index of relative importance, IRI) of prey items. 
Units%Index. Study has prey data recorded as a percent index (e.g., percent index of relative importance, %IRI) of prey items. 

Contact:  Amber Szoboszlai, Farallon Institute for Advanced Ecosystem Research, 101 H Street, Petaluma, CA 94954. Phone: 707-981-8033. E-mail ambo@faralloninstitute.org. 

Acknowledgements
This database developed from a collaboration to support fisheries ecosystem based management, it includes data from over 190 publications and reflects the work of countless researchers (see Appendix A in the associated paper for a complete list of authors). Database design was managed by Spencer Wood, additional data entry by Sarah Ann Thompson and Laura Koehn, with general guidance and oversight from Julie Thayer, Bill Sydeman and Tim Essington. Financial support for this project was provided by The Pew Charitable Trusts and the National Fish and Wildlife Foundation. 

History
Version 1.0; 31 July 2015; 119 predator species, 193 citations

**Comment by jhpoelen** [comment]
Hey Amber:

Thanks for being thorough . . . the meta data associated with your dataset can be found here:
https://github.com/globalbioticinteractions/szoboszlai2015/blob/master/globi.json 

Once the v2 of the links file is available, please update globi.json accordingly in browser and create pull request or drop me a line if that doesn't work for you. 

Your dataset should be available through GloBI within a few days or so (using the old link file until we update it in globi.json). 

-jorrit

**Comment by jhpoelen** [comment]
Your data is now available through GloBI and associated tools. See comments above on ideas for upgrading to the v2 version of the ilnk data.

Thanks for sharing your data and let me know if you find any suspicious data. . . 

from http://www.globalbioticinteractions.org/#interactionType=interactsWith&accordingTo=Szoboszlai I saw:

![screen shot 2015-09-08 at 4 31 59 pm](https://cloud.githubusercontent.com/assets/1084872/9749994/3c9a3dbc-5647-11e5-9660-b9ccbbc778fd.png)
