### ISSUE TITLE
Chen et al, seed dispersal- also includes some fruit traits

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#160]
Hello! I put this dataset in EOL's DwC-A excel template. Three things to note:

a new (stand-in) association term, already in EOL system: http://eol.org/schema/terms/IsDispersalVectorFor
(there's a vector term in RO but judging by the definition source, it is meant only for pathogens)

There are some child measurements of the association records, for metadata, in the measurementOrFact tab. Is that alright? (Eats what body part? Disperses what propagule?)

There are also some independent non-associations traits in the measurementOrFact tab- properties of the seeds and fruit. I think GloBI has incidentally included traits like this before in resources, and sent them to EOL in the DwC-A export. Is it convenient to leave them in and handle them that way? If not I can take them out and load them to EOL separately.

Thanks!

https://dl.dropboxusercontent.com/u/33761226/animal%20seed%20size.xlsx

**Comment by jhammock** [comment]
@jhpoelen Just getting back to revising this resource, I cannot find the discussion where you pointed me to a resource I could look at as an example. Recall: I had some non-standard metadata to attach to the association records, so I made child records in the measurementOrFact file, referencing the relevant association records. This is not the preferred way. 

(This is what comes of keeping my correspondence in so many different media...)

**Comment by jhpoelen** [comment]
@jhammock I believe that example I pointed to was the Tri-Trophic Thematic Collection Network archive generated by @seltmann et al. (see https://github.com/globalbioticinteractions/tri-trophic-thematic-collection-network/blob/master/globi.json link and #133 for context).

Does that answer your question?

**Comment by jhammock** [comment]
Hmm... now that I have the exemplar resource in hand, it's harder to interpret than I expected. It looks like an occurrences file and a taxa file to me. Is one partner in the first and another in the second? If so, which column links the two together? All the good candidate elements seem to be frequently empty, so I ruled them out. I'm happy to imitate this format, but so far I don't understand it.

**Comment by jhpoelen** [comment]
The associated dropbox link is no longer public / accessible. Closing issue.
