### ISSUE TITLE
Change label for flower visitor interactions

### ISSUE THREAD

**Issue by KatjaSchulz** [jhpoelen/eol-globi-data#166]
Flower visitor interactions have funky labels in the interactions menu of the browser: http://www.globalbioticinteractions.org/browse/index.html 

It should be "flowers visited by" instead of "is flowers visited by" and "visits flowers of" instead of "is visits flowers of"

**Comment by jhpoelen** [comment]
Thanks for your observations. 

Göran @coding46 - do you have an idea to address this?

**Comment by coding46** [comment]
Four ideas:

1) As those labels are built by exploding the camelcased interaction type strings (+ some magic for suffices 'of' and 'by') from response we could solve it by renaming them in the web service (see https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/blob/master/node_modules/globi-search/index.js#L315)

2) Remove the special suffix handling for "of" and "by" from 1) in our application

3) Add a label field to the service response which holds an human-readable name of the interaction type. So we don't have to built it programmatically.

4) We could map interaction type names in frontend to fit user's purpose. This would lead to changes whenever new interaction types are added to the database.


I prefer 2)

**Comment by jhpoelen** [comment]
@coding46 (apologies for a late reply) if I add the 3) label , would you be able to easily apply the change to use that label?

**Comment by cmungall** [comment]
I can add these to RO, and add explicit inverses. The rdfs:label from either would be used

**Comment by jhpoelen** [comment]
nice! this way, GloBI doesn't have to keep (duplicates) labels around. Let me know when RO changes are applied, so we can start using the labels.
