### ISSUE TITLE
Default query for GloBI browser

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#167]
Since there must be a tractable subset of GloBI records displayed by default when you arrive in the browser (i.e., we can't show all GloBI records), how about showing an explicit example of a reasonable size, with fun records, like this, as default:
http://www.globalbioticinteractions.org/browse/#interactionType=interactsWith&resultType=json&sourceTaxon=Chelonia%20mydas

And show the query selection also, in addition to the results, so people know what they're looking at? This may just mean redirecting http://www.globalbioticinteractions.org/browse/ to this example url. If that's the easy way, it works for me...

**Comment by jhpoelen** [comment]
Thanks for your suggestion! Just added this default to the GloBI browser. Please re-open if the behavior is not as desired.
