### ISSUE TITLE
update interaction type mapping for darwin core archive

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#172]
in #165 @jhammock shared the following observation:

---
Hmm... The records in question were added a couple of months ago and are available in the browser, eg: http://www.globalbioticinteractions.org/browse/index.html#interactionType=visitsFlowersOf&resultType=json

I think I've found them in the DarwinCore Archive (from the source, Sarah E Miller. 6/25/2015. Species associations manually extracted from Robertson, C. 1929. Flowers and insects: lists of visitors to four hundred and fifty-three flowers. Carlinville, IL, USA). In the browser their interaction type is visits flowers of. In the DarwinCore it's interacts with.

Were you waiting on the EOL terms, Jorrit? We have these now:
http://eol.org/schema/terms/VisitsFlowersOf
http://eol.org/schema/terms/FlowersVisitedBy

**Comment by jhpoelen** [comment]
@jhammock question before updating the interaction type mapping:

Does the EOL ingestion process support the RO interaction types like:
http://purl.obolibrary.org/obo/RO_0002439 (preysUpon)
http://purl.obolibrary.org/obo/RO_0002444 (parasiteOf)
http://purl.obolibrary.org/obo/RO_0002454 (hasHost)

I am hoping that we can use the RO terms if they are available. Otherwise, EOL terms can be used to fill-in the missing terms.

Curious to hear your thoughts.

**Comment by jhammock** [comment]
Hmm... We've made EOL terms for all of those; frankly, I'm ready to overwrite all the EOL terms with RO terms if they're ready, though. So next time we harvest GloBI, let's plan on that. In the meantime, Jorrit, if you want to go ahead and adopt the RO terms in the EOL export, could you send me a list of all the RO terms you're using? And any EOL terms you're using where RO terms still aren't available, if there are any cases like that. I'll make sure they all get in when next we are able to harvest GloBI.

**Comment by jhammock** [comment]
(eg: if RO does not have the flower visiting terms, we can use the EOL terms)

**Comment by jhpoelen** [comment]
Now, the darwin core archive includes RO first. If RO terms are not available, eol terms are used. If none are available, the default interaction "interactWith" is used. Closing issue.

PS If you have the time please review terms (and their IRIs) that can be found through:

 https://github.com/jhpoelen/eol-globi-data/wiki/Ontologies-and-Vocabularies  --> https://github.com/jhpoelen/eol-globi-data/blob/master/eol-globi-lib/src/main/java/org/eol/globi/domain/InteractType.java

interaction types without an IRI are mapped to generic "interactsWith".

Kindly make sure that EOL know how to deal with RO terms and let me know whether there's any IRIs that need updating.

**Comment by jhammock** [comment]
Sweet, will check that list and try to cover all unmatched terms on EOL upon next harvest. Not going to rush, though, in case RO decides to claim some of them in the meantime.
