### ISSUE TITLE
Dismantle taxonomic roll-up

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#174]
Reminded by https://github.com/jhpoelen/eol-globi-data/issues/173, and following up on discussions at GloBI feedback session a couple of weeks ago with @KatjaSchulz and company, we are ready to end the taxonomic rollup experiment. The "seal food" style collections will address the needs of casual users in search of this kind of higher taxon level data; serious searchers are best served in the GloBI browser; and the roll up created to many confusing (if perfectly true) statements, eg: African apes eat Polar bears. It was good to try, and now we know.

**Comment by jhpoelen** [comment]
Removed the roll-up and updated the resource url in eol.
