### ISSUE TITLE
eol page search for "Brown" returns an (incorrect) exact match for Brown Wood Owl (Strix leptogrammica)

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#175]
Steps to reproduce:

retrieve result from:
http://eol.org:80/api/search/1.0.xml?q=Brown&exact=true

expected result:
no exact matches

actual result:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:os="http://a9.com/-/spec/opensearch/1.1/">
  <title>Encyclopedia of Life search: </title>
  <link href="http://eol.org/api/search/1.0/Brown"/>
  <updated/>
  <author>
    <name>Encyclopedia of Life</name>
  </author>
  <id>http://eol.org/api/search/1.0/Brown</id>
  <os:totalResults>1</os:totalResults>
  <os:startIndex>1</os:startIndex>
  <os:itemsPerPage>30</os:itemsPerPage>
  <os:Query role="request" searchTerms="" startPage=""/>
  <link rel="alternate" href="http://eol.org/api/search/1.0/Brown/" type="application/atom+xml"/>
  <link rel="first" href="http://eol.org/api/search/Brown.xml?page=1" type="application/atom+xml"/>
  <link rel="self" href="http://eol.org/api/search/Brown.xml?page=1" type="application/atom+xml"/>
  <link rel="last" href="http://eol.org/api/search/Brown.xml?page=1" type="application/atom+xml"/>
  <link rel="search" href="http://eol.orghttp://160.111.248.28/opensearchdescription.xml" type="application/opensearchdescription+xml"/>
  <entry>
    <title>Strix leptogrammica Temminck, 1832</title>
    <link href="http://eol.org/1178287?action=overview&amp;controller=taxa"/>
    <id>1178287</id>
    <updated/>
    <content>Brown</content>
  </entry>
</feed>
```

A similar search using eol.org returns a big list of items containing "brown" in the name (see screenshot).

![screen shot 2015-09-14 at 7 40 01 pm](https://cloud.githubusercontent.com/assets/1084872/9866544/710ebaca-5b18-11e5-9242-3281b81e9d5e.png)

@jhammock can you help me understand why the eol api is coming up with this result?

**Comment by jhammock** [comment]
Odd... I can only replicate this on this taxon concept; other pages that I've tried don't have similar behavior. It is behaving as though the only English common name for this taxon is "Brown". What it returns between the <content> tags, as I understand it, is all values present in the section where the string match was made- scientific names or any one language in the common names. The french name for this taxon concept also works, but neither of the English common names displaying in the common names subtab (Brown Wood Owl, Brown Wood-owl) are recognized. I tried re-indexing the page. I'm not sure if that reaches into the database; if it does, this may take a few hours to have any effect...

**Comment by jhpoelen** [comment]
@jhammock just repeated http://eol.org:80/api/search/1.0.xml?q=Brown&exact=true and same (unexpected) result is present: Brown Wood Owl (Strix leptogrammica).

**Comment by jhpoelen** [comment]
Also, found that "blue" resolves to "Blue Wildebeest (_Connochaetes taurinus_). It seems that exact matches are more like exact _prefix_ matches. 

So, because of this GloBI says that Yellowfin Tuna (_Thunnus albacares_) eat Blue Wildebeest (_Connochaetes taurinus_). Weird isn't it?

![screen shot 2015-10-07 at 7 42 51 pm](https://cloud.githubusercontent.com/assets/1084872/10356434/1f31c550-6d2c-11e5-86da-4b1450d780af.png)

**Comment by jhammock** [comment]
Jeremy is now digging into the names mapping code and we're starting to learn how this worked. There have been a couple of surprises already, which fit this general pattern.

**Comment by jhpoelen** [comment]
@jhammock Thanks for following up and good to hear that Jeremy is looking at this. . . . curious what the outcomes will be.

**Comment by jhpoelen** [comment]
Issue seems to no longer occur. Thanks for fixing this!

```curl "http://eol.org:80/api/search/1.0.xml?q=Brown&exact=true"``` now returns

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:os="http://a9.com/-/spec/opensearch/1.1/">
  <title>Encyclopedia of Life search: </title>
  <link href="http://eol.org/api/search/1.0/Brown"/>
  <updated/>
  <author>
    <name>Encyclopedia of Life</name>
  </author>
  <id>http://eol.org/api/search/1.0/Brown</id>
  <os:totalResults>0</os:totalResults>
  <os:startIndex>1</os:startIndex>
  <os:itemsPerPage>30</os:itemsPerPage>
  <os:Query role="request" searchTerms="" startPage=""/>
  <link rel="alternate" href="http://eol.org/api/search/1.0/Brown/" type="application/atom+xml"/>
  <link rel="search" href="http://eol.orghttp://media.eol.org//opensearchdescription.xml" type="application/opensearchdescription+xml"/>
</feed>
```
