### ISSUE TITLE
Wardeh et al. 2015 - Database of host-pathogen and related species interactions, and their global distribution

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#176]
@rdmpage suggested to add Wardeh, M. et al., 2015. Database of host-pathogen and related species interactions, and their global distribution. Sci. Data, 2, p.150049. Available at: http://dx.doi.org/10.1038/sdata.2015.49.

This dataset took a similar approach suggested in #18 some time ago - mining GenBank for interaction data.

**Comment by millerse** [comment]
@jhpoelen Taking care of this[one](https://github.com/millerse/Wardeh-et-al.-2015).  Also, Katja was wondering if there was a way to add a PMIDs list to the resource.

**Comment by jhpoelen** [comment]
Great! At first glance, I'd say that the Wardeh et al. 2015 can be moved to the source reference and the PMIDs can move to the referenceURLs with one line per reference: each reference reported an interaction and can be recorded as such. 

For example:

```
EOL:1001047     brucella ovis   RO:0002454      has host        EOL:328660      capra hircus     http://www.ncbi.nlm.nih.gov/pubmed/9144364; http://www.ncbi.nlm.nih.gov/pubmed/4624210; http://www.ncbi.nlm.nih.gov/pubmed/4062738 
```

would turn into:
```
EOL:1001047     brucella ovis   RO:0002454      has host        EOL:328660      capra hircus    http://www.ncbi.nlm.nih.gov/pubmed/9144364
EOL:1001047     brucella ovis   RO:0002454      has host        EOL:328660      capra hircus    http://www.ncbi.nlm.nih.gov/pubmed/4624210
EOL:1001047     brucella ovis   RO:0002454      has host        EOL:328660      capra hircus    http://www.ncbi.nlm.nih.gov/pubmed/4062738 
```

Also, I'd suggest to use the more specific interaction term "hasPathogen" (http://purl.obolibrary.org/obo/RO_0002556) instead of "hasHost" (http://purl.obolibrary.org/obo/RO_0002454). 

Lastly, suggest to rename ```globi.ston``` to ```globi.json```

Hope this helps, and curious to hear if you have any other suggestions on how to approach this.

**Comment by jhpoelen** [comment]
PS I could probably help write a little tool that fetches a human readable reference citation for a PMID (referenceUrl) if this is too much trouble.

**Comment by millerse** [comment]
Wonderful!  Will get on the fixes.  As for the PMID code, if you have the time, you can but this is the first time that I have run into one of these instances.  @KatjaSchulz what do you think?

**Comment by millerse** [comment]
Oh and @KatjaSchulz suggested the has host rather than has pathogen because the paper says the interactions can be classified as pathogenic or parasitic.  So her solution was to go more general.

**Comment by jhpoelen** [comment]
Thanks for clarifying. Also, one more thing: if you could add the locale for the interactions, GloBI might be able to cross reference to lat/lng using geonames.org .

**Comment by millerse** [comment]
Sorry to say, but there is no locality data.

**Comment by jhpoelen** [comment]
Interesting . . . I did see countries/regions mentioned in the data tables (see attached screenshot) . I consider these localities. Please let me know if I missed something.

![screen shot 2016-04-27 at 9 52 43 am](https://cloud.githubusercontent.com/assets/1084872/14860491/ee37afce-0c5d-11e6-829f-07b8b9e3c92b.png)

**Comment by millerse** [comment]
I saw that sheet and I have a big problem with it.  The paper indicates, at least from my understanding, that the location and species tables were created for two separate purposes.  The species list was made just to show interactions and the location sheet was made to "indicate the possibility of a species being found in a certain location".  The localities are just a list of where these species occur and the publications where the researchers found the information.

Worse, there seems to be no way for me to match the localities to the interactions.  There are no identifiers or even a common publication that i can link to.

That is why I passed on the localities.

**Comment by jhpoelen** [comment]
Ok, makes sense. Thanks again for clarifying and being patient with me.

**Comment by millerse** [comment]
Oh no problem.  You were doing your good diligence and I appreciate that.

**Comment by millerse** [comment]
Also, is there a way that the data set can have a link to nuccore in the same way we have a pubmed link in the resource?

**Comment by KatjaSchulz** [comment]
To clarify, the dataset does not only cover parasitic and pathogenic relationships but also has some mutualistic and neutral (commensal) relationships, and there's no way to tell which ones those are.  I think "hasHost" is most appropriate because "host" is actually the term they used for their textmining.

In addition to the references from the "publication" column, we should also add the references to the GenBank sequence metadata records, e.g., http://www.ncbi.nlm.nih.gov/nuccore/133722056

Many but not all of these records will also have location information, usually in the "country" subtype of the "source" element. The record above for nucleotide #133722056 has /country="Greece"  @jhpoelen  if you think it's worth your trouble, you should be able to fetch this information automagically.

**Comment by jhpoelen** [comment]
Is it correct that this reference to the gene sequence related to either the host or the hosted organism? In that case, I would recommend to add something like sourceGeneSequence/targetGeneSequence (@katjaschulz - I realize that source/target names are not your favorite  . . .), 'cause it related to the occurrences, not the interaction between them.

About adding the information: please add as much information as possible, ideally is separate clearly defined column: it is easy for GloBI to ignore now, and add later . . . but the revisiting the transcription of the source is much harder given the transformation process is not fully automated.

@millerse  @KatjaSchulz  I leave the final decision up to you.

**Comment by millerse** [comment]
@jhpoelen I am fine with adding the gene sequences to the same column as the pudmeds.  @KatjaSchulz any objections?

**Comment by cmungall** [comment]
I don't think you are particularly interested in the sequence area you? In the example above the gene is not relevant to the interaction AFAICT.

Here it's the sequence record you want to record (this could be done in a generic `source` field).

**Comment by KatjaSchulz** [comment]
@jhpoelen It looks like all the sequences are for the parasites/pathogens/mutualists/commensals being hosted. But @cmungall is right. We are not interested in the sequences themselves, and a generic source field (http://purl.org/dc/terms/source) would work for the metadata references.   

When people sequence a parasite/pathogen/mutualist/commensal they often report the host in the metadata. So Wardeh et al. use the sequence metadata records as a source of host records.  This gives them some host relationships that have not or only rarely been recorded in the literature.  Of course, this kind of evidence is weaker than an explicit assertion about a host relationship in a scientific paper, backed up by additional evidence about the relationship.  Therefore, it's important to document the source of each of the assertions.

**Comment by jhpoelen** [comment]
Thanks for chiming in and clarifying. Sounds like we have consensus.

**Comment by millerse** [comment]
All done!  Enjoy the 270,000+ new records

**Comment by jhpoelen** [comment]
Nice! I had a peek and it looks pretty good (see attached). Did you do spot checks of the data through http://globalbioticinteractions.org ? This is what I usually do to validate assumptions and links to external systems.

Suggest to rename "referenceURL" to "referenceUrl" . Also, I noticed that dois have an extra space in between the "doi:" and ids (e.g. ```doi: 10.1038/sdata.2015.49```). Suggest to remove the space to make it a little more consistent with how others write down dois.

![screen shot 2016-05-03 at 9 48 57 am](https://cloud.githubusercontent.com/assets/1084872/14991030/59f8526c-1114-11e6-9590-f17088b892a0.png)

**Comment by millerse** [comment]
Thanks.  Taken care of the header and doi.

**Comment by jhpoelen** [comment]
@millerse thanks for making the changes! The reference urls are now being populated (see attached).

Please re-open / comment if you have concerns / issues. 

![screen shot 2016-05-05 at 10 41 36 am](https://cloud.githubusercontent.com/assets/1084872/15051554/1234e33c-12ae-11e6-8f3a-e59abeefbd3a.png)

**Comment by jhpoelen** [comment]
PS I captured the idea resolve pubmed / genbank ids to bibliographic citations here in #223 .
