### ISSUE TITLE
integrate with DAPSTOM (integrated database and portal for fish stomach records) is an ongoing initiative (supported by Defra and the EU) to digitise and make available fish stomach content records spanning the past 100 years.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#178]
DAPSTOM (integrated database and portal for fish stomach records) is an ongoing initiative (supported by Defra and the EU) to digitise and make available fish stomach content records spanning the past 100 years.

https://www.cefas.co.uk/publications-data/fish-stomach-records/

**Comment by millerse** [comment]
I can grab this set if that is fine.

**Comment by jhpoelen** [comment]
That would be pretty cool! Do you think there's a way to get the dapstrom data in their native format before transforming it into the tabular files that you've created in the past? Do you think that this dataset will change over time?

**Comment by millerse** [comment]
I think so.  I do have the raw data here: https://www.dropbox.com/sh/lrwz7bgmj766cl7/AAAJ_TNjo4CnlMKHBymY44b0a?dl=0

As for changing over time, I think it might in terms of adding years of data.  If you want, I can keep an eye on it.

**Comment by jhpoelen** [comment]
Nice! I poke around a little and found that we might be able to automate downloading the csv files using some url patterns and lists of species codes. 

For instance, European mackerel (_Scomber scomberus_) data can be retrieved by using code ```MAC```. with a list of all ICES areas ```V1a, VIIIb``` . . . and years ```2011, 2010, ...``` and resulting in a url pointing to the csv - 

https://www.cefas.co.uk/umbraco/CefasPlugins/DapstomSurface/Download?searchType=predator&species=MAC&years=2011&years=2010&years=2006&years=2005&years=2004&years=1991&years=1987&years=1986&years=1979&years=1978&years=1977&years=1976&years=1974&years=1972&years=1965&years=1956&years=1919&years=1917&years=1907&years=1906&years=1902&years=1901&years=1899&areas=VIIIb&areas=Va&areas=VIa&areas=VIIj&areas=XIVa&areas=VIIId&areas=VIIIc&areas=XIVb&areas=IIa&areas=VIIg&areas=VIIh&areas=IVc&areas=VIIIa&areas=VIIe&areas=VIIf&areas=IVa&areas=IVb&areas=VIIa&minlength=0&maxlength=1000&nullLengths=true

After chopping off the headers and concatenating the file, you should be able to recreate the whole dapstrom dataset. Also, I can show you how to point GloBI to non-standard columns and pick up the predator/prey. Perhaps time for a little mini-workshop by skype? 

Reason why I am a big fan of automation is because it is easier to fix mistakes (I always make a mistake or two) and add new data (looks like Dapstrom is an active project). 

Curious to hear your thoughts.

**Comment by millerse** [comment]
Sure.  Let's set up a time for next week if that is alright?

**Comment by jhpoelen** [comment]
Sounds good, please send me a doodle by email.

**Comment by millerse** [comment]
How about Thursday?  Any time is works for me.

**Comment by jhpoelen** [comment]
@millerse Thanks for adding the DAPSTOM dataset. Included a sample record that includes DAPSTOM records using the meta-table method we discussed (see https://github.com/millerse/dapstrom-test and https://www.w3.org/TR/tabular-data-model/). I hope that this method of describing a schema and pointing to an existing tabular data file will help to integrate existing datasets more easily. Let me know if you have any suggestions on how to improve it.
 
![screen shot 2016-06-09 at 7 56 37 am](https://cloud.githubusercontent.com/assets/1084872/15934261/cbc09e20-2e17-11e6-8376-6d1a5df3d8cf.png)
