### ISSUE TITLE
Ecological associations from datamining GenBank

### ISSUE THREAD

**Issue by rdmpage** [jhpoelen/eol-globi-data#18]
The basic idea is that GenBank is a large repository of information beyond simply DNA sequences. Individual sequences may contain information on host-parasite relationships (see http://ispecies.blogspot.co.uk/2006/03/building-encyclopedia-of-life.html ) or dietary information (e.g., sequences from gut contents ). I explored some of this data in http://iphylo.blogspot.co.uk/2011/03/visualising-symbiome-hosts-parasites.html .

An advantage of GenBank data is that there is a clear digital identifier for the observation (the accession number of the sequence), and this is linked to a NCBI tax_id for one member of the association (the organism being sequenced). The sequence is usually (but not always) linked to one or more publications, typically with identifiers such as DOIs and PMIDs. Many recent sequences (especially DNA barcode are also georeferenced), and some will have collection date. Hence in the best case scenario we have observations located in space and time, tied to a taxon and the primary literature.

The challenge is to mine this data. The "host" field is free-form, so people populate it with all sorts of strings, ranging from scientific names to common names, patient codes, etc. The nature of the ecological relationship can be tricky to infer as well. However, it's a potential gold mine.

I'm working with a local copy of Genbank sequence metadata for animals as par tof another project (http://bionames.org), and am interested in cleaning and mining this and extracting ecological associations. It's not clear to me what sort of data format Globi wants, and what level of detail you're after. Suggestions welcome.

**Comment by jhpoelen** [comment]
@rdmpage Wardeh et al. 2015 #176 has mined genbank for associated and published results. While the method is a one-time procedure and not a continuous process, I think that it covers the idea you suggested sufficient. This is why I am closing this issue. Please feel free to re-open / comment if you have ideas/comment about this topic. Thanks for your patience.
