### ISSUE TITLE
Kissling, W.D. et al., 2014. Establishing macroecological trait datasets: digitalization, extrapolation, and validation of diet preferences in terrestrial mammals worldwide. Ecology and Evolution, 4(14), pp.2913–2930. Available at: http://dx.doi.org/10.1002/ece3.1136.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#183]
@BrianHayden suggested to make:

Kissling, W.D. et al., 2014. Establishing macroecological trait datasets: digitalization, extrapolation, and validation of diet preferences in terrestrial mammals worldwide. Ecology and Evolution, 4(14), pp.2913–2930. Available at: http://dx.doi.org/10.1002/ece3.1136.

accessible through GloBI.

**Comment by KatjaSchulz** [comment]
Looks like most of these are general diet data, not biotic interaction data where we have taxonomic data for both players.  We've already talked about the potential of inferring diet from interaction data.  It may make sense for GloBi to expand its scope to also manage such diet data.  This would probably be a good topic for our discussions during your DC visit.

**Comment by millerse** [comment]
Way too general of a dataset.
