### ISSUE TITLE
add Africa Tree Database

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#184]
Thanks to @carrieseltzer et al. the data associated with the http://africatreedatabase.org is now available in a machine readable format. Contains over 9k species interactions focused on trees and their consumers/ seed dispersers. 

------
Dear colleagues,

It has been about 3 years since we launched the Africa Tree Database and about that long now since most of us corresponded about it! Over the last few months, I've worked to get the data we painstakingly entered into a more findable, shareable, and citable format. Thank you to Bill for helping with this process.

Here are permanent links to each of the datasets on figshare:
·      Plant-animal interactions from Africa. http://dx.doi.org/10.6084/m9.figshare.1526128
·      Common names of African trees. http://dx.doi.org/10.6084/m9.figshare.1526129
·      SQL of Africa Tree Database. http://dx.doi.org/10.6084/m9.figshare.1526125
·      Seed characteristics of African trees. http://dx.doi.org/10.6084/m9.figshare.1526135
·      Fruit characteristics of African trees. http://dx.doi.org/10.6084/m9.figshare.1526131
·      Growth form (habit) of African trees. http://dx.doi.org/10.6084/m9.figshare.1526132
·      Medicinal uses of African plants. http://dx.doi.org/10.6084/m9.figshare.1526133
·      Non-medicinal uses of African trees. http://dx.doi.org/10.6084/m9.figshare.1526136

The main motivation behind this has been to make the 9000 records of interactions available for incorporation into the Global Biotic Interactions (GloBI) project (see some fabulous visualizations on their blog). I've copied Jorrit Poelen (GloBI) and Jen Hammock (EOL) so that they can incorporate the additional data directly from figshare. 

I am unsure how to contact Jamie, Aaron, and Jordan. Could you pass this along to them if you know how to get in touch?

Thank you all for your part in this project to disseminate knowledge about African trees. Please let me know if you have any questions. 

Best,
Carrie

-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by jhpoelen** [comment]
@carrieseltzer the plant-animal interactions of the Africa Tree Database are now available through GloBI. See http://www.globalbioticinteractions.org/index.html#interactionType=interactsWith&accordingTo=Seltzer or attached screenshot for info.

![screen shot 2016-01-19 at 9 01 42 am](https://cloud.githubusercontent.com/assets/1084872/12425791/5171f1e2-be8b-11e5-918c-26261531b4f3.png)

**Comment by jhammock** [comment]
Probably not important, but just in case: Carrie has updated these two table, which had some corrupted rows. If you happened to use them, @jhpoelen , you may want to refresh:

· Common names of African trees. http://dx.doi.org/10.6084/m9.figshare.1526129
· Medicinal uses of African plants. http://dx.doi.org/10.6084/m9.figshare.1526133

**Comment by jhpoelen** [comment]
@jhammock thanks for sharing. At this point, GloBI is not using the tables that Carrie refreshed. At this point, only the following data publication is used (from https://github.com/globalbioticinteractions/AfricaTreeDatabase/blob/master/globi.jso ):

Seltzer, Carrie; Wysocki, William; Palacios, Melissa; Eickhoff, Anna; Pilla, Hannah; Aungst, Jordan; Mercer, Aaron; Quicho, Jamie; Voss, Neil; Xu, Man; J. Ndangalasi, Henry; C. Lovett, Jon; J. Cordeiro, Norbert (2015): Plant-animal interactions from Africa. figshare. https://dx.doi.org/10.6084/m9.figshare.1526128
