### ISSUE TITLE
Ecological Database of the World's Insect Pathogens

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#185]
suggested by @diatomsRcool -

http://cricket.inhs.uiuc.edu/edwipweb/edwipabout.htm 

Thanks Anne!

**Comment by millerse** [comment]
@jhpoelen Has anyone taken a stab at this?

**Comment by jhpoelen** [comment]
@millerse I don't think anyone has worked on this yet. From the website, it looks like the project has been around for a while (15+ years) and the author David W. Onstad is still active. I think it would be great we could work with the author to first publish the data and then include it in GloBI. Perhaps you can consult with @jhammock or @KatjaSchulz on that. Hope this helps.

**Comment by millerse** [comment]
@KatjaSchulz So I took a look at the site and the data is presented in a table with general information and then very specific information in individual pages (see here: http://cricket.inhs.uiuc.edu/edwipweb/FMPro and here: http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=nvpassoc.fp5&-format=nvp%5frecord%5fdetail.htm&-lay=web%20form&-max=20&-recid=1&-findall=).

Can you help me with finding a code that will let me gather all the information without having to copy and paste page by page for all 7,000+ records?

**Comment by jhpoelen** [comment]
Inspecting the urls for the search pages, had me create urls that list all associations records for the difference "files". Notice the "max=..." for each of the urls. I chose the "max" for each of the files to be slightly more than the number of respective records. With this, you can use tools like ```wget``` to crawl and download the associated html pages. Then, with some scripting, you might be able to transform the html pages to a tabular format.

 file | urls
 --- | ---
 host classification and ecology | http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=hosts.fp5&-format=ho_search_results.htm&-lay=web%20table&-max=5000&-skip=0&-findall=
 nonviral pathogen classification | http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=pathogen.fp5&-format=path_search_results.htm&-lay=web%20query&-max=2100&-findall=
  negative test results | http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=negative.fp5&-format=neg_search_results.htm&-lay=web%20query&-max=600&-findall=
  virus associations | http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=viruses.fp5&-format=vir_search_results.htm&-lay=web%20query&-max=1700&-findall=
  nematode assocations | http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=nematode.fp5&-format=nema_search_results.htm&-lay=web%20query&-max=240&-findall=
  non-viral pathogen associations | http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=nvpassoc.fp5&-format=nvp_search_results.htm&-lay=web%20form&-max=7200&-findall=
  citations | http://cricket.inhs.uiuc.edu/edwipweb/FMPro?-db=citation.fp5&-format=ref_search_results.htm&-lay=web%20query&-max=2000&-findall=

**Comment by millerse** [comment]
@jhpoelen It does.  Thanks for the help.  I will keep you posted on my progress.

**Comment by millerse** [comment]
@jhpoelen Okay, so I have the files.  The code worked perfectly.  But now I have 10,000+ files with information.  Is there a code that you know of that I can run that will put the information into a single file?

**Comment by millerse** [comment]
@jhpoelen Nevermind.  Katja helped me on that one.

**Comment by jhpoelen** [comment]
@millerse glad to hear things are coming along. I hope that you'll publish both the 10,000+ files (as a zip archive perhaps), the scripts used to extract the information, and the resulting csv files. Also, I'd say that a little description in the README.md of the magic you used to turn the one into the other would be informative.

**Comment by millerse** [comment]
DONE at last! [dataset](https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens)

**Comment by KatjaSchulz** [comment]
@millerse You acknowledged EDWIP for all the records where they did not provide a reference, but we should acknowledge them as the source of the data for every single record.  This means we should have both a source (where WE got the data from) and a reference (where they got the data from). Can @jhpoelen 's template accommodate that?

**Comment by jhpoelen** [comment]
As far as I can tell, @millerse attributed the source in the https://github.com/millerse/Ecological-Database-of-the-World-s-Insect-Pathogens/blob/master/globi.json file. The references mentioned in the source are in the column ```referenceCitation``` in the interactions.tsv file. So, yes, the template allows for attributing both the source and the references mentioned in that source.

**Comment by KatjaSchulz** [comment]
Ah, nevermind.  I missed that. We just have to make sure that this source attribution is at the record level when the data land in EOL.

**Comment by jhpoelen** [comment]
Looks like the 30k (!) interactions have propagated and are ready for review by @KatjaSchulz or @jhammock (see attached).

![screenshot from 2016-12-15 15-31-22](https://cloud.githubusercontent.com/assets/1084872/21246139/aa9f9666-c2db-11e6-9999-ea9911501756.png)

**Comment by jhpoelen** [comment]
@jhammock please let me know how you'd like to proceed on reviewing this dataset provided by @millerse .

**Comment by jhammock** [comment]
This looks good, but I would like to see URIs in the sourceTaxonStage, eg:
http://eol.org/schema/terms/eggStage
http://purl.obolibrary.org/obo/PATO_0001185
http://www.ebi.ac.uk/efo/EFO_0001272

**Comment by millerse** [comment]
@jhammock fixed those stages.

**Comment by jhammock** [comment]
Looks great, thanks!
