### ISSUE TITLE
Resolved ids in Unmatched Taxon Id

### ISSUE THREAD

**Issue by millerse** [jhpoelen/eol-globi-data#187]
I added ids to some unmatched taxa and they still appear in the latest version of the unmatched taxon id sheet on the globi main site.  If those could be removed, that would be very helpful.

**Comment by jhpoelen** [comment]
@millerse please confirm that these are the examples:

unmatched name | unmatched id
--- | ---
... | ...
marine detritus	 | ENVO:01000155
terrestrial detritus | ENVO:01000155

**Comment by jhpoelen** [comment]
Found the underlying issue. Will fix issue if the fix propagates to the data.

**Comment by millerse** [comment]
@jhpoelen Yes

**Comment by jhpoelen** [comment]
@millerse thanks! I also checked the current (as of Monday 16 November 2015) unmatchedTaxa.csv and appears that the ENVO terms are no longer present.
