### ISSUE TITLE
Greystock et al. 2015 Do managed bees drive parasite spread and emergence in wild bees?

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#188]
Bees and their parasites: spatial-temporal species interactions.
Greystock et al. 2015 Do managed bees drive parasite spread and emergence in wild bees? http://dx.doi.org/10.1016/j.ijppaw.2015.10.001

**Comment by millerse** [comment]
@jhpoelen Unfortunately, this paper was withdrawn from the site.

**Comment by millerse** [comment]
Paper is back up

**Comment by millerse** [comment]
And done: https://github.com/millerse/Greystock-et-al.-2015

**Comment by jhammock** [comment]
This looks great! I don't see a figure in the paper, but perhaps I'm missing it? If you pulled the records out of the text (oof) can I request individual references be added? It looks like they're usually present.

Looks like there's some confusion in the paper about the spelling of the Asian honeybee; I think Apis ceranae is a typo. They can all go in as Apis cerana.

**Comment by jhpoelen** [comment]
@millerse did you get a chance to address @jhammock  comments?

**Comment by millerse** [comment]
Just did
