### ISSUE TITLE
index image urls for taxa 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#195]
Currently, taxon images are not indexed by GloBI. However, images can be retrieved through the GloBI api. This api calls the eol api to retrieve images. This means that whenever the EOL api is unresponsive or unavailable, GloBI cannot point to images (e.g. see https://github.com/jhpoelen/eol-globi-data/issues/194).

Suggest to index images so that GloBI can provide images urls (not images themselves) without having to consult an external api.

**Comment by jhpoelen** [comment]
Thumbnails for taxa that are resolved through EOL are now indexed to provide for fast access to thumbnails given a . For example ```http://api.globalbioticinteractions.org/imagesForName/Homo%20sapiens``` returns:

```json
{"thumbnailURL":"http://media.eol.org/content/2014/08/07/23/02836_98_68.jpg",
"imageURL":null,
"infoURL":"http://eol.org/pages/327955",
"pageId":"327955",
"scientificName":"Homo sapiens",
"commonName":"Humans",
"taxonPath":"Animalia | Bilateria | Deuterostomia | Chordata | Vertebrata | Gnathostomata | Tetrapoda | Mammalia | Theria | Eutheria | Primates | Haplorrhini | Simiiformes | Hominoidea | Hominidae | Homininae | Homo | Homo sapiens"
}
``` in a fraction of a second.

Note that only a fraction of the available taxon information (e.g. links to various taxonomies) is provided. 

@jhammock though you might be interested in this - a "microservice" using EOL data to solve a specific problem: getting a thumbnail for a specific taxon.

**Comment by jhammock** [comment]
Yup, this is cool, and would meet the needs of a lot of API users...
