### ISSUE TITLE
parasitic plant connection http://parasiticplants.siu.edu/

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#197]
suggest to add http://parasiticplants.siu.edu/ 

from their website:

As of November 2010, The Parasitic Plant Connection contains over 4000 files, 3564 of these image files of parasitic and mycoheterotrophic plants.  And of course, the family pages link to many photographs being maintained on other servers. At present there are over 760 links to at least one remote image.

**Comment by millerse** [comment]
Taken care of: https://github.com/millerse/parasitic-plant-connection

**Comment by jhpoelen** [comment]
@jhammock please let me know how you'd like to proceed on reviewing this dataset provided by @millerse .

**Comment by jhammock** [comment]
looks lovely!
