### ISSUE TITLE
link to WoRMS

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#204]

**Comment by jhpoelen** [comment]
Thanks for the quick replies of Bart Vanhoorne of the WoRMS Data Management Team for establishing a bi-directional link between GloBI and WoRMS (see screenshots).

![screen shot 2016-02-04 at 10 52 36 am](https://cloud.githubusercontent.com/assets/1084872/12825923/7ab88e0e-cb2d-11e5-9777-eb9b21dea375.png)

![screen shot 2016-02-04 at 10 54 06 am](https://cloud.githubusercontent.com/assets/1084872/12825968/b0e5882e-cb2d-11e5-99bf-71943c7d1e2f.png)

**Comment by jhammock** [comment]
This is awesome.
