### ISSUE TITLE
MammalDIET - A comprehensive global dataset of diet preferences of mammals

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#205]
from http://datadryad.org/resource/doi:10.5061/dryad.6cd0v :

"A comprehensive global dataset of diet preferences of mammals (‘MammalDIET’). Diet information was digitized from the literature and extrapolated for species with missing information. The original and extrapolated data cover species-level diet information for >99% of all terrestrial mammals."

**Comment by millerse** [comment]
Do you need someone to get dataset into Github?  If so, I have some time to do so.

**Comment by jhpoelen** [comment]
That would be great! Perhaps we should include @jhammock @KatjaSchulz to determine which available should be transcribed first. There's a bunch of pending datasets. . . 

Meanwhile, I was wondering whether you got a chance to look at a  a new column mapping technique I've added a while ago (see https://github.com/globalbioticinteractions/AfricaTreeDatabase/blob/master/globi.json). The idea is that you point to a tabular file and define the mapping in the globi.json .

**Comment by jhpoelen** [comment]
Closing this issue because it is a duplicate of #183 .
