### ISSUE TITLE
Zika vectors and hosts?

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#206]
It looks like the Zika virus ([EOL](http://www.eol.org/pages/541190/overview) and [NCBI](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=64320&lvl=3&lin=f&keep=1&srchmode=1&unlock)) didn't make it into GloBI yet. 

@millerse @jhammock @KatjaSchulz do you think it would be worthwhile to add some of Zika's vectors and hosts?

**Comment by jhammock** [comment]
Good call; let is stay on top of the important viruses. @millerse, do you fancy a break from your Odonata to track down some Zika virus hosts? Google Scholar seems to have [some ideas](https://scholar.google.com/scholar?q=zika+virus+hosts&btnG=&hl=en&as_sdt=0%2C9)...

**Comment by millerse** [comment]
@jhpoelen @jhammock will get on that.

**Comment by millerse** [comment]
[Set up a new collection here](https://github.com/millerse/Zika-Virus)

**Comment by KatjaSchulz** [comment]
Hi Sarah, RO:0002444 (parasite of) is not the appropriate term to describe the relationship between the virus and the mosquito.  You should use RO:0002459 (is vector for) or RO:0002460 (has vector) for this, i.e.: 
EOL:541190	Zika virus (ZIKV)	RO:0002460	has vector	EOL:740699	Aedes aegypti
or 
EOL:740699	Aedes aegypti	RO:0002459	is vector for	Zika virus (ZIKV)	EOL:541190

This raises an interesting issue.  Since vectors can be host-specific, we would ideally describe a 3-way relationship here, i.e., Aedes aegypti is vector for Zika virus (ZIKV) in Homo sapiens.  Has this sort of thing ever come up before?  Has a solution been discussed?

**Comment by jhpoelen** [comment]
@millerse thanks for taking action! 

@KatjaSchulz agree on the interaction types has vector / is vector for. 

Topic of three way (or n-way) interactions did come up at points, and this might be a great example to help advance this. Opened a new issue for this here https://github.com/jhpoelen/eol-globi-data/issues/207 .

Meanwhile, I'd like to suggest to encode this using the existing method, with something like:

Zika virus (eol id) pathogenOf (RO id) Homo sapiens (eol id)

Aedes aegypti (eol id) vectorOf (RO id)  Zika virus (eol id)

Aedes aegypti (eol id) parasiteOf (RO id) Homo sapiens (eol id)

**Comment by cmungall** [comment]
I'm just filing a RO ticket to try and clarify when vector can be used. I think it's obvious here, but there may be cases where the difference between vector, reservoir and infected intermediate organism may not be clear

**Comment by millerse** [comment]
@KatjaSchulz @jhpoelen Just changed the intercation type

**Comment by KatjaSchulz** [comment]
Hi Sarah, 

Your revision is not correct.  Humans are not vectors for the virus.  They are the host.  

I think it's best to recode all the interactions using Jorrit's suggestions:  
Zika virus (eol id) pathogenOf (RO id) Homo sapiens (eol id)
Aedes aegypti (eol id) vectorOf (RO id) Zika virus (eol id)
Aedes aegypti (eol id) parasiteOf (RO id) Homo sapiens (eol id)

**Comment by jhpoelen** [comment]
Interesting! I thought I read that humans can sexually transmit the Zika virus when infected. I didn't check whether the cited publication included this, but if it did, does that make humans a vector of the Zika virus?

**Comment by millerse** [comment]
For what it is worth: http://www.cnn.com/2016/02/02/health/zika-virus-sexual-contact-texas?sr=nl_5things_zikavirussexualcontact

**Comment by millerse** [comment]
@KatjaSchulz @jhpoelen How about now?

**Comment by jhpoelen** [comment]
Looks good to me. @KatjaSchulz any suggestions?

**Comment by cmungall** [comment]
@jhpoelen - your interpretation seems to fit most definitions of vector that I can find. But this does render the vector concept very weak, inclusive and labile, and it seems unconventional to include humans as vectors in these scenarios?

I have seen some definitions of vector in which the vector is not afflicted with a disease - but this would also cover non-symptomatic human carriers.

I would have thought the most biologically useful definition would be in terms of lifecycle of the agent (vector as intermediate; completes life cycle in host). But I can't find any backing for this.

http://purl.obolibrary.org/obo/IDO_0000418 says the organism must be 'active' in the transfer. We might think of biting as active, but (say) sneezing as passive? But this seems like a difficult property to assign.

Domain expert opinion required!

**Comment by KatjaSchulz** [comment]
@jhpoelen @cmungall   I suspect even with expert input, the "vector" concept remain somewhat fuzzy.  Most classic vector relationships involve arthropods.  Some people also consider rodents, bats, etc. "vectors of disease," but others prefer to distinguish between vector-borne and zoonotic diseases.  In any case, I don't think anybody would talk about "vectors" in the case of intra-specific disease transmission.  Vectors usually operate across species borders.

**Comment by KatjaSchulz** [comment]
@millerse You still have the Rhesus monkey coded as a vector.  I suspect that it's actually the host (so would need a PathogenOf relationship) and it should have a mosquito vector that needs to get a ParasiteOf relationship.

**Comment by millerse** [comment]
@KatjaSchulz Actually, the monkey was the first species to have been infected with the Zika Virus.  I got rid of the vector and added a parasiteof relationship.

**Comment by KatjaSchulz** [comment]
What's a rhesus monkey doing in Uganda anyway?  They don't occur there naturally, so this must have been a lab monkey? In that case, I don't think we should include it in GloBi.  What do you think @jhpoelen ?

**Comment by cmungall** [comment]
yes, 

https://en.wikipedia.org/wiki/Zika_virus#Virus_isolation_in_monkeys_and_mosquitoes.2C_1947

interesting question, not sure where to draw the line with anthropogenically influenced interactions.

**Comment by jhpoelen** [comment]
@KatjaSchulz sorry for my late reply. About the monkey in Uganda: if someone reported a monkey in Uganda, then the monkey appeared in Uganda. I can imagine that a specimen could be marked or associated with a property like "captive" or "caged". If you'd like to further explore this categorization of the captive/wild/farmed kind of state of the interacting organism, please open a new issue.

**Comment by jhpoelen** [comment]
On another note, I noticed that Zika virus does not appear in searches in http://globalbioticinteractions.org by name, but it does appear by EOL id (see http://www.globalbioticinteractions.org/?sourceTaxon=EOL%3A541190&interactionType=interactsWith)

![screen shot 2016-03-15 at 10 33 26 am](https://cloud.githubusercontent.com/assets/1084872/13787491/6795d81e-ea99-11e5-81ae-f65970bf2c8a.png)

Closing this issue, because @millerse added the Zika interactions. Thanks @millerse ! 

Opening a separate issue on the Zika virus name search here: https://github.com/jhpoelen/eol-globi-data/issues/213 .
