### ISSUE TITLE
Dunne et al. 2016. The roles and impacts of human hunter-gatherers in North Pacific marine food webs.

### ISSUE THREAD

**Issue by woodsp** [jhpoelen/eol-globi-data#210]
Hey Jorrit, there are two new food webs from Sanak Island at

  http://www.nature.com/article-assets/npg/srep/2016/160217/srep21179/extref/srep21179-s2.xls

from [Dunne, et al. 2016. The roles and impacts of human hunter-gatherers in North Pacific marine food webs. Scientific Reports 6: 21179.](http://dx.doi.org/10.1038/srep21179)

**Comment by jhpoelen** [comment]
Hi Spencer @woodsp :

Congratulations on your publication on thanks for sharing the references to it!

A brief glance at the methods section in the paper made me wonder about the overlap of method used between ```Szoboszlai AI, Thayer JA, Wood SA, Sydeman WJ, Koehn LE (2015) Data from: Forage species in predator diets: synthesis of data from the California Current. Dryad Digital Repository. http://dx.doi.org/10.5061/dryad.nv5d2 Accessed at http://datadryad.org/bitstream/handle/10255/dryad.94536/CCPDDlinkdata_v1.csv ``` and this particular study. 

The reason I am interested in this is that Szoboszlai et al. 2015 published the data in a way that is machine readable and allows for tracing the food web link assertions back to supporting evidence. I would imagine that the scientists whose work you used to construct your food web might appreciate a data reference to their publication. In addition, a researcher who is interested in carefully studying the food web link assertions that were made, would need this information to trace back to the supporting evidence. From the text in [your publication](http://www.nature.com/articles/srep21179) "[...] A total of 20,145 feeding links were observed in the field or compiled from descriptions in 1,532 peer-reviewed publications, dissertations, technical reports, or online databases, a more comprehensive version of the sources used in Wood et al. 2015. [...]", I would expect to see at many as 1,532 references associated to the food web links.

Please let me know what I can do to associate proper data citation with the food web you shared. Ideally, a pre-existing format Szoboszlai et al. 2015 would be re-used to avoid extra work in making your valuable work machine readable.

-jorrit

**Comment by woodsp** [comment]
Hi Jorrit, indeed, the webs were constructed using very similar methods as Szoboszlai et al 2015 and Wood et al 2015.  And I agree completely that the links should be attributed and in a more machine-readable format.  Nonetheless, this is the format that the team decided to publish, and will hopefully improve on in future papers.

**Comment by jhpoelen** [comment]
Thanks for clarifying!

**Comment by jhpoelen** [comment]
Data is now available through GloBI (see screenshot and http://www.globalbioticinteractions.org/?sourceTaxon=Homo%20sapiens&interactionType=interactsWith&accordingTo=http%3A%2F%2Fdx.doi.org%2F10.1038%2Fsrep21179). 

@woodsp if you ever would like to chat about ways to capture food webs in a re-usable format, please let me know. Out of the three formats you've used across Szoboszlai et al. 2015, Wood et al. 2015 and Dunne et al. 2016, I like the one from Wood et al. 2015 best: a structured, single-table format in csv that is easy to parse.
