### ISSUE TITLE
Adams et al. 2016 A century of Chinook salmon consumption by marine mammal predators in the Northeast Pacific Ocean

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#224]
Paper contains reference to diet dataset related to predators of Chinook Salmon (_Oncorhynchus tshawytscha_). It seems that they used github to prepare data/figured for the closed access paper: https://github.com/eric-ward/marine_mammal_salmon_diet_database/blob/master/Consumption%20spreadsheet_noThomas.xlsx . Hopefully we can find a way to convince @eric-ward to convert the xlsx datafile to a more machine readable, and open, csv/tsv format.

**Comment by eric-ward** [comment]
I also uploaded a csv version of the main .xlsx file. In the markdown document, we'd used Hadley Wickham's readxl package, so you'd obviously have to use something else to import the data - read.table, read.csv, etc

**Comment by jhpoelen** [comment]
Thanks for adding the csv file on such short notice.

I was also wondering whether you considered using taxon ids / scientific name to describe predator / prey  (e.g. ITIS:161980 or http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=161980 for Chinook Salmon (_Oncorhynchus tshawytscha_)) and/or geonames.org ids for the locales (e.g. geonames id 5807483 http://www.geonames.org/5807483 ). 

In my experience, using these explicit ids (or links) improve the ability of the dataset to be integrated, linked and re-used in future research / synthesis efforts. For instance, lat/lng pairs for the locations can be derived automatically to enable geospatial searches.

I do realize that your data has been published and you might be hesitant to spend some time to add a few new columns. Regardless, I think your dataset would make a valuable addition to GloBI.

**Comment by jhpoelen** [comment]
@millerse @jhammock - interested in tackling this one?

**Comment by millerse** [comment]
@jhpoelen I can.

**Comment by jhpoelen** [comment]
@millerse thanks for adding a first pass at the data. I took at brief look at it and shared an observation [here](https://github.com/millerse/Adams-et-al.-2016/issues).

@jhammock do you mind have a peek at the result also.

**Comment by jhpoelen** [comment]
@millerse thanks for adding the interactions and making the suggested changes. 

@eric-ward if you are interested how @millerse transcribed your data, please see https://github.com/millerse/Adams-et-al.-2016 .

**Comment by jhpoelen** [comment]
from http://www.globalbioticinteractions.org/?interactionType=interactsWith&accordingTo=http%3A%2F%2Fdx.doi.org%2F10.1016%2Fj.ecoinf.2016.04.010 :
![screen shot 2016-09-02 at 8 03 13 pm](https://cloud.githubusercontent.com/assets/1084872/18222319/d184b098-7148-11e6-8432-6ea0917d5439.png)

**Comment by jhammock** [comment]
This looks good to me, but one question- what field does targetNote map to, in the EOL DwC-A?
