### ISSUE TITLE
introduce term "adjacent to" /  RO:0002220

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#225]
as suggested by @KatjaSchulz in http://www.inaturalist.org/observations/3085320 (see screenshot) referencing [Ramona's comments](https://github.com/PopulationAndCommunityOntology/pco/issues/7) and [RO:0002220](http://purl.obolibrary.org/obo/RO_0002220). 

![screen shot 2016-05-11 at 9 19 32 am](https://cloud.githubusercontent.com/assets/1084872/15188248/8355f1fa-1759-11e6-98d6-164293096db9.png)

**Comment by cmungall** [comment]
Would you like a more descriptive relation? Note that formally for adjacency to hold, surfaces must be in contact.

**Comment by jhpoelen** [comment]
I think it would be nice to add an example or two to the definition to show usage.

**Comment by KatjaSchulz** [comment]
I don't think the "surfaces must be in contact" requirement is a problem with our intended usage of RO:0002220 for animals that are "found on" plants without feeding being observed.  If the animals wasn't in actual contact with the plant surface, it would be "found near" which everybody agrees is a very different kind of relation. See https://github.com/PopulationAndCommunityOntology/pco/issues/7

**Comment by jhpoelen** [comment]
Added the interaction to GloBI as discussed. Please note that the temporal interpretation seems to indicate that the interaction must be valid at all times. This is why I didn't include the "pollinates" or "eats" associations as a kind of "adjacent to" interaction. Happy to make changes when necessary to reflect more nuanced interpretation of this interaction.

**Comment by cmungall** [comment]
On 9 Jun 2016, at 8:40, Jorrit Poelen wrote:

> Added the interaction to GloBI as discussed. Please note that the 
> temporal interpretation seems to indicate that the interaction must be 
> valid at all times.

If you are using this relation for GloBI this qualifier can be ignored.

It is important for making an OWL compliant dump of GloBI - we'd be sure 
to have the axioms such that the relation would only hold for snapshots 
of the organism instances. But as the RDF globi is off, this is not 
really relevant, you're using RO as a vocabulary.

For more info:
This is the class axiom interpretation. See 
https://github.com/oborel/obo-relations/wiki/ROAndTime
