### ISSUE TITLE
travis integration test for individual datasets

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#228]
as suggested by @millerse @cmungall -

introduce a way to check how GloBI ingests existing individual datasets.

This would help make it easier to troubleshoot issues and check for errors without have to import/export all datasets.

Use case:
1. create a new globi-github repository
2. add configuration / mapping files
3. submit changes
4. triggered by the changes, an automated process (e.g. travis-ci.org) runs a GloBI integration test on the updated datasets
5. if there is an error in the data integration, notifications are sent

**Comment by jhpoelen** [comment]
@cmungall Here's an example of a first pass at the "globinizer" check https://github.com/jhpoelen/Dapstrom-test . What do you think?

**Comment by cmungall** [comment]
nice!

**Comment by jhpoelen** [comment]
@cmungall glad you like it. I've added some docs, including working configuration using the template data-set: https://github.com/globalbioticinteractions/template-dataset .
