### ISSUE TITLE
neo4j data archive fails to export to tar.gz due to tar size limit contraints

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#231]
Due to growth of GloBI, the neo4j data dump no longer "fits" in a tar.gz archive resulting in an error message like:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (make-assembly) on project eol-globi-datasets: Failed to create assembly: Error creating assembly archive neo4j-graph-db: Problem creating TAR: request to write '0' bytes exceeds size in header of '-2136930534' bytes -> [Help 1]
[ERROR] 
```

**Comment by jhpoelen** [comment]
switched to zip archive that does not appear to have this file size constraint.

**Comment by BrianHayden** [comment]
We're going to need a bigger boat!

Sent from my iPhone

On May 18, 2016, at 5:43 PM, "Jorrit Poelen" <notifications@github.com<mailto:notifications@github.com>> wrote:


switched to zip archive that does not appear to have this file size constraint.

-
