### ISSUE TITLE
Wirta et al, 2015, Arctic food web

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#237]
Not huge but important in light of current interest in Arctic eology and climate change. @millerse, care to have a look? http://onlinelibrary.wiley.com/doi/10.1002/ece3.1647/full

**Comment by millerse** [comment]
And it's [done](https://github.com/millerse/Arctic-food-web)

**Comment by jhammock** [comment]
Nice! Remind me to try an Arctic GloBI search next week...
