### ISSUE TITLE
integrate with NHM Interactions Bank

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#241]
curated by @edwbaker and available through NHM's data portal: 

Ed Baker (2016). Dataset: NHM Interactions Bank. http://dx.doi.org/10.5519/0060767
Retrieved: 18:20 03 Aug 2016 (GMT)

**Comment by edwbaker** [comment]
This is a very preliminary version of what we hope to make available, and also subject to changes - not least because the source data are liable to some major changes. 

But consider it a statement of intent.

**Comment by jhpoelen** [comment]
First pass at NHM Interactions Bank is now available through GloBI using https://github.com/globalbioticinteractions/natural-history-museum-london-interactions-bank . For example of resulting interactions, see attached screenshot of http://www.globalbioticinteractions.org/index.html?interactionType=interactsWith&accordingTo=NHM%20Interactions%20Bank .
![screen shot 2016-08-08 at 7 59 36 am](https://cloud.githubusercontent.com/assets/1084872/17484367/4ebc1fca-5d3e-11e6-8133-eb268528c2fc.png)

Future improvements will be recorded in separate issues.
