### ISSUE TITLE
Vectors and Parasites - Judicaël Obame-Nkoghe et al. 2016 DOI 10.1186/s13071-016-1625-z

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#246]
Bat flies (Diptera: Nycteribiidae andStreblidae) infesting cave-dwelling bats in Gabon: diversity, dynamics and potentialrole inPolychromophilus melanipherustransmission http://dx.doi.org/10.1186/s13071-016-1625-z .

**Comment by millerse** [comment]
Done and ready to go: here`https://github.com/millerse/Bat-flies`

**Comment by jhammock** [comment]
This resource looks good!
