### ISSUE TITLE
report interactions with unknown/unmapped interaction type by source

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#247]
question asked by @edwbaker - 

`Is there a way to get a list of things that are not being harvested by GloBI so I can have an idea of where to start making fixes?`

**Comment by jhpoelen** [comment]
@edwbaker - I created a tool that simulates an ingestion into GloBI and reports warnings and errors, including skipped records or missing term mappings. This way the "build failed" idea van be re-used for datasets. 

I actually used this tool to find out that the locale ids extracted from nhm are not easy to resolve using existing resolver (ie geonames). For examples of related troubleshooting and fixing activity see https://github.com/globalbioticinteractions/natural-history-museum-london-interactions-bank (configuration of the data source, including column mapping), https://travis-ci.org/globalbioticinteractions/natural-history-museum-london-interactions-bank/builds (build history on travis), and a status page at http://globalbioticinteractions.org/status, including nhm data source. 

I also made an attempt to outline the method at https://github.com/jhpoelen/eol-globi-data/wiki/Dataset-Management . 

Curious to hear your thoughts on this.

**Comment by edwbaker** [comment]
The LocationID column is an internal identifier used by Scratchpads - it
looks like you had it mapped to Lat/Lng? Very few of our datasets have that
data, most are limited to country.



Edward Baker
--------------------
Biodiversity Informatics, Department of Life Sciences, Natural History
Museum
Informatics Advisor, International Commission on Zoological Nomenclature

edward.baker@nhm.ac.uk | http://ebaker.me.uk | http://bio.acousti.ca
<http://e-monocot.org/>
Skype: ewb1985 | Mobile: 07761807048 | Twitter: edwbaker
http://impactstory.org/edwbaker
<http://www.nhm.ac.uk/research-curation/staff-directory/entomology/e-baker/index.html>

**Comment by jhpoelen** [comment]
@edwbaker Thanks for clarifying. I was thinking to make an automated notification in case the nhm interaction bank <> globi integration needs some attention. Would you be interested in receive these notifications?

**Comment by edwbaker** [comment]
Yes - that would be useful!

Edward Baker
--------------------
Biodiversity Informatics, Department of Life Sciences, Natural History
Museum
Informatics Advisor, International Commission on Zoological Nomenclature

edward.baker@nhm.ac.uk | http://ebaker.me.uk | http://bio.acousti.ca
<http://e-monocot.org/>
Skype: ewb1985 | Mobile: 07761807048 | Twitter: edwbaker
http://impactstory.org/edwbaker
<http://www.nhm.ac.uk/research-curation/staff-directory/entomology/e-baker/index.html>

**Comment by jhpoelen** [comment]
Just added you to the notification list of https://github.com/globalbioticinteractions/natural-history-museum-london-interactions-bank/blob/master/.travis.yml . You should now get notifications if the globi <> nhm-ib has issues. The check is now configured to run weekly, or whenever changes occur in https://github.com/globalbioticinteractions/natural-history-museum-london-interactions-bank . Please don't hesitate to add others to the notification list or suggest changes. 

Please re-open the issue if you feel that it hasn't been addressed properly.
