### ISSUE TITLE
support searches with iNaturalist Taxon Ids

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#252]
Currently, interaction records imported from iNaturalist attempt to extract a GBIF taxon id when possible. However, the iNaturalist taxon id is not yet used.

@kueda suggested to make GloBI aware of iNaturalist Taxon Ids (e.g. www.inaturalist.org/taxa/117520 for _Enhydra lutris spp. nereis_) to make it easier for iNaturalist to link interaction records on the taxon level.

**Comment by kueda** [comment]
Just to be clear, while searching by iNat taxon ID would be nice, getting iNat taxon IDs back in the responses is even more important to us, e.g. getting them back from http://api.globalbioticinteractions.org/interaction?sourceTaxon=Quercus%20lobata instead of (or in addition to) identifiers like `EOL:185117`.

**Comment by jhpoelen** [comment]
Thanks for clarifying. Just poked around the inaturalist api to extract full taxonomic path (or ancestry) including scientific name, rank, inat taxon id, and common names (if available).

I am thinking to do the following:

First extract the ancestry ids from a inat taxon by (e.g. http://www.inaturalist.org/taxa/406089.json ). Then request all ancestors by ids using something like http://api.inaturalist.org/v1/taxa/406089,47126,48460 . 

So, resolving each taxon requires two round trips. Let me know if there's another approach you'd recommend.

**Comment by jhpoelen** [comment]
Just found that http://api.inaturalist.org/v1/taxa/406089 actually contains the ancestry. I'll use that instead of  http://www.inaturalist.org/taxa/406089.json .

**Comment by kueda** [comment]
According to https://github.com/dimus/gni/wiki/How-to-publish-your-scientific-names-list it seems like GNI should already be indexing the data we provide to GBIF. Is that not happening, @dimus? We only provide occurrences in our GBIF DwC-A, but we could start including taxonomic info too.

**Comment by jhpoelen** [comment]
@kueda regarding the INAT_TAXON prefix: I was checking the results today and found a caching issue that prevented the inaturalist taxa from appearing (see https://github.com/jhpoelen/eol-globi-data/commit/23b4d978f76615535374458894f9172adb4b1ce0). So, even though the iNaturalist taxonomy integration was in place, previously cached taxon items were linked. The joys of caching ; ) . Will keep you posted on progress.

**Comment by jhpoelen** [comment]
INaturalist searchable taxa are starting to appear in GloBI:
see http://www.globalbioticinteractions.org/?sourceTaxon=INAT_TAXON%3A67434&interactionType=eats
![screenshot from 2016-10-27 17-17-54](https://cloud.githubusercontent.com/assets/1084872/19789998/5b4f5a58-9c69-11e6-9919-c71176d66b3b.png)

I did fix another cache related issue just now. After this fix propagates, all inaturalist taxa referenced in inaturalist interaction records should be searchable. Until then, only inaturalist taxa that were previously unknown to GloBI are searchable (e.g. _Merops nubicoides_ is searchable by inat taxon, but Orthoptera is not (yet)).

More soon . . .

**Comment by dimus** [comment]
@kueda, would be nice if you make a checklist from your observations, for now I will just use your 
http://www.inaturalist.org/observations/gbif-observations-dwca.zip --- I will try to import it today

**Comment by dimus** [comment]
@kueda @jhpoelen I added iNaturalist taxa -- 

http://resolver.globalnames.org/name_resolvers?names=Pardosa%20moesta%20Banks,%201892&data_source_ids=180

Does it look right to you?

**Comment by jhpoelen** [comment]
@dimus nice! Thanks for doing this on such short notice. . . 

I noticed that the path ids are missing, I am assuming because they were missing from the dwca. If this is the case, I am hoping that @kueda can figure out a way to add them. With the path ids (higher order taxon ids), GloBI can support hierarchical searches by any rank published through iNaturalist, not just the taxa associated with interaction records.

**Comment by dimus** [comment]
@jhpoelen yes, you are right, there are no path ids in dwca for GBIF

**Comment by jhpoelen** [comment]
@kueda http://api.globalbioticinteractions.org/interaction?sourceTaxon=Enhydra%20lutris&type=json.v2&accordingTo=inaturalist now returns INAT_TAXON ids as discussed.

**Comment by jhpoelen** [comment]
After having confirmed that id searches like http://api.globalbioticinteractions.org/interaction?sourceTaxon=INAT_TAXON%3A133061&type=json.v2&accordingTo=inaturalist seem to produce reasonable results, I am closing this issue. Please feel free to re-open or comment on finding unexpected or missing behavior.

@kueda please work with @dimus to enable higher order inaturalist taxon searches by inat taxon id by providing taxon path ids in dwca or checklist. GloBI should pickup the changes automatically when these path ids are available.

**Comment by kueda** [comment]
@dimus, just to clarify, when you say "make a checklist" you mean include a file of taxon records in our Darwin Core Archive following the steps at https://github.com/GlobalNamesArchitecture/gni/wiki/How-to-publish-your-scientific-names-list#using-darwin-core-star-schema, right? Also, do you want that file to include only the taxa used in the observations, or all taxa period, or maybe all taxa from the obs and all their ancestor taxa?

**Comment by kueda** [comment]
@jhpoelen, is there a way to request that I get iNat taxon IDs back for interactions that did not come form iNat sources? E.g. with http://api.globalbioticinteractions.org/interaction?sourceTaxon=INAT_TAXON%3A4778 I'm asking for interactions with a taxon specified by an iNat taxon ID, but the target taxa in the response all have EOL identifiers, even taxa that iNat has reported interaction data for, e.g. Aquila chrysaetos. Or is this only going to work when I ask for interactions `accordingTo` iNaturalist?

**Comment by jhpoelen** [comment]
@kueda opened a new, related issue #258 to capture your feature request to capture iNaturalist taxon mapping for non-inaturalist interaction records.

**Comment by dimus** [comment]
@kueda, if you have stable IDs for names -- lets have all of them. Then we have a future-proof data, and if my harvest is outdated, globi will be able to get observations of completely new species anyway. Normally I collect names, vernaculars and synonyms. If you have synonyms and/or vernaculars supplied by your users -- I would love to have them, if not -- just scientific names is enough. If you can give classification through parent IDs, it would be the best. something like this would be enough information for me:

```
<?xml version="1.0"?>
<archive xmlns="http://rs.tdwg.org/dwc/text/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://rs.tdwg.org/dwc/terms/xsd/archive/ http://darwincore.googlecode.com/svn/trunk/text/tdwg_dwc_text.xsd">
  <core encoding="UTF-8" fieldsTerminatedBy="," fieldsEnclosedBy="&quot;" linesTerminatedBy="&#10;" rowType="http://rs.tdwg.org/dwc/terms/Taxon" ignoreHeaderLines="1">
    <files>
      <location>taxa.txt</location>
    </files>
    <id index="0"/> (taxonID)
    <field term="http://rs.tdwg.org/dwc/terms/parentNameUsageID" index="1"/> (parentID)
    <field term="http://rs.tdwg.org/dwc/terms/acceptedNameUsageID" index="2"/> (for synonyms to point to accepted name)
    <field term="http://rs.tdwg.org/dwc/terms/scientificName" index="3"/> (full scientific name with authors etc.)
    <field term="http://rs.tdwg.org/dwc/terms/taxonomicStatus" index="4"/> (synonym, valid, etc)
    <field term="http://rs.tdwg.org/dwc/terms/taxonRank" index="5"/> (rank of the clade)
  </core>
  <extension encoding="UTF-8" fieldsTerminatedBy="," fieldsEnclosedBy="&quot;" linesTerminatedBy="&#10;" rowType="http://rs.gbif.org/terms/1.0/VernacularName" ignoreHeaderLines="1">
    <files>
      <location>vernacular_names.txt</location>
    </files>
    <coreid index="0"/>
    <field term="http://rs.tdwg.org/dwc/terms/vernacularName" index="1"/>
    <field term="http://purl.org/dc/terms/language" index="2"/>
  </extension>
</archive>
```

In the simplest terms (if there are no synonyms or vernaculars, and all names are accepted names) ``taxonID``, ``scientificName``, ``parentUsageID``, ``taxonRank`` should do the trick I think.

**Comment by kueda** [comment]
We don't have stable IDs for names, just IDs for concepts. So if _Pseudacris regilla_ gets split into _Pseudacris regilla_, _Pseudacris sierra_, and _Pseudacris hypochondriaca_, all 4 of those concepts have separate IDs, even though two of them have the same name. Is that ok?

**Comment by dimus** [comment]
> We don't have stable IDs for names, just IDs for concepts. So if Pseudacris regilla gets split into Pseudacris regilla, Pseudacris sierra, and Pseudacris hypochondriaca, all 4 of those concepts have separate IDs, even though two of them have the same name. Is that ok?

It should be OK with GN -- all 4 records will be registered, but *Pseudacris regilla* will return 2 IDs
