### ISSUE TITLE
expose ID prefixes in API

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#253]
GloBI uses id prefixes like "EOL:", "GBIF:" and "INAT_TAXON:" to refer to external resources.

@kueda suggested to include a method in the GloBI api that helps expand the shortened prefixes to one (or more) resolvable urls. E.g. EOL:1 --> http://eol.org/pages/1 .

**Comment by cmungall** [comment]
See also: https://github.com/prefixcommons/

**Comment by jhpoelen** [comment]
@cmungall that looks nice. is there a way to make a reference to an external registry through https://github.com/prefixcommons/biocontext/blob/master/registry . 

Something like:

globi_registry.jsonld --> ld.globalbioticinteractions.org/prefixes

This way, duplication of prefix mapping could be reduced.

**Comment by jhpoelen** [comment]
@kueda for now, the prefixes are available through:

http://api.globalbioticinteractions.org/prefixes
```json
{
  "http://": {
    "url_prefix": "http://",
    "url_suffix": ""
  },
  "W:": {
    "url_prefix": "http://wikipedia.org/wiki/",
    "url_suffix": ""
  },
  "NBN:": {
    "url_prefix": "https://data.nbn.org.uk/Taxa/",
    "url_suffix": ""
  },
...
}
```
or

http://api.globalbioticinteractions.org/prefixes?type=csv

```csv
id_prefix,url_prefix,url_suffix
http://,http://,
W:,http://wikipedia.org/wiki/,
NBN:,https://data.nbn.org.uk/Taxa/,
...
```

**Comment by jhpoelen** [comment]
Create https://github.com/prefixcommons/biocontext/pull/8 as a gesture of contribution to prefix commons project. I do hope that some mechanism will be introduced to avoid introduced duplication.
