### ISSUE TITLE
add summary statistics to interaction queries

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#256]
as suggested by @kueda

```
[...] I'd like to see
these kinds of summary stats in results from
http://api.globalbioticinteractions.org/interaction as a way of
weighting edges in the graph, e.g. there are 10 studies showing sea
otters each purple sea urchins and 2 studies that show sea otters eat
ochre sea stars, maybe the former is a more important interaction
[...]
```

**Comment by jhpoelen** [comment]
simlar to #233 .

**Comment by jhpoelen** [comment]
@kueda there's some aggregate statistics on the taxon level that I could expose through the api. However, these aggregate statistics are across all data sources. Is that an issue?

**Comment by kueda** [comment]
So you mean I could get the number of sources that say sea otters each purple sea urchins, but I could not get the number of times iNaturalist said sea otters eat purple sea urchins? I think that's fine.

**Comment by jhpoelen** [comment]
Added first pass at summary statistics through existing, optional, field ```number_of_interactions```. 

e.g. http://api.globalbioticinteractions.org/interaction?type=json.v2&sourceTaxon=Enhydra&field=source_taxon_name&field=number_of_interactions&field=target_taxon_name&limit=3
produces:
```
[
  {
    "source_taxon_name": "Enhydra lutris",
    "number_of_interactions": 1,
    "target_taxon_name": "Phoca vitulina"
  },
  {
    "source_taxon_name": "Enhydra lutris",
    "number_of_interactions": 1,
    "target_taxon_name": "Larus occidentalis"
  },
  {
    "source_taxon_name": "Enhydra lutris",
    "number_of_interactions": 2,
    "target_taxon_name": "Nassarius fossatus"
  }]
```

Note that this only works for queries that do *not* use accordingTo or bbox queries. The summary statistics are only available to name/interactionType queries. 

Also note that duplicate interactions can be possible, because the taxon id are used to distinguish individual taxa. The taxon names are merely labels for human consumption.

@kueda let me know if this helps build more meaningful interactions graph. 

PS If you end up making interaction widgets, please do let me know. I'd very much like to re-use them in  the basic tools provided on globalbioticinteractions.org.

**Comment by kueda** [comment]
Ok, well I still think this is good to have in general, but not having these numbers when using `accordingTo` is a deal-breaker for me. I basically want to make a graph of interactions for a taxon from iNat data and weight the edges according to number of interactions, so for that I would need a) only interactions from iNat, b) iNat taxon IDs, c) number of sources (i.e. iNat observations) per interaction.

**Comment by jhpoelen** [comment]
I can see how that makes sense for your use case: re-opening issue. Thanks for your patience.

**Comment by jhpoelen** [comment]
@kueda am working on supporting your use case. . . and wanted to check what kind of information elements you'd like to have in the interaction summary. How about something like http://tinyurl.com/globi-inat-agg (have to run the query by clicking "run", for results see screenshot). The distinction between number_of_interactions and number_of_studies show that sometimes a single observation (= study) contains multiple interactions.

Other than taxon ids, interaction types, number_of_interactions, number_of_studies, are there any additional information elements you need for your use case?

![screenshot from 2016-11-16 09-28-35](https://cloud.githubusercontent.com/assets/1084872/20358018/1a97db40-abdf-11e6-9c52-01296acae63d.png)

**Comment by jhpoelen** [comment]
First pass at aggregate statistics is now available through fields like ```number_of_studies```, ```number_of_interactions``` and ```number_of_sources```. Note that in GloBI a study translates to an iNaturalist observation, so if you are interested in distinct sea otter interactions from inaturalist and number of studies (i.e. observations) that reported them, you can do something like:

 http://api.globalbioticinteractions.org/interaction?type=json.v2&sourceTaxon=Enhydra&field=source_taxon_name&field=target_taxon_name&field=number_of_studies&accordingTo=inaturalist

@kueda please close this issue if this now satisfies your use case.

**Comment by jhpoelen** [comment]
@kueda please re-open / comment on this issue if there's anything else you need. Closing for now.
