### ISSUE TITLE
Smith, K., Scanferla, A. 2016. Fossil snake preserving three trophic levels and evidence for an ontogenetic dietary shifts. Palaeobiodiversity and Palaeoenvironments. doi: 10.1007/s12549-016-0244-1

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#257]
paleo diet data publication as suggested by @diatomsRcool 

Smith, K., Scanferla, A. 2016. Fossil snake preserving three trophic levels and evidence for an ontogenetic dietary shifts. Palaeobiodiversity and Palaeoenvironments. doi: 10.1007/s12549-016-0244-1

**Comment by jhpoelen** [comment]
@jhammock please let me know how you'd like to proceed on reviewing this dataset provided by @millerse .

**Comment by jhammock** [comment]
repository, please?

**Comment by jhpoelen** [comment]
I'd say it is probably https://github.com/millerse/Fossil-snake

**Comment by jhammock** [comment]
Thanks! @millerse it would be nice to have lifestage urls in this one too, please. Everything else looks good!

**Comment by millerse** [comment]
@jhammock taken care of

**Comment by jhammock** [comment]
Fantastic, thanks!
