### ISSUE TITLE
return interaction data using specific taxonomy. 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#258]
Currently, taxon ids available through the /interaction api endpoint include the primary taxon id. The primary taxon id the first taxon match to be resolved for a specific interaction record. For instance, primary taxon ids for interactions mined from inaturalist will start with "INAT_TAXON" and point to inaturalist taxon ids. Non-primary ids are "similar" taxon ids found in other naming sources. You can currently search by primary and non-primary taxon results. However, in the search results, only the primary taxon id is included. 

In #252 @kueda expressed a desire to map all results following a search to a specific taxonomic id provider (in this case inaturalist), along the lines of ... /interaction?sourceTaxon=...&nameIdProvider=inat . This would include mapping for both inaturalist *and* non-inaturalist interactions.

@kueda - please feel free to chime in if I missed anything here.

**Comment by kueda** [comment]
I think that describes what I want, e.g. if I request http://api.globalbioticinteractions.org/interaction?sourceTaxon=Sylvilagus, I want to get back iNat taxon IDs for all the target taxa, even if the sources for the interactions are not iNaturalist.

**Comment by jhpoelen** [comment]
Previously, results returned from interaction queries did not allow for selecting from specific taxonomy. 

Currently, you can select taxa with a specific taxonomic namespace/prefix (for info on prefixes, see http://api.globalbioticinteractions.org/prefixes) using urls like:

http://api.globalbioticinteractions.org/interaction?sourceTaxon=Sylvilagus&taxonIdPrefix=INAT_TAXON

@kueda does this do the trick for you?

**Comment by kueda** [comment]
I think it does, thanks.
