### ISSUE TITLE
integrate with Archbold Biological Station Arthropod Collection

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#261]
As pointed out by Joanna M. of iDigBio: 

from https://www.idigbio.org/portal/recordsets/db4bb0df-8539-4617-ab5f-eb118aa3126b :
```This collection is unusually large for a field station, and serves multiple functions. There are more than 250,000 pinned and labeled insect specimens. Pinned specimens are in trays in glass-topped Cornell drawers, generally one species per tray. Many, but not all, identifications are by taxonomic specialists. Species occurring on the Station are the main focus of the collections, but there are specimens from elsewhere for comparative purposes. There is a large collection of North American ants, and the collection of wood-inhabiting insects includes many species of beetles and wasps from areas north of Florida.```

See also: http://symbiota4.acis.ufl.edu/scan/portal/collections/misc/collprofiles.php?collid=104

**Comment by millerse** [comment]
@jhpoelen Ok so this one has interaction data.  Should I do what I did with DAPSTROM incase the data is updated?
