### ISSUE TITLE
Checklists of Protozoans and Myxozoans of Freshwater and Marine Fishes of Basrah Province, Iraq

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#269]
May be worth checking that this is not already represented in an aggregate source...

https://www.researchgate.net/profile/Najim_Khamees/publication/309189021_Checklists_of_Protozoans_and_Myxozoans_of_Freshwater_and_Marine_Fishes_of_Basrah_Province_Iraq/links/5813979908ae90acb23b7951.pdf

**Comment by millerse** [comment]
And ready [here](https://github.com/millerse/Fishes-of-Basrah-Province-Iraq)

**Comment by jhammock** [comment]
THis looks good! Sorry for the delayed response.
