### ISSUE TITLE
Universal Chalcidoidea Database at nhm.ac.uk 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#279]
As suggested by Malcolm Storey - 

from http://www.nhm.ac.uk/our-science/data/chalcidoids/database/ : 

[...]
John S. Noyes

Welcome to the wonderful world of chalcidoid wasps!

Described as "gem-like inhabitants of the woodlands by most never seen nor dreamt of", chalcidoids include some of the most beautiful insects on the planet, but are amongst some of the most poorly known. [...]

- See more at: http://www.nhm.ac.uk/our-science/data/chalcidoids/#sthash.vYTgOxHe.dpuf

**Comment by jhpoelen** [comment]
I wonder whether Universal Chalcidoidea Database will be included in NHM's Interaction Bank of @edwbaker et al.  http://data.nhm.ac.uk/dataset/nhm-ib .

**Comment by edwbaker** [comment]
It will be happening (soon-ish)

**Comment by jhpoelen** [comment]
@edwbaker great to see that nhm is consolidating it's wealth of interaction datasets.
