### ISSUE TITLE
Lichenicolous Fungi at http://www.lichenicolous.net

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#282]
As suggested by Malcolm Storey - 

from http://www.lichenicolous.net -

Lichenicolous Fungi – Worldwide Checklist Including Isolated Cultures and Sequences Available
Phylogenetic Arrangement of Genera [...] Lichenicolous fungi live exclusively on lichens, most commonly as host-specific parasites, but also as broad-spectrum pathogens, saprotrophs or commensals. [...]

**Comment by millerse** [comment]
Okay this is ready for review.https://github.com/millerse/Lichenous

**Comment by jhammock** [comment]
Looks lovely! Nice find.
