### ISSUE TITLE
Taxon classification mismatch

### ISSUE THREAD

**Issue by SriniAnandIUDS** [jhpoelen/eol-globi-data#289]
When querying the neo4j database for specific kingdoms, we found a potential mismatch at the Kingdom level.

For example, the following query retrieves all know specimens in the Protozoa Kingdom

For neo4j v3.x use this query
START sourceTaxon = node:taxonPaths('path:Protozoa') 
MATCH (sourceTaxon)<-[x:CLASSIFIED_AS]-(sourceSpecimen)
WHERE EXISTS(sourceTaxon.externalId)
RETURN DISTINCT sourceTaxon.externalId, sourceTaxon.rank, sourceTaxon.path, sourceTaxon.pathNames, sourceTaxon.name, sourceTaxon.externalIds

For neo4j v1.9.9 use this query
START sourceTaxon = node:taxonPaths('path:Protozoa')
MATCH sourceTaxon<-[:CLASSIFIED_AS]-sourceSpecimen
RETURN DISTINCT sourceTaxon.name as TaxonName, sourceTaxon.externalId, sourceTaxon, sourceTaxon.externalIds
ORDER BY sourceTaxon.externalId

Most of the data returned is for the Protozoa family. However, we find some records have a path of Fungi or other Kingdoms.

**Example 1**
EOL:62056 of Genus Pleistophora has path Fungi | Microspora | Microsporea | Microsporida | Pleistophoridae | Pleistophora

However, the query returns this node as its externalId field labels it as Protozoa. The mismatch appears to be how EOL and GBIF classify this particular specimen

EOL (62056)
Fungi | Microspora | Microsporea | Microsporida | Pleistophoridae | Pleistophora
http://eol.org/pages/62056/overview

GBIF (7545195)
Protozoa › Microsporidia › Microsporea › Glugeida › Pleistophoridae
http://www.gbif.org/species/7545195

**Example 2**
OTT:722598		Bodo saltans		Protista | Euglenozoa | Kinetoplastea | Bodonidae | Bodo | Bodo saltans

GBIF (7761641)
Protozoa › Euglenozoa › Kinetoplastea › Eubodonida › Bodonaceae › Bodo
http://www.gbif.org/species/7761641

With the exception of the Archaea kingdom, all kingdoms exhibit this phenomenon.

**Comment by jhpoelen** [comment]
@SriniAnandIUDS thanks for reporting this detailed taxonomic linking challenge.

Re: genus Pleistophora - from my (non-biologist) view, it appears that the division https://en.wikipedia.org/wiki/Microsporidia of genus Pleistophora has been recently reassigned from being a protozoa to fungi. From https://en.wikipedia.org/wiki/Microsporidia (accessed at 11 April 2017):

```
[...] They were once considered protozoans or protists, but are now known to be fungi,[6] or a sister group to fungi.[7] [...]
```
So, it appears that the conflict you found is has been a topic of debate in recent history. It appears that EOL, Index Fungorum, NCBI taxonomy (and more) are using the Fungi kingdom, whereas GBIF and ITIS are *not* using the Fungi kingdom for this genus. So, the behavior is as expected and ... confusing.

**Comment by jhpoelen** [comment]
Re: species _Bodo saltans_ 

It appear that Protozoa is a kind of Protista (see http://eol.org/info/456). However, I do notice that some taxonomies (e.g. WoRMS, GBIF) use the Protozoa as a kingdom, whereas some consider Protista as a kingdom  (e.g. OTT). 
![screenshot from 2017-04-11 09-31-20](https://cloud.githubusercontent.com/assets/1084872/24919888/fc8f3fa2-1e99-11e7-8d3c-f8f16b3a36ab.png)

**Comment by jhpoelen** [comment]
The current functionality of the GloBI taxonomic path search is to include all linked taxa (e.g. Bodo saltans) that are considered the same, including those that might have been re-assigned in higher order taxonomic ranks. This is why a search for Protozoa might include some Fungi, because some protozoa have recently been reassigned to the Protista kingdom. 

Before, we get into ways to unconfuse the situation, please let me know if you follow my above comments. If not, please clarify where my explanation falls short.

Thanks again for sharing these valuable observations.

**Comment by jhpoelen** [comment]
Closing issue
