### ISSUE TITLE
ingest FoodII from fishbase/fooditems

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#293]
@BrianHayden suggested to ingest data from the FoodII field of https://fishbase.ropensci.org/fooditems in addition to the more granular Foodname field.

**Comment by jhpoelen** [comment]
@BrianHayden changes are in - waiting for changes to propagate before closing this issue.

**Comment by BrianHayden** [comment]
Quick work Jorrit! Excited to see what the data from the new BightGloBI show us....

**Comment by jhpoelen** [comment]
Changes have propagated. 

Please do note that FoodII terms ```finfish``` and ```herps``` have not yet been mapped. Any ideas?

**Comment by jhammock** [comment]
Arg! Herps could go to Tetrapoda, taxonomically speaking, but I wonder if it's worth it. Finfish should include both bony and cartilaginous fishes, so apart from Eugnathostomata or something, no great options. Certainly no way to exclude tetrapods that I can see...

**Comment by BrianHayden** [comment]
That's a messy one alright. I cant think of anything more suitable than Tetrapoda and Eugnathostomata

**Comment by jhpoelen** [comment]
Thanks! I've added your suggestions: something coarse is better than nothing. Note that the foodII item names are often accompanied by more specific names. Hopefully, it due time, the 25% remaining unmatch taxon names from fishbase / sealifebase will be resolved. Until then, we at least have a way to determine a coarse taxonomic location.

**Comment by jhpoelen** [comment]
I wish we had an easy way to distribute the taxonomic name linkage work while avoiding duplicated efforts.

**Comment by jhammock** [comment]
Indeed. We could start a support group with other names-harried projects! With data services and string matching...  That sounds like work.

**Comment by jhpoelen** [comment]
Hmm. How about something like: 

Store unresolved names, name corrections / suggestions in structure like (scroll down to see readme):
https://github.com/globalbioticinteractions/globi-names/tree/master/globalbioticinteractions/fishbase

Then, GloBI can harvest name corrections made by human curators from that some location.

features: version controlled, authentication (github needs login), room for discussion (comments) and disagreement (forks/merging).

Too crazy?

**Comment by jhpoelen** [comment]
Oh, and it would support searches:
https://github.com/globalbioticinteractions/globi-names/search?utf8=✓&q=herps&type=

**Comment by jhammock** [comment]
I get it, sort of. And Fishbase could also harvest the corrections if they chose? I had envisioned a single venue for everybody's names, but I suppose there's not so many advantages to that, and it would require that any names provider use a filter to get just their own names back, so maybe this is easier. If you plan to direct people to the "name status" field, though, it should be labeled :)

**Comment by jhpoelen** [comment]
@jhammock thanks for sharing your thoughts

Yes, Fishbase would be able to harvest the corrections if they choose to. 

The idea of splitting out the names by dataset is to incorporate the sense of ownership: I imagine that fishbase is much more concerned about fishbase names than about gophers in north east Texas. Also, the GloBI status page could link to the unresolved names by dataset.

Agree on the "name status" field - for the quick prototype, I didn't bother to include the column labels.

**Comment by jhpoelen** [comment]
Also, you could still chose to concatenate all name corrections into a giant list like the one that is currently published (taxonUnmatched.tsv at http://globalbioticinteractions.org/references ).

**Comment by jhammock** [comment]
Right. My initial fantasy was a single venue where anyone with names could add theirs, and searches would run across all of them- but I suppose that runs into scalability problems for human effort, let alone data display.

Speaking of which, there'll be a learning curve to accurately navigating to the correct column in edit mode, but again, you can't have everything at scale...

**Comment by jhpoelen** [comment]
I see no limited to be able to add your own names and search across all. In this case, GloBI would automatically provide unmatched names for specific datasets, and other projects/humans could do the same, even for non-GloBI datasets.

**Comment by jhpoelen** [comment]
As far as the column editing goes: I was thinking to add placeholder values like ```replace me``` or perhaps ```name suggestion```, that can be updated to be ```notSame``` or ```sameAs```.

**Comment by jhammock** [comment]
I like the placeholder idea, especially if this does scale. A neat method to turn a txt view into an easily edited document.
