### ISSUE TITLE
Checklist of Micro-Organisms Associated With Tree Seeds in the World

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#295]
Checklist of Micro-Organisms Associated With Tree Seeds in the World
Anderson, Robert L.
Date: 1986
Source: Gen. Tech. Rep. SE-39. Asheville, NC: U.S. Department of Agriculture, Forest Service, Southeastern Forest Experiment Station. 34 p.

https://www.srs.fs.usda.gov/pubs/viewpub.php?index=5496

**Comment by millerse** [comment]
Ready for Review: https://github.com/millerse/Checklist-of-Micro-Organisms-Associated-With-Tree-Seeds-in-the-World
