### ISSUE TITLE
Ecological Database of the World's Insect Pathogens

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#298]
http://cricket.inhs.uiuc.edu/edwipweb/edwip_search.htm

A few pages in the website failed for me, but the search per each of the six available files ("Select a file") worked fine. Contact is listed as David W. Onstad (onstad@uiuc.edu)

**Comment by jhpoelen** [comment]
Thanks for the pointer... Did you consider #185 ?

**Comment by jhammock** [comment]
oops! Lazy checks. My test species was missing; I expect it was newly added...

**Comment by jhpoelen** [comment]
Hmm. Now I am interested - which species? Perhaps we can check whether all the data it making it across . . . @millerse any ideas?

**Comment by jhammock** [comment]
let me see... ah, here it is: 

http://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Bibio%20ferruginatus

(see Nematode Associations file)
