### ISSUE TITLE
A life cycle database for parasitic acanthocephalans, cestodes, and nematodes by Benesh et al. 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#305]
As suggested by @derele - 

[...] 
I a currently interacting with Dan Benesh who compiled a database on parasite life cycles (http://onlinelibrary.wiley.com/doi/10.1002/ecy.1680/full)  ).  Dan will work with my team in Berlin soon. He told me that he also wants to include this data in globi, 
[...]

**Comment by dbenesh82** [comment]
Hi, I compiled this parasite life cycle database and have been meaning to get it into globi. If anything is unclear, I would be happy to help.

**Comment by millerse** [comment]
And done [see here](https://github.com/millerse/Benesh-et-al-2017/tree/master)

**Comment by jhammock** [comment]
Looks good! If you want to get fancy, you will probably find terms for some of the LocationinhostName values in [UBERON](http://bioportal.bioontology.org/ontologies/UBERON?p=classes&conceptid=root). I wouldn't bother chasing elusive ones, but if you find an exact match to the string you have, that should be worth using.

**Comment by cmungall** [comment]
Scanned the 78 distinct values, fairly sure we have them all, I can do 
the mapping if you like

**Comment by jhammock** [comment]
Fantastic! Yes please

**Comment by cmungall** [comment]
consider also mapping these to ENVO:

        Host.habitat: freshwater
        Host.habitat: marine
        Host.habitat: terrestrial

These to PATO:

               Shape: NA
               Shape: coiled
               Shape: cylinder
               Shape: ellipsoid
               Shape: leaf
               Shape: ribbon
               Shape: sphere
               Shape: thread-like
               Shape: whip

I would also use Uberon instead of EFO plus PATO for stages

**Comment by jhammock** [comment]
I'm not seeing those terms in this dataset, @cmungall - are you scanning all of GloBI now?

**Comment by cmungall** [comment]
OK, I did all these by hand. I think they are all correct. In cases of ambiguity I looked back at the source data from the suppl data in 10.1002/ecy.1680. I marked anything that is not totally trivial with `**`

```
air sacs,UBERON:0009060,air sac
bile duct,UBERON:0002394,bile duct
bladder,UBERON:0001255,urinary bladder***
blood system,UBERON:0004537,blood vasculature
body cavity,UBERON:0004458,body cavity or lining
brain,UBERON:0000955,brain
buccal cavity,UBERON:0000167,oral cavity
ceca,UBERON:0001153,caecum
central nervous system (spine),UBERON:0002240,spinal cord
cranial sinuses,UBERON:0001825,paranasal sinus
crop,UBERON:0007356,crop
diaphragm,UBERON:0001103,diaphragm
digestive gland,UBERON:0006925,digestive gland**
esophagus,UBERON:0001043,esophagus
esophagus wall,UBERON:0001096,wall of esophagus
eyes,UBERON:0000019,camera-type eye
fat,UBERON:0001013,adipose tissue
fins,UBERON:0008897,fin
gall bladder,UBERON:0002110,gall bladder
gall bladder surface,UBERON:0002110,gall bladder**
gastrosplenic ligament,UBERON:0004686,gastro-splenic ligament
gizzard,UBERON:0005052,gizzard
gizzard wall,UBERON:0005052,gizzard
gonads,UBERON:0000991,gonad
gut,UBERON:0001555,digestive tract
gut lumen,UBERON:0006909,lumen of digestive tract
gut wall,UBERON:0000328,gut wall
heart,UBERON:0000948,heart
hepatopancreas,UBERON:0010264,hepatopancreas
jaw bones,UBERON:0001708,jaw skeleton
kidneys,UBERON:0002113,kidney
larynx,UBERON:0001737,larynx
liver,UBERON:0002107,liver
liver surface,UBERON:0002107,liver**
lung surface,UBERON:0002048,lung**
lungs,UBERON:0002048,lung
lymph nodes,UBERON:0000029,lymph node
mesenteric arteries,UBERON:0005616,mesenteric artery
mesentery,UBERON:0002095,mesentery
mouth,UBERON:0000165,mouth
mucosa of mouth,UBERON:0003729,mouth mucosa
muscles,UBERON:0001630,muscle organ
nasal,UBERON:0001707,nasal cavity
nasal passage,UBERON:0001707,nasal cavity**
orbital cavities,UBERON:0004867,orbital cavity
pancreatic duct,UBERON:0007329,pancreatic duct
pericardial muscles,UBERON:2002221,pericardial muscle
peritoneal cavity,UBERON:0001179,peritoneal cavity
peritoneum,UBERON:0002358,peritoneum
pharynx,UBERON:0006562,pharynx
proventriculus,UBERON:0007357,proventriculus
proventriculus wall,UBERON:0007357,proventriculus**
pulmonary arteries,UBERON:0002012,pulmonary artery
pulmonary epithelium,UBERON:0000115,lung epithelium
sacral space,UBERON:0006075,sacral region of vertebral column**
seminal vesicles,UBERON:0000998,seminal vesicle
sinuses,UBERON:0001825,paranasal sinus**
skeletal muscles,UBERON:0014892,skeletal muscle organ
skin,UBERON:0000014,zone of skin
spiral valve,UBERON:0010016,spiral valve of intestine ** CHECKED**
stomach,UBERON:0000945,stomach
stomach wall,UBERON:0001167,wall of stomach
swim bladder,UBERON:0006860,swim bladder
thoracic cavity,UBERON:0002224,thoracic cavity
tissues,UBERON:0000479,tissue
tongue,UBERON:0001723,tongue
ureters,UBERON:0000056,ureter
urinary bladder,UBERON:0001255,urinary bladder
urinary tract,UBERON:0001008,renal system
viscera,UBERON:0002075,viscus
wall of kidneys,UBERON:0002113,kidney**
```

spiral valve is generally ambiguous, as this can refer to 3 structures. However, this seemed to be only affected in sharks/dogfish which makes it very likely it's the SV of the intestine.

bladder is ambiguous, but based on the source data (`Site: urinary tract; bladder`) this is the urinary bladder.

We don't have all wall-of-X terms pre-composed in uberon. I marked these `**` and went for the generic structure.

I didn't do these:

```
subcutaneous,
subcutaneous in fins,
subcutaneous in gills or head,
subcutaneous in head,
subcutaneous muscles,
subcutaneous muscles especially in head,
subcutaneous or skeletal muscles,
```

the plain adjective is ambiguous (maybe subcutaneous tissue aka hypoermis?)

For the others, your options are to have some kind of OWL class expression in globi TSVs (e.g. "subcutaneous tissue and part-of some fin"), have 2 values with some delimiter (weaker than OWL) or simply to choose the structure over the tissue or vice versal

**Comment by cmungall** [comment]
> I'm not seeing those terms in this dataset, @cmungall - are you scanning all of GloBI now?

they're in the supplemental data... sorry got obsessive

**Comment by cmungall** [comment]
For digestive gland, this seems to only be used with molluscs and crustaceans. In this context it's a syn for hepatopancreas.

So replace the generic  UBERON:0006925 "digestive gland" (which is a broad grouping) with one of:

 * [UBERON:0010264](http://purl.obolibrary.org/obo/UBERON_0010264) ! hepatopancreas
        * [UBERON:0010265](http://purl.obolibrary.org/obo/UBERON_0010265) ! mollusc hepatopancreas
         * [UBERON:0010266](http://purl.obolibrary.org/obo/UBERON_0010266) ! arthropod hepatopancreas

**Comment by jhammock** [comment]
UBERON:0010264 ! hepatopancreas, I think. I don't think either phylum is present; the downside of having the taxon IDs take care of ancestry is there's no convenient way for a compiler to eyeball for a target in a taxonomically mixed batch of records

**Comment by jhpoelen** [comment]
I found that including both name and ids hierarchies helps to mitigate this. Example from interactions.tsv 


sourceTaxonId | sourceTaxonIds | sourceTaxonName | sourceTaxonRank | sourceTaxonPathNames | sourceTaxonPathIds | sourceTaxonPathRankNames
-- | -- | -- | -- | -- | -- | --
EOL:1180140 | EOL:1180140 \| OTT:799633 \| GBIF:2439118 \| IRMNG:10226997 \| ITIS:633362 \| NCBI:218838 | Sigmodontomys alfari | Species | Animalia \| Chordata \| Mammalia \| Rodentia \| Muridae \| Sigmodontomys \| Sigmodontomys alfari | EOL:1 \| EOL:694 \| EOL:1642 \| EOL:8677 \| EOL:8698 \| EOL:111336 \| EOL:1180140 | kingdom \| phylum \| class \| order \| family \| genus \| species
EOL:328447 | EOL:328447 \| OTT:271571 \| GBIF:2439270 \| IRMNG:10200291 \| ITIS:180362 \| INAT_TAXON:44575 \| NCBI:10117 | Rattus rattus | Species | Animalia \| Chordata \| Mammalia \| Rodentia \| Muridae \| Rattus \| Rattus rattus | EOL:1 \| EOL:694 \| EOL:1642 \| EOL:8677 \| EOL:8698 \| EOL:42343 \| EOL:328447 | kingdom \| phylum \| class \| order \| family \| genus \| species
EOL:4461296 | EOL:4461296 \| OTT:370184 \| NCBI:548537 | Zygodontomys microtinus | Species | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Deuterostomia \| Chordata \| Craniata \| Vertebrata \| Gnathostomata \| Teleostomi \| Euteleostomi \| Sarcopterygii \| Dipnotetrapodomorpha \| Tetrapoda \| Amniota \| Mammalia \| Theria \| Eutheria \| Boreoeutheria \| Euarchontoglires \| Glires \| Rodentia \| Sciurognathi \| Muroidea \| Cricetidae \| Sigmodontinae \| Zygodontomys \| Zygodontomys microtinus | EOL:6061725 \| EOL:2908256 \| EOL:2910700 \| EOL:1 \| EOL:10380067 \| EOL:3014411 \| EOL:8814528 \| EOL:694 \| EOL:5004126 \| EOL:2774383 \| EOL:12094272 \| EOL:4656087 \| EOL:10459961 \| EOL:8909 \| EOL:40072735 \| EOL:4712200 \| EOL:3014446 \| EOL:1642 \| EOL:57446 \| EOL:2844801 \| EOL:32005829 \| EOL:40107874 \| EOL:4530224 \| EOL:8677 \| EOL:2846678 \| EOL:4468899 \| EOL:2921042 \| EOL:2848007 \| EOL:111343 \| EOL:4461296 | \| superkingdom \|  \| kingdom \|  \|  \|  \| phylum \| subphylum \|  \| superclass \|  \|  \|  \|  \|  \|  \| class \|  \|  \|  \| superorder \|  \| order \| suborder \|  \| family \| subfamily \| genus \| species
EOL:328601 | EOL:328601 \| OTT:348031 \| GBIF:2433536 \| IRMNG:10452653 \| ITIS:180579 \| INAT_TAXON:41670 \| NCBI:9651 | Nasua nasua | Species | Animalia \| Chordata \| Mammalia \| Carnivora \| Procyonidae \| Nasua \| Nasua nasua | EOL:1 \| EOL:694 \| EOL:1642 \| EOL:7662 \| EOL:7665 \| EOL:14190 \| EOL:328601 | kingdom \| phylum \| class \| order \| family \| genus \| species
EOL:328504 | EOL:328504 \| OTT:919176 \| GBIF:2439920 \| IRMNG:10939366 \| ITIS:552536 \| INAT_TAXON:42649 \| NCBI:9268 | Didelphis marsupialis | Species | Animalia \| Chordata \| Mammalia \| Didelphimorphia \| Didelphidae \| Didelphis \| Didelphis marsupialis | EOL:1 \| EOL:694 \| EOL:1642 \| EOL:7621 \| EOL:7622 \| EOL:34779 \| EOL:328504 | kingdom \| phylum \| class \| order \| family \| genus \| species
EOL:327955 | EOL:327955 \| OTT:770315 \| GBIF:2436436 \| IRMNG:10857762 \| NCBI:741158 \| ITIS:180092 \| NCBI:9606 | Homo sapiens | Species | Animalia \| Bilateria \| Deuterostomia \| Chordata \| Vertebrata \| Gnathostomata \| Tetrapoda \| Mammalia \| Theria \| Eutheria \| Primates \| Haplorrhini \| Simiiformes \| Hominoidea \| Hominidae \| Homininae \| Homo \| Homo sapiens | EOL:1 \| EOL:3014411 \| EOL:8814528 \| EOL:694 \| EOL:2774383 \| EOL:12094272 \| EOL:4712200 \| EOL:1642 \| EOL:57446 \| EOL:2844801 \| EOL:1645 \| EOL:10487985 \| EOL:10509493 \| EOL:4529848 \| EOL:1653 \| EOL:10551052 \| EOL:42268 \| EOL:327955 | kingdom \| subkingdom \| infrakingdom \| division \| subdivision \| infraphylum \| superclass \| class \| subclass \| infraclass \| order \| suborder \| infraorder \| superfamily \| family \| subfamily \| genus \| species
EOL:313735 | EOL:313735 \| OTT:376988 \| GBIF:5219666 \| IRMNG:10683583 \| ITIS:632427 \| INAT_TAXON:46010 \| NCBI:226870 | Sciurus granatensis | Species | Animalia \| Chordata \| Mammalia \| Rodentia \| Sciuridae \| Sciurus \| Sciurus granatensis | EOL:1 \| EOL:694 \| EOL:1642 \| EOL:8677 \| EOL:8703 \| EOL:34612 \| EOL:313735 | kingdom \| phylum \| class \| order \| family \| genus \| species
EOL:313735 | EOL:313735 \| OTT:376988 \| GBIF:5219666 \| IRMNG:10683583 \| ITIS:632427 \| INAT_TAXON:46010 \| NCBI:226870 | Sciurus granatensis | Species | Animalia \| Chordata \| Mammalia \| Rodentia \| Sciuridae \| Sciurus \| Sciurus granatensis | EOL:1 \| EOL:694 \| EOL:1642 \| EOL:8677 \| EOL:8703 \| EOL:34612 \| EOL:313735 | kingdom \| phylum \| class \| order \| family \| genus \| species
EOL:313735 | EOL:313735 \| OTT:376988 \| GBIF:5219666 \| IRMNG:10683583 \| ITIS:632427 \| INAT_TAXON:46010 \| NCBI:226870 | Sciurus granatensis | Species | Animalia \| Chordata \| Mammalia \| Rodentia \| Sciuridae \| Sciurus \| Sciurus granatensis | EOL:1 \| EOL:694 \| EOL:1642 \| EOL:8677 \| EOL:8703 \| EOL:34612 \| EOL:313735 | kingdom \| phylum \| class \| order \| family \| genus \| species

**Comment by dbenesh82** [comment]
Thanks all! I'm glad to see this parasite database going into globi. I'm more biologist than programmer, so I apologize that the data were not more easily mappable to existing ontologies.

I looked over the [interactions.tsv](https://github.com/millerse/Benesh-et-al-2017/blob/master/interactions.tsv) file and have a few comments. First, a silly QC question. The published csv file has about ~8500 unique interactions whereas the tsv file is about 9000 rows. I assume this difference is the result of taxon mapping, but wanted to ask how it might have come up.

The interactionTypeName could be more specific 'endoparasite of' instead of 'parasite of'. The data is focused on endoparasitic worms. Also, some interactions could maybe be labelled with 'facultative parasite of'. The data include a column called 'Facultative', which indicates whether a host is facultative or obligate. However, this coding refers more to the stage of the parasites life cycle than a specific host interaction. For example, if a parasite has a three-host life cycle (i.e. infects three hosts in succession before reproducing) and the second host is facultative, then it can skip any of the second host species listed for the parasite (i.e. the stage is facultative, as opposed to a specific host species).

@cmungall respect for going through all the locations! All the mappings look fine, including spiral valve, bladder, and hepatopancreas. I see how subcutaneous is ambiguous. It refers to anything under the skin but not in an organ, so it could be skin tissue like hypodermis or muscle tissue. Thus, I am not sure how to best categorize these values. More broadly, I had no idea what the categories for LocationinHost would be when I started this data collection, so some are less specific than others. The only way to rectify this and make them 100% comparable is to go back through the original sources and find the most specific UBERON term for each case.

Stage, shape, and habitat ontologies are fine. Localities and dates could eventually be extracted from referenceSource, if one had a few months to go through all the sources...

The hosts in the dataset are also marked as 'typical' or 'atypical' (e.g. if the parasite rarely infects a host or does not develop in it). I don't know if there is a way in globi to mark interactions as typical or common.

Finally, after a few queries, I think there are two other parasite databases that are not included in globi: the [global mammal parasite database](www.mammalparasites.org) and the [host-parasite database](http://www.nhm.ac.uk/research-curation/scientific-resources/taxonomy-systematics/host-parasites/) hosted by the NHM in London. An [R interface](http://onlinelibrary.wiley.com/doi/10.1111/ecog.02131/abstract) to this latter database was recently published.

**Comment by jhammock** [comment]
using endoparasite is easy enough. @dbenesh82 , can you verify that the definition and context displayed at  http://purl.obolibrary.org/obo/RO_0002634 meet your needs? I just came from an ontology workshop and have discovered how easily definitions can be found incompatible...

**Comment by dbenesh82** [comment]
Yes @jhammock, endoparasite is more appropriate for the interactions in this dataset.

**Comment by millerse** [comment]
Okay everyone.  I have added the endoparasite link and the body terms to the sheet.

@dbenesh82 To your comment about the extra numbers:  You had multiple body locations in a single record (i.e. gut, body cavity, etc.).  I took each of those terms and made a single full record for each term.  That is where the records come from.

**Comment by jhpoelen** [comment]
@jhammock @dbenesh82 please let me know if your feedback has been addressed. If not, please holler. If so, I am going to close this issue.

**Comment by dbenesh82** [comment]
I'm happy with it. If I ever upgrade the database, e.g. with better LocationinHost values, I'll let you know.

**Comment by jhammock** [comment]
sorry I never chimed in; this looks great!
