### ISSUE TITLE
chalcid wasp interactions by John S. Noyes - http://www.nhm.ac.uk/our-science/data/chalcidoids/

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#312]
Mentioned by @seltmann .

**Comment by jhpoelen** [comment]
@edwbaker - are you familiar with chalcid wasp database work by your colleague John S. Noyes? I've heard that many species interactions are included and was wondering whether you are planning to include these into the NHM Interaction Bank.

**Comment by edwbaker** [comment]
Yes - I have them ready to go - although there is an issue uploading them to the Data Portal at present. I have asked the Data Portal team to take a look.

**Comment by edwbaker** [comment]
The issue is: https://github.com/NaturalHistoryMuseum/DataPortal/issues/69

The build will likely fail until this issue is resolved.

**Comment by jhpoelen** [comment]
Great to hear that. Is it correct that https://github.com/NaturalHistoryMuseum/DataPortal is a private repository? This would explain why I cannot see the issue you mentioned.

**Comment by edwbaker** [comment]
Oh - possibly. The issue has been fixed this morning to the data should now start to flow.

**Comment by edwbaker** [comment]
There appears to be an issue with the build - probably as the path to the required file has changed (new UUID) http://data.nhm.ac.uk/dataset/nhm-ib/resource/9f49865f-ca81-488e-8738-82c569fb562e

**Comment by jhpoelen** [comment]
@edwbaker Thanks for the update. I noticed that chalcid wasp interactions by John S. Noyes are now appearing on http://data.nhm.ac.uk/dataset/nhm-ib . 

@seltmann - Should just be a matter of time before the chalcid interactions propagate into GloBI.

**Comment by jhpoelen** [comment]
As far as I can tell, John S. Noyes - http://www.nhm.ac.uk/our-science/data/chalcidoids/ is now available through GloBI . See attached example of hosts of parasitic wasp _Herodotia subatriventris_ 
http://www.globalbioticinteractions.org/?interactionType=parasiteOf&sourceTaxon=Herodotia%20subatriventris
![screenshot from 2017-09-09 09-30-41](https://user-images.githubusercontent.com/1084872/30241959-eebd8180-9541-11e7-828b-2f4de788024f.png)

@seltmann thanks for the pointer

@edwbaker thanks for making dataset available through NHM Interactions Bank.
