### ISSUE TITLE
Global Mammal Parasite Database at http://www.mammalparasites.org

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#315]
in https://github.com/jhpoelen/eol-globi-data/issues/305#issuecomment-330798999 @dbenesh82 suggested to add Global Mammal Parasite Database at http://www.mammalparasites.org .

**Comment by jhpoelen** [comment]
@millerse In case you didn't see, Please note http://gmpd.nunn-lab.org/Databases/useinfo.htm - they'd like to make sure to know how their data is used by sending a note of use.

**Comment by millerse** [comment]
@jhpoelen Sure.

**Comment by jhpoelen** [comment]
duplicate of #374
