### ISSUE TITLE
post open source licenses so that reviewers can find it

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#317]
GloBI is open source and uses GPLv3 see  https://github.com/jhpoelen/eol-globi-data/#licenses. Some java libraries use MIT.

@derele shared that a reviewer thought that GloBI was *not* open source.

**Comment by derele** [comment]
In my opionion www.globalbioticinteractions.org is most visible. Licencing would be most visibly included/linked there. Best as a main node in the navigation or at least under the "about". 

Reviewers have littel time to search and rather won't look at a github readme page after a google search, but were able to find licences under "about" for [open tree of life](opentreeoflife.org).

**Comment by jhpoelen** [comment]
I've updated the about page to emphasize the open-ness of GloBI:

-----
What is GloBI?

Global Biotic Interactions (GloBI) provides open access to species interaction data (e.g., predator-prey, pollinator-plant, pathogen-host, parasite-host) by combining existing open datasets using open source software.
----
Also, I've added a footer : 

----
Global Biotic Interactions is an open service providing open data using open source software.
----

@derele please free to comment / re-open this issue if you have alternative ideas on how to make the openness of GloBI more explicit for hurried reviewers/visitors.

**Comment by derele** [comment]
Issue solved. Thanks!
