### ISSUE TITLE
HTTPS certificate is invalid

### ISSUE THREAD

**Issue by timrobertson100** [jhpoelen/eol-globi-data#319]
https://www.globalbioticinteractions.org/ is not deployed with a valid certificate but needs to be.

**Comment by jhpoelen** [comment]
Good point! The site is now deployed using github pages and they don't seem to support https for custom domain. Will have a look into alternatives. See https://github.com/isaacs/github/issues/156 .

**Comment by jhpoelen** [comment]
I just setup cloudflare and waiting for name server settings to propagate.

**Comment by jhpoelen** [comment]
@timrobertson100 It seems that https://globalbioticinteractions.org is working ok now (see screenshot). Please confirm by closing this issue.

![screenshot from 2017-10-10 08-48-17](https://user-images.githubusercontent.com/1084872/31396292-ddc16266-ad97-11e7-85c2-f994c81713e7.png)

**Comment by timrobertson100** [comment]
Looks good to me. Thanks
