### ISSUE TITLE
Nordic Saproxylic Database

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#320]
As suggested by @dschigel and @dagendresen .

See https://github.com/globalbioticinteractions/saproxylic for work in progress.

**Comment by jhpoelen** [comment]
@dschigel @dagendresen - just wrote a first pass at supporting the saproxylic dataset. Some summary statistics about 1346 unique taxon names (see attached) and about 25k interactions (see https://travis-ci.org/globalbioticinteractions/saproxylic/builds/287142386#L642). Note that roles A->B and B->A are counted separately, so more like 25k/2 ~ 12k interactions). I'd expect 16k based on counting rows in https://github.com/globalbioticinteractions/saproxylic/blob/master/sx_txt/SX_Association.txt .
25k interactions (see https://travis-ci.org/globalbioticinteractions/saproxylic/builds/287142386#L642). Note that roles A->B and B->A are counted separately, so more like 25k/2 ~ 12k interactions). I'd expect 16k based on counting rows in https://github.com/globalbioticinteractions/saproxylic/blob/master/sx_txt/SX_Association.txt .

[aproxylic_names.txt](https://github.com/jhpoelen/eol-globi-data/files/1380062/aproxylic_names.txt)

Please open issues/discussions on this datasets here - github.com/globalbioticinteractions/saproxylic/issues

**Comment by dschigel** [comment]
Hi Jorrit,

Thanks for working on it. I found some scary black screens following your links but if find the result looks reassuring to you, I am happy, too. I don’t remember the metrics of the original database, so can’t compare.

Many thanks.
Regards,

Dmitry Schigel

**Comment by jhpoelen** [comment]
Nordic Saproxylic Database is now indexed/searchable through GloBI . See attached screenshot and 

https://www.globalbioticinteractions.org/?accordingTo=globi:globalbioticinteractions/saproxylic

![screenshot from 2017-10-23 11-59-52](https://user-images.githubusercontent.com/1084872/31885822-bb6dd576-b7e9-11e7-953e-7da99be6e671.png)

**Comment by dschigel** [comment]
Thanks Jorrit, 

Nice to see the db coming back to life renewed. I did a quick check with beetle genus Cis, which is supposed to breed & eat all kinds of wood fungi, but a lot of those are supposedly linked to some plant https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fsaproxylic&interactionType=interactsWith&targetTaxon=Cis. I wonder, if there is something wrong in source data, or this is a new bug? Don't remember such an issue when we the db was online  @dagendresen, @emeyke

**Comment by jhpoelen** [comment]
A quick note (I am traveling) - just had a glance at the data interface behind https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fsaproxylic&interactionType=interactsWith&targetTaxon=Cis at https://api.globalbioticinteractions.org/interaction.tsv?accordingTo=globi%3Aglobalbioticinteractions%2Fsaproxylic&interactionType=interactsWith&targetTaxon=Cis

and did find some fungi - 


source_taxon_external_id | source_taxon_name | source_taxon_path | source_specimen_life_stage | source_specimen_basis_of_record | interaction_type | target_taxon_external_id | target_taxon_name | target_taxon_path
-- | -- | -- | -- | -- | -- | -- | -- | --
NBN:NHMSYS0001482398 | Fomitopsis pinicola | Biota \| Fungi \| Basidiomycota \| Agaricomycotina \| Agaricomycetes \| Agaricomycetidae \| Polyporales \| Fomitopsidaceae \| Fomitopsis \| Fomitopsis pinicola |   |   | eatenBy | EOL:3487886 | Cis glabratus | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis glabratus
NBN:NHMSYS0001482398 | Fomitopsis pinicola | Biota \| Fungi \| Basidiomycota \| Agaricomycotina \| Agaricomycetes \| Agaricomycetidae \| Polyporales \| Fomitopsidaceae \| Fomitopsis \| Fomitopsis pinicola |   |   | eats | EOL:3487886 | Cis glabratus | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis glabratus
NBN:NHMSYS0000461247 | Picea abies | Biota \| Plantae \| Tracheophyta \| Pinopsida \| Pinales \| Pinaceae \| Picea \| Picea abies |   |   | eatenBy | no:match | Cis quadridens |  
NBN:NHMSYS0000461247 | Picea abies | Biota \| Plantae \| Tracheophyta \| Pinopsida \| Pinales \| Pinaceae \| Picea \| Picea abies |   |   | hostOf | no:match | Cis quadridens |  
NBN:NHMSYS0001482398 | Fomitopsis pinicola | Biota \| Fungi \| Basidiomycota \| Agaricomycotina \| Agaricomycetes \| Agaricomycetidae \| Polyporales \| Fomitopsidaceae \| Fomitopsis \| Fomitopsis pinicola |   |   | eatenBy | no:match | Cis quadridens |  
NBN:NHMSYS0001482398 | Fomitopsis pinicola | Biota \| Fungi \| Basidiomycota \| Agaricomycotina \| Agaricomycetes \| Agaricomycetidae \| Polyporales \| Fomitopsidaceae \| Fomitopsis \| Fomitopsis pinicola |   |   | eats | no:match | Cis quadridens |  
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | EOL:3270112 | Cis jacquemartii | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis jacquemartii
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | EOL:3270112 | Cis jacquemartii | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis jacquemartii
NBN:NHMSYS0000461247 | Picea abies | Biota \| Plantae \| Tracheophyta \| Pinopsida \| Pinales \| Pinaceae \| Picea \| Picea abies |   |   | eatenBy | EOL:3487886 | Cis glabratus | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis glabratus
NBN:NHMSYS0000461247 | Picea abies | Biota \| Plantae \| Tracheophyta \| Pinopsida \| Pinales \| Pinaceae \| Picea \| Picea abies |   |   | hostOf | EOL:3487886 | Cis glabratus | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis glabratus
EOL:1017400 | Fomes fomentarius | Fungi \| Basidiomycota \| Agaricomycetes \| Polyporales \| Polyporaceae \| Fomes \| Fomes fomentarius |   |   | eatenBy | EOL:3270112 | Cis jacquemartii | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis jacquemartii
EOL:1017400 | Fomes fomentarius | Fungi \| Basidiomycota \| Agaricomycetes \| Polyporales \| Polyporaceae \| Fomes \| Fomes fomentarius |   |   | eats | EOL:3270112 | Cis jacquemartii | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis jacquemartii
NBN:NHMSYS0001493153 | Phellinus pini | Basidiomycota \| Agaricomycetes \| Hymenochaetales \| Hymenochaetaceae \| Phellinus \| Phellinus pini |   |   | eatenBy | no:match | Cis quadridens |  
NBN:NHMSYS0001493153 | Phellinus pini | Basidiomycota \| Agaricomycetes \| Hymenochaetales \| Hymenochaetaceae \| Phellinus \| Phellinus pini |   |   | eats | no:match | Cis quadridens |  
EOL:1017400 | Fomes fomentarius | Fungi \| Basidiomycota \| Agaricomycetes \| Polyporales \| Polyporaceae \| Fomes \| Fomes fomentarius |   |   | eatenBy | EOL:3487884 | Cis lineatocribratus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis lineatocribratus
EOL:1017400 | Fomes fomentarius | Fungi \| Basidiomycota \| Agaricomycetes \| Polyporales \| Polyporaceae \| Fomes \| Fomes fomentarius |   |   | eats | EOL:3487884 | Cis lineatocribratus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis lineatocribratus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | NBN:NHMSYS0020151730 | Cis micans | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis micans
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | NBN:NHMSYS0020151730 | Cis micans | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis micans
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | NBN:NBNSYS0000024775 | Cis festivus | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis festivus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | NBN:NBNSYS0000024775 | Cis festivus | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis festivus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | no:match | Cis rugulosus |  
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | no:match | Cis rugulosus |  
ITIS:19478 | Betula | Plantae \| Viridiplantae \| Streptophyta \| Embryophyta \| Tracheophyta \| Spermatophytina \| Magnoliopsida \| Rosanae \| Fagales \| Betulaceae \| Betula |   |   | eatenBy | EOL:3270114 | Cis fagi | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis fagi
ITIS:19478 | Betula | Plantae \| Viridiplantae \| Streptophyta \| Embryophyta \| Tracheophyta \| Spermatophytina \| Magnoliopsida \| Rosanae \| Fagales \| Betulaceae \| Betula |   |   | hostOf | EOL:3270114 | Cis fagi | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis fagi
no:match | Coniferous |   |   |   | eatenBy | EOL:3270113 | Cis dentatus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis dentatus
no:match | Coniferous |   |   |   | hostOf | EOL:3270113 | Cis dentatus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis dentatus
ITIS:19276 | Quercus | Plantae \| Viridiplantae \| Streptophyta \| Embryophyta \| Tracheophyta \| Spermatophytina \| Magnoliopsida \| Rosanae \| Fagales \| Fagaceae \| Quercus |   |   | eatenBy | NBN:NBNSYS0000024778 | Cis bidentatus | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis bidentatus
ITIS:19276 | Quercus | Plantae \| Viridiplantae \| Streptophyta \| Embryophyta \| Tracheophyta \| Spermatophytina \| Magnoliopsida \| Rosanae \| Fagales \| Fagaceae \| Quercus |   |   | hostOf | NBN:NBNSYS0000024778 | Cis bidentatus | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis bidentatus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | EOL:3487888 | Cis comptus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis comptus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | EOL:3487888 | Cis comptus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis comptus
ITIS:19478 | Betula | Plantae \| Viridiplantae \| Streptophyta \| Embryophyta \| Tracheophyta \| Spermatophytina \| Magnoliopsida \| Rosanae \| Fagales \| Betulaceae \| Betula |   |   | eatenBy | EOL:3487885 | Cis castaneus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis castaneus
ITIS:19478 | Betula | Plantae \| Viridiplantae \| Streptophyta \| Embryophyta \| Tracheophyta \| Spermatophytina \| Magnoliopsida \| Rosanae \| Fagales \| Betulaceae \| Betula |   |   | hostOf | EOL:3487885 | Cis castaneus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis castaneus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | no:match | Cis alter |  
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | no:match | Cis alter |  
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | NBN:NBNSYS0000024778 | Cis bidentatus | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis bidentatus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | NBN:NBNSYS0000024778 | Cis bidentatus | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis bidentatus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | NBN:NBNSYS0000024780 | Cis boleti | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis boleti
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | NBN:NBNSYS0000024780 | Cis boleti | Biota \| Animalia \| Arthropoda \| Hexapoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis boleti
no:match | Coniferous |   |   |   | eatenBy | EOL:3487883 | Cis punctulatus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis punctulatus
no:match | Coniferous |   |   |   | hostOf | EOL:3487883 | Cis punctulatus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis punctulatus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | EOL:3487885 | Cis castaneus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis castaneus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | EOL:3487885 | Cis castaneus | Animalia \| Arthropoda \| Insecta \| Coleoptera \| Ciidae \| Cis \| Cis castaneus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | eatenBy | EOL:3270111 | Cis hispidus | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis hispidus
EOL:5050265 | Laserpitium latifolium | Plantae \| Tracheophyta \| Magnoliopsida \| Apiales \| Apiaceae \| Laserpitium \| Laserpitium latifolium |   |   | hostOf | EOL:3270111 | Cis hispidus | Cellular organisms \| Eukaryota \| Opisthokonta \| Metazoa \| Eumetazoa \| Bilateria \| Protostomia \| Ecdysozoa \| Panarthropoda \| Arthropoda \| Mandibulata \| Pancrustacea \| Hexapoda \| Insecta \| Dicondylia \| Pterygota \| Neoptera \| Endopterygota \| Coleoptera \| Polyphaga \| Cucujiformia \| Tenebrionoidea \| Ciidae \| Ciinae \| Cis \| Cis hispidus
