### ISSUE TITLE
Suspicious Chicken Issue

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#327]
See https://github.com/jhpoelen/eol-globi-data/issues/324#issuecomment-343632578 

That is odd. . . here's the proof https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Flupinus-nipomensis-interactions-2017&interactionType=interactsWith&sourceTaxon=Gallus that there's actually a chicken visiting a flower of Lupinus nipomensis .

At first glance it seems that GloBI mapped "Aranae" to "Gallus domesticus". See [here](https://neo4j.globalbioticinteractions.org/webadmin/#/data/search/start%20dataset%20%3D%20node%3Adatasets(namespace%3D%22globalbioticinteractions%2Flupinus-nipomensis-interactions-2017%22)%0Amatch%20dataset%3C-%5B%3AIN_DATASET%5D-study-%5B%3ACOLLECTED%5D-%3Especimen-%5B%3ACLASSIFIED_AS%5D-taxon%2C%20specimen-%5B%3AORIGINALLY_DESCRIBED_AS%5D-%3EtaxonOrig%0Awhere%20taxon.name%20%3D~%20'Gallus.*'%0Areturn%20taxon.name%2C%20taxonOrig.name/) for query if you are interested. 

Thanks for noticing this and will have a look sooner rather than later.

![screenshot from 2017-11-10 19-30-54](https://user-images.githubusercontent.com/1084872/32685816-c15aaf1e-c64d-11e7-8e8e-74052865aadb.png)

**Comment by jhpoelen** [comment]
@nipomensis - it seems like the offering record is - 

ITIS:162438     Aranae  RO:0002622      visits flowers of       ITIS:516356     Lupinus nipomensis      GEONAMES:8105481        Phillips 66 Oil Refinery Mesa   35.038741       -120.579352  

Where the flower visitor is a bit odd ITIS:162438 does not seems to be affiliated with Aranae, but with some invalid name related to spiderfishes (see https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=162438#null) . Perhaps the data was meant to be Araneae (spiders) with [ITIS:82732](https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=82732#null) ? If so, please apply corrections and GloBI should pick it up next time is does the rounds.

This does leave the question why GloBI thought that Aranae were chickens. . . hoping to look into that also.

**Comment by jhpoelen** [comment]
Looks like many other suspicious chicken interactions exist. From https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Gallus%20domesticus

![screenshot from 2017-11-13 09-19-00](https://user-images.githubusercontent.com/1084872/32739085-bb1e4892-c853-11e7-88e3-8fdd434ce311.png)

**Comment by jhpoelen** [comment]
I found that due to a importer bug (see https://github.com/hurlbertlab/dietdatabase/issues/90) an identifier ```ITIS:unverified``` was introduced to the system. The chicken (_Gallus domesticus_) was the first to be assigned to this id, so all subsequence names with that same id were linked to _Gallus domesticus_ . On a related note: _Gallus domesticus_ does not appear in ITIS.

I've implemented a fix changed should propagate in a couple of days.

**Comment by seltmann** [comment]
Is this forever to be known as the "Suspicious Chicken Issue"?

**Comment by jhpoelen** [comment]
Yep

**Comment by ahhurlbert** [comment]
Glad to have contributed to (a nicer way of saying "caused") such a suspicious issue.

Oops!

We will address [hurlbertlab/dietdatabase#90](https://github.com/hurlbertlab/dietdatabase/issues/90) as suggested but might not get to it until next week or so.

**Comment by nipomensis** [comment]
Great! The persistent pervasive chicken!

**Comment by jhpoelen** [comment]
After changes propagated, the suspicious chicken interactions no longer seem to occur. For instance, https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Flupinus-nipomensis-interactions-2017&interactionType=interactsWith&sourceTaxon=Gallus now no longer lists any interactions. (see attached screenshot).

@nipomensis thanks for being patient, and please let me know if you find any other suspicious interactions. Also, please re-open or comment if the issue persists.

![screenshot from 2017-11-20 10-22-10](https://user-images.githubusercontent.com/1084872/33034476-d30a48a0-cddc-11e7-8722-4a95a3088788.png)

**Comment by nipomensis** [comment]
Great!! Thanks for helping! I wil double check and let you know.

Cheers

**Comment by nipomensis** [comment]
Hi Jorrit,

Was wondering, how can I add photos for organisms that don't have images on
GLOBI?

**Comment by jhpoelen** [comment]
GloBI uses images that are made available via http://eol.org . Suggest to use the encyclopedia of life to share images. 

PS. Am assuming that the chicken issue has been resolved.

**Comment by nipomensis** [comment]
Yes it Has! And great thanks I will get ok n that. I was sure what your
email we so I just responded to this thread, sorry

**Comment by jhpoelen** [comment]
no worries. Would it be helpful to have a GloBI mailing list or some sort of chat room for these kinds of questions?

**Comment by jhpoelen** [comment]
This way, others can chime in if they'd like

**Comment by jhammock** [comment]
Yes!  Since this ticket is not really the place for me to direct @nipomensis to inaturalist.org, in order to share images or data with EOL (and incidentally with various other data hubs)...

**Comment by jhpoelen** [comment]
Ok, please see https://github.com/jhpoelen/eol-globi-data/issues/329 . Open to suggestions.

**Comment by seltmann** [comment]
Hi @nipomensis, @jhpoelen, @jhammock 
Im trying not to make a world more work for @nipomensis, but I wonder if the route to go would be:
1. Add images to our collection database for the voucher specimens from the project. Its a symbiota portal (of course!)

2. I share all our stuff with EOL (and thus Globi).

The problem I see with this plan are specifically tying the images back to the interaction dataset nipomensis shared. Thing is, these are images of vouchers of the interaction. Not just any image of a species illustrating a species from the interaction.

I know I am late to the party on this...sorry for taking so long to respond!
