### ISSUE TITLE
slow query when searching for Animals interacting with Animals

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#330]
queries in the browser interfaces appear to run but return no results

**Comment by jhpoelen** [comment]
just now from https://www.globalbioticinteractions.org/?interactionType=eats&sourceTaxon=Enhydra%20lutris
![screenshot from 2017-12-20 15-24-52](https://user-images.githubusercontent.com/1084872/34233400-fbee2dca-e599-11e7-8af9-0cbe6034775b.png)

**Comment by jhpoelen** [comment]
Can you please send url?

**Comment by jhammock** [comment]
https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Animalia&targetTaxon=Animalia works but produces no results, which is surprising. 

When I opened the ticket, 
https://www.globalbioticinteractions.org/?interactionType=eats&sourceTaxon=Enhydra%20lutris had behaved the same once, but it works as expected now.

**Comment by jhpoelen** [comment]
Hmm. Animalia vs Animalia is an especially crunchy query.

**Comment by jhammock** [comment]
Is it the size or the complexity? Trying to be less taxing:

https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=diptera

Still no results

**Comment by jhammock** [comment]
ah, no, that completed; it just took a minute. I think I just need to get a sense of scale. For my edification, should 
https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Animalia

be less crunchy or more crunchy than 

https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Animalia&targetTaxon=Animalia

**Comment by jhpoelen** [comment]
thanks for reporting this . . . GloBI should definitely return quicker. Re-opening issue.

**Comment by jhpoelen** [comment]
And yes, https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Animalia&targetTaxon=Animalia is definitely crunchier than https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Animalia .

**Comment by jhpoelen** [comment]
@jhammock I've tweaked the queries a little. To make the Animalia <> Animalia query return faster, I've disabled the feature that orders the result by #233 frequency of occurrence. For queries with single taxon, the ordering is still applied. 

Please re-close the issue if you are able to get some results now.

**Comment by jhpoelen** [comment]
btw - thanks to your issue, most queries on https://globalbioticinteractions.org should be a lot faster now.

**Comment by jhammock** [comment]
Indeed, my crunchy queries appear in a few seconds now. Nice!
