### ISSUE TITLE
Not sure if new dataset linked to globi

### ISSUE THREAD

**Issue by fgabriel1891** [jhpoelen/eol-globi-data#336]
Hi @jhpoelen! 

I have uploaded a new [dataset](https://github.com/fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics) which I would like to be available at GloBi. However, I'm not sure If I did the integration steps correctly. 

For step 1, I tried to fork again the template dataset but I kept being sent to my [previous forked dataset](https://github.com/fgabriel1891/Plant-Frugivore-Interactions-SouthEastAsia). So I ended up cloning the template repository and commit/edit the new information. I linked the new GitHub repository already with Travis and Zenodo.  

Is it ok doing it this way?  Is the interaction information linked to GloBi? 

Thanks!!

**Comment by jhpoelen** [comment]
@fgabriel1891 just sent another pull request - the readme has to contain the text "globalbioticinteractions". Apparently, GitHub does not index links in README.md, so ```[GloBI](https://globalbioticinteractions.org)``` is not included when searching for "globalbioticinteractions".

**Comment by fgabriel1891** [comment]
Hi @jhpoelen, thanks for your pull request. I merged it already with the repository. However, I do not see the globi batch change nor my dataset in the GloBi status page. Should I wait or do you think there is some other issue? 

Thanks for all your help!

**Comment by jhpoelen** [comment]
Thanks for checking in - I just checked some logs, and found 

```
21:39:36,169  INFO StudyImporterForGitHubData:52 - importing github repo [fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics]...
21:39:36,404  INFO StudyImporterForGitHubData:56 - importing github repo [fgabriel1891/Palm-Frugivore_Interactions_Neo-Afrotropics] done.
```
which means that your new datasets is on it's way. Thanks for being patient ! If you have ideas or suggestions on how to make this process faster, please do share.

**Comment by fgabriel1891** [comment]
Nice of you to share the logs, I'll be more patient.  Thanks again @jhpoelen! I'll close the issue as soon the globi batch gets updated!

**Comment by jhpoelen** [comment]
@fgabriel1891 looks like your dataset has propagated. Please confirm. 
![screenshot from 2018-02-24 16-12-35](https://user-images.githubusercontent.com/1084872/36631770-f66ed0f8-197d-11e8-8cf1-9a2d3c6a7a3c.png)

**Comment by fgabriel1891** [comment]
@jhpoelen, Yes! I can find the dataset on GloBi! Appreciate your help!
