### ISSUE TITLE
Status page shows "No DOI" for data with zenodo DOIs

### ISSUE THREAD

**Issue by cboettig** [jhpoelen/eol-globi-data#337]
Not sure how common this is, but a quick example from the top that has a DOI: https://github.com/diatomsRcool/greenland_interactions

even though the status badge is red X: https://www.globalbioticinteractions.org/status.html.

For any data that lives on GitHub (e.g. has the travis build and the issues), why not just flip the Zenodo switch to at least have some more robust archive?  Is this an issue of ownership / maintainer (e.g. you don't want to do this on GitHub repos that are created by you rather than created by the original data depositor / maintainer?)

**Comment by jhpoelen** [comment]
@cboettig thanks for chiming in. Just checked the doi and found that the zenodo dataset is not yet part of the zenodo's Global Biotic Interactions community at https://zenodo.org/communities/globalbioticinteractions .

@diatomsRcool could you please request your dataset to be added to "Global Biotic Interactions" community?  Please holler if you need help doing this.

**Comment by jhpoelen** [comment]
You should be able to add an existing dataset by "edit > communities > add" in zenodo's web UI

**Comment by jhpoelen** [comment]
@diatomsRcool - any thoughts about publishing your dataset on Zenodo?

**Comment by diatomsRcool** [comment]
I have a vague memory of doing this. Maybe it didn't work or I got distracted or something.

**Comment by diatomsRcool** [comment]
OK, I'm in zenodo and I don't see where it says "edit"

**Comment by jhpoelen** [comment]
Thanks for the voice chat just now. One more thing:
After adding the citation in globi.json in github , please make a new release to trigger a Zenodo publication. Then, for each new release, you have to manually add the "global biotic interactions" community. A bit clunky for sure. Am trying to think of ways to make this process a little easier. If you have any thoughts, please let me know. Also, if you feel that some more documentation is needed for this Zenodo publication business, let me know where I should publish this such that your past self would have found it.

**Comment by jhpoelen** [comment]
Good point! 

From https://travis-ci.org/diatomsRcool/greenland_interactions/jobs/434666081#L488 , it looks like that some interaction types are unsupported (e.g., http://purl.obolibrary.org/obo/RO_0002472) . At first glance, this looks like one of those "smart" excel features where it increments number when you copy them.

**Comment by jhpoelen** [comment]
Also line 266 seems to not have any interaction data. Also github's table viewer is complaining about line 266, see https://github.com/diatomsRcool/greenland_interactions/blob/master/interactions.tsv (and attached screenshot). 
![screenshot from 2018-09-28 08-32-00](https://user-images.githubusercontent.com/1084872/46218246-01f0be80-c2f9-11e8-886b-a0b8ddf23a1b.png)

**Comment by diatomsRcool** [comment]
ok, I think this is done now. Please close the issue if all is well.

**Comment by jhpoelen** [comment]
Thanks for doing all the work and for being patient! I'll wait until the changes propagate to the status page. Hoping to close in a couple of days.

**Comment by jhpoelen** [comment]
https://github.com/diatomsRcool/greenland_interactions now shows up as having a Zenodo doi, because the publication was added to the Global Biotic Interactions community on Zenodo - see https://zenodo.org/communities/globalbioticinteractions/ .
