### ISSUE TITLE
GalapagosSeaLion-fish interactions 

### ISSUE THREAD

**Issue by fgabriel1891** [jhpoelen/eol-globi-data#354]
Hello @jhpoelen,

I am trying to upload a new small dataset of predator-prey interactions to GloBI. However, the build on TRAVIS fails, it seems is not picking up the changes and returns the following error:

> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
> The command "./resolve-names.sh ${TRAVIS_REPO_SLUG}" exited with 1.

I first forked the globi template dataset to my personal GitHub but later I moved it to my organization's repository. Does this has anything to do with the error I'm seeing?. Should I erase the repository and start a new one? [Here](https://github.com/NASUA/SeaLion-Fish_prey_interactions_Galapagos) the link to the interactions repository. 

Thanks for your help,  

All the best, 

Gabriel

**Comment by jhpoelen** [comment]
hey @fgabriel1891 - thanks for your message. The issue that you describe is related to an experimental features in which travis notifies GloBI of taxonomic names occurring in the dataset. I've disabled the feature until the infrastructure is a little more stable. Please re-run and confirm that the travis build works as expected.

**Comment by fgabriel1891** [comment]
Ok, I have rebuilt on TRAVIS. But it failed again. The log is somehow different now but I get the same error: 

>  The command "./resolve-names.sh ${TRAVIS_REPO_SLUG}" exited with 1.

I have to leave for a moment, but I'll try again in a couple of hours. 

Thanks again!

**Comment by jhpoelen** [comment]
Hmm. Interesting. It looks like some of the GitHub APIs are restricting access for some reason:

```
Caused by: java.io.IOException: failed to get [https://api.github.com/repos/NASUA/SeaLion-Fish_prey_interactions_Galapagos/commits]
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:122)
	at org.eol.globi.util.HttpUtil.getContent(HttpUtil.java:111)
	at org.eol.globi.service.GitHubUtil.httpGet(GitHubUtil.java:25)
	at org.eol.globi.service.GitHubUtil.lastCommitSHA(GitHubUtil.java:80)
	at org.eol.globi.service.DatasetFinderGitHubArchive.datasetFor(DatasetFinderGitHubArchive.java:11)
	... 10 more
Caused by: org.apache.http.client.HttpResponseException: Forbidden
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:67)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:120)
	... 14 more
```
Sorry about this. Hoping to provide a fix for this unexpected error in the GloBI travis check process.

**Comment by jhpoelen** [comment]
I simplified the check script a little more to avoid the github api . Please try again. Thanks for being patient.

**Comment by fgabriel1891** [comment]
I made new GitHub repo   ([here](https://github.com/NASUA/ZalophusPredatoryInteractions) ) with the same data, I erased the last one

But the build has passed! Will check the data availability on GlobI in a few days. 
Thanks @jhpoelen :)

**Comment by jhpoelen** [comment]
hey @fgabriel1891 - I just noticed an unexpected error in the GloBI ingestion process related to an outage of a jsonld resource which caused to halt the refreshes. I've reproduced and fixed the issue (see 6b87e670a092f5fee1e50968c283bad105a7f112 ) and restarted the re-index process. Apologies for the delay . . .

**Comment by fgabriel1891** [comment]
Hi @jhpoelen. No worries. I appreciate your efforts. Thanks again.

**Comment by jhpoelen** [comment]
Looks like your dataset made it through - https://www.globalbioticinteractions.org/?accordingTo=globi%3ANASUA%2FZalophusPredatoryInteractions&interactionType=interactsWith .

**Comment by jhpoelen** [comment]
Please note that your old dataset is cached in a GloBI archive, even through it disappeared from Github.

**Comment by fgabriel1891** [comment]
Nice! .... How could I erase the older one? I don't see it on my Travis account...

**Comment by jhpoelen** [comment]
I've removed the older one manually from the GloBI archive cache. Changes should propagate in a couple of days.
