### ISSUE TITLE
unexpected disagreement between geographic browser display and download

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#356]
For this search in the browser interface

https://www.globalbioticinteractions.org/browse/?bbox=-206.3671875%2C-69.65708627301174%2C235.89843749999997%2C73.82482034613932&interactionType=interactsWith&resultType=json&sourceTaxon=Arthropoda

The number of source and target taxa listed in the interface results display (804 and 925) differ from the numbers of taxa represented in the download, (10 and 952)

https://api.globalbioticinteractions.org/interaction.csv?type=csv&limit=4096&interactionType=interactsWith&bbox=-206.3671875%2C-69.65708627301174%2C235.89843749999997%2C73.82482034613932&sourceTaxon=Arthropoda&includeObservations=true&field=source_taxon_id&field=source_taxon_name&field=source_taxon_path&field=source_taxon_path_ids&field=source_specimen_life_stage_id&field=source_specimen_life_stage&field=source_specimen_physiological_state_id&field=source_specimen_physiological_state&field=source_specimen_body_part_id&field=source_specimen_body_part&field=interaction_type&field=target_taxon_id&field=target_taxon_name&field=target_taxon_path&field=target_taxon_path_ids&field=target_specimen_life_stage_id&field=target_specimen_physiological_state&field=target_specimen_physiological_state_id&field=target_specimen_physiological_state&field=target_specimen_body_part_id&field=target_specimen_body_part&field=latitude&field=longitude&field=study_citation&field=study_url&field=study_source_citation

**Comment by jhpoelen** [comment]
Thanks for sharing. I've downloaded the associated observations (see attached [interactions_download.zip](https://github.com/jhpoelen/eol-globi-data/files/2290803/interactions_download.zip)
) and noticed that the maximum number of 4096 records was reached. Since the browser displays the summary statistics on the taxon level and provides the download on the occurrence level, this would explain the unexpected difference between the display and the download. 

Also see #169 . 

Hoping to remove this limitation at some point. Now, you'd have to page through the results (see https://github.com/jhpoelen/eol-globi-data/wiki/API#pagination)  or use the bulk download and select only Arthropoda interactions using a filter/regex (see https://globalbioticinteractions.org). 

Just wondering - what is your use case?

**Comment by jhammock** [comment]
Ah, thanks. Of course, the 776 interactions is taxon combinations, not records. I'll want the geographic filter; I can paginate.

I was spot checking our GloBI resource on EOL against the source data, but I'm also hoping to compare EOL's summarized view, i.e.: interaction data at the taxon level for taxa we think are found in region X

eg: https://beta.eol.org/terms/search_results?utf8=%E2%9C%93&clade_name=Arthropoda&term_query%5Bclade_id%5D=164&pred_name=geographic+distribution+includes&term_query%5Bfilters_attributes%5D%5B0%5D%5Bpred_uri%5D=http%3A%2F%2Feol.org%2Fschema%2Fterms%2FPresent&term_query%5Bfilters_attributes%5D%5B0%5D%5Bop%5D=is_obj&obj_name=Australia&term_query%5Bfilters_attributes%5D%5B0%5D%5Bobj_uri%5D=http%3A%2F%2Fwww.geonames.org%2F2077456&pred_name=interacts+with&term_query%5Bfilters_attributes%5D%5B1%5D%5Bpred_uri%5D=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002437&term_query%5Bfilters_attributes%5D%5B1%5D%5Bop%5D=is_any&term_query%5Bresult_type%5D=taxa&commit=Search

with the geolocated occurrence-level view from the GloBI, summarized to taxon

eg: https://www.globalbioticinteractions.org/browse/?bbox=110.0390625%2C-44.087585028245165%2C155.0390625%2C-9.79567758282973&interactionType=interactsWith&resultType=json&sourceTaxon=Arthropoda

It's not quite apples to apples at this point, but we might expend some effort on it later. Additional lines of evidence to assess confidence of our geographic records would be useful soon, for the data search.

**Comment by jhammock** [comment]
looks like it might be an old version, actually. You can always see it at https://opendata.eol.org/dataset/globi/resource/97da6a23-e577-4708-bfa1-a2180118702f

So currently, http://depot.globalbioticinteractions.org/release/org/eol/eol-globi-datasets/0.5/eol-globi-datasets-0.5-darwin-core-aggregated.tar.gz

should we be using https://depot.globalbioticinteractions.org/snapshot/target/eol-globi-datasets-1.0-SNAPSHOT-darwin-core-aggregated.zip

if we want the latest and greatest?

**Comment by jhpoelen** [comment]
Yep, https://depot.globalbioticinteractions.org/snapshot/target/eol-globi-datasets-1.0-SNAPSHOT-darwin-core-aggregated.zip is the latest and greatest.

**Comment by jhammock** [comment]
updated, thanks

**Comment by jhpoelen** [comment]
Nice! Looking at the resource page, I notice that the format says "TAR", whereas the current format is "ZIP". Is that an issue?

**Comment by jhammock** [comment]
oops- just a cosmetic one, for us; our harvester doesn't ask CKAN for that metadata. The assignment is automatic the first time a resource is loaded, but it doesn't check again if we change the resource...
