### ISSUE TITLE
gut contents, from iNaturalist

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#370]
I think so far these all come from one lionfish-guts-barcoding project. Apparently, lionfish have a wide diet...

https://www.inaturalist.org/observations?field:Found%20in%20Gut%20of%20(species)

**Comment by jhpoelen** [comment]
@jhammock cool! If you convince them to use a "taxon observation field", then they are included in GloBI automatically. It's only about 60 observations, so perhaps easier to add a taxon observation field manually. . . curious to hear your thoughts.

**Comment by jhpoelen** [comment]
Would be cool to see the overlap between https://www.globalbioticinteractions.org/?accordingTo=globi%3Ajhammock%2FLayman-and-Allgeier-Lionfish&interactionType=interactsWith and this one.

**Comment by jhpoelen** [comment]
btw - a taxon observation field is an observation field with data type "taxon" , see attached example from https://www.inaturalist.org/observation_fields/3011 : 

![screenshot from 2018-09-19 10-15-19](https://user-images.githubusercontent.com/1084872/45769686-337cd200-bbf5-11e8-9ae8-03894234882e.png)

**Comment by jhpoelen** [comment]
I've created a new observation field "found in gut of" with taxon data type at https://www.inaturalist.org/observation_fields/9674#activity_comment_2194130 and annotated a few of the observations in the hopes that the curators of the project will follow suit.

**Comment by jhpoelen** [comment]
@jhammock please feel free to re-open issue if you feel there's another actions we can take to incorporate these interesting data.
