### ISSUE TITLE
eol image urls broken

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#381]
As reported by @mjy - 

"Looks like your links
are broken- https://www.globalbioticinteractions.org/?interactionType=pollinates&sourceTaxon=Apis"

**Comment by jhpoelen** [comment]
The thumbnail link associate to Apis (bees) was retrieved via the EOL Api some time ago via http://eol.org/pages/104135 . It appears that the image at https://media.eol.org/content/2009/07/24/08/00620_98_68.jpg no longer exists. 

In trying to retrieve an up-to-date image using the EOL API using http://eol.org:80/api/pages/1.0/104135.json?images=1&videos=0&sounds=0&maps=0&text=0&iucn=false&subjects=overview&licenses=all&details=false&common_names=true&synonyms=false&references=false&taxonomy=true&format=json , no data objects containing images were returned.

@jhammock does the EOL API still support images? If so, please let me know how I can find an image related to Apis (bees).

**Comment by jhammock** [comment]
Yes, this looks like a bug. We were trying for full back compatibility, at least to recent versions; and our merry band of API testers haven't reported this one yet. 

https://eol.org/api/pages/1.0/104135.json?details=true&images_per_page=1
  does return an image. 

Any idea how long ago you last used our Pages services? I dimly recall a tough decision to require pagination, a couple of years ago.

**Comment by jhpoelen** [comment]
After digging into the code, I was able to uncover some things. 

First, the return object of https://eol.org/api/pages/1.0/104135.json?details=true&images_per_page=1 has changed. It used to be 

```json
{ "identifier" : "...",
  "taxonConcepts" : "...",
  "..." : "..."
}
```

however, now it is:

```json
{ "taxonConcept" : {
  "identifier" : "...",
  "taxonConcepts" : "...",
  "..." : "..."
  }
}
```

(more to follow)

**Comment by jhpoelen** [comment]
Secondly, the previously support call: 

http://eol.org:80/api/hierarchy_entries/1.0/6447487.json?common_names=false&synonyms=false&format=json 

Is now returning a http status code of 500, an error code.

**Comment by jhammock** [comment]
Bad news: hierarchy_entries is no longer supported. Use cases were rare and those queries will be better handled in the cypher service once we've got the alternate hierarchies in the graph. We'll also make an updated cross provider ID mapping data dump available at that point.

**Comment by jhpoelen** [comment]
Another issue appears to be that http://eol.org:80/api/search/1.0.xml?q=Actinopterygii&exact=true used to return something like:

```xml
<something>
 <entry></entry>
 <entry></entry>
</something>
```

however, currently, it looks like "entry" is called "result" : 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<hash>
  <totalResults type="integer">7</totalResults>
  <startIndex type="integer">1</startIndex>
  <itemsPerPage type="integer">50</itemsPerPage>
  <results type="array">
    <result>
      <id type="integer">1905</id>
      <title>Actinopterygii</title>
      <link>https://eol.org/pages/1905</link>
      <content>Actinopterygii; Actinopterygii ; ACTINOPTERYGII</content>
    </result>
    <result>
      <id type="integer">47056647</id>
      <title>unplaced extinct Actinopterygii</title>
      <link>https://eol.org/pages/47056647</link>
      <content>unplaced extinct Actinopterygii</content>
    </result>
    <result>
      <id type="integer">48957636</id>
      <title>Actinopterygii</title>
      <link>https://eol.org/pages/48957636</link>
      <content>Actinopterygii</content>
    </result>
    <result>
      <id type="integer">48859786</id>
      <title>ACTINOPTERYGII</title>
      <link>https://eol.org/pages/48859786</link>
      <content>ACTINOPTERYGII</content>
    </result>
    <result>
      <id type="integer">48957649</id>
      <title>Actinopterygii which</title>
      <link>https://eol.org/pages/48957649</link>
      <content>Actinopterygii which</content>
    </result>
  </results>
</hash>
```

**Comment by jhammock** [comment]
The other change,

{ "taxonConcept" : {
  "identifier" : "...",
  "taxonConcepts" : "...",
  "..." : "..."
  }
}

 sounds similar/analogous to a change made deliberately today in another service (data_objects) in response to a back compatibility problem reported by @hyanwong (Yan, correct me if I'm wrong) to *support* back compatibility. @jrice didn't really approve of the form, but it was the most recent one we had. Gents, any comment on this form in the Pages API?

@jhpoelen still wondering if you remember when your last use of the service was. It could be the form of the response went through changes during v2.

**Comment by jhpoelen** [comment]
Regarding supporting the hierarchies API - as you probably know, GloBI has been relying on that feature for quite some time as a work-around while waiting for a method more suitable for high throughput taxon matching applications. Luckily, I introduced the GloBI Taxon Graph to keep copies of hierarchies around (see https://doi.org/10.5281/zenodo.755513) to avoid heavily relying on APIs (this includes Cypher/SPARQL endpoints) to never change and stay around forever. 

However, I am still bummed that the hierarchies API is gone, because now, if I understand it correctly, I don't have any way to retrieve hierarchies from EOL without having to login with some token.

Anyways, thanks for listening / responding and keeping the API up and running. I hope my feedback is useful.

**Comment by jhpoelen** [comment]
Coming back to the original issue (the missing image) - 

Rather than generating a 404 not found, a 301 permanently moved is generated, however, no redirect information is provided where where the image move to. Could the missing images be a result of a misbehaving url rewrite/ redirect rule?  

```
$ curl --verbose -L https://media.eol.org/content/2009/07/24/08/00620_98_68.jpg
> GET /content/2009/07/24/08/00620_98_68.jpg HTTP/1.1
> Host: media.eol.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 20 Nov 2018 00:13:11 GMT
< Content-Length: 0
< Connection: keep-alive
< Server: Varnish
< X-Varnish: 20545634
< 
```

**Comment by jhpoelen** [comment]
from https://en.wikipedia.org/wiki/HTTP_301 - 
"The HTTP response status code 301 Moved Permanently is used for permanent URL redirection, meaning current links or records using the URL that the response is received for should be updated. The new URL should be provided in the Location field included with the response. The 301 redirect is considered a best practice for upgrading users from HTTP to HTTPS."

**Comment by jhammock** [comment]
Oops, no, that's certainly misleading. No claim of redirect was intended. The images were not migrated in but re-harvested; that was the only practical way to correct the poor taxon mapping in EOL v2. Arguably most of the image files are still available in EOL, but many are attached to different taxa now and we made no attempt to track them. Thanks for pointing that out!

**Comment by jhpoelen** [comment]
@jhammock as far as timing goes - I noticed that the GloBI image linker was pretty happy a couple of days ago, but was crashing a couple of days ago.

For example (dates are in central European time):
```
2018-11-18 13:44:21,998 [main] INFO  org.eol.globi.tool.LinkUtil - Linker started...
2018-11-18 13:44:24,879 [main] WARN  org.eol.globi.tool.ImageLinker - failed to lookup externalId [
ITIS:117297]
java.io.IOException: org.eol.globi.service.PropertyEnricherException: failed to lookup [http://eol.
org/api/search_by_provider/1.0/117297.json?hierarchy_id=903]: http status [500]   
        at org.eol.globi.service.EOLTaxonImageService.lookupImageForExternalId(EOLTaxonImageService
.java:22)
```

**Comment by jhammock** [comment]
One more news item that may also be helpful: three hierarchy_entries users have expressed pain in two days, so it's back on the to do list to support the old version- it might take us til Monday, sorry!

We do hope people will migrate to the cypher service eventually; it isn't our plan to continue requiring keys once we're steady on our v3 feet.

**Comment by jhpoelen** [comment]
The original issue has been fixed by removing all EOL thumbnail urls from GloBI Taxon Graph and disabling an automated image linking process. Instead, thumbnail are now retrieved via an ad-hoc wikidata lookup. Am still hoping to access the wealth of image data that EOL has to offer once the access methods stabilize. 

Perhaps an idea would be to have an endpoint for taxon pages that would serve a thumbnail by EOL id or offer a 404 when none is available. Another idea is to publish a flat file with an thumbnail lookup associated with page ids. 

@jhammock thanks for chiming in!
