### ISSUE TITLE
Otter-salmon relationship is reversed

### ISSUE THREAD

**Issue by Klisz** [jhpoelen/eol-globi-data#389]
GloBI currently cites Carss, Kruuk & Conroy's "Predation on adult Atlantic salmon, _Salmo salar_ L., by otters, _Lutra lutra_ (L.), within the River Dee system" (J. Fish Biol. 37(6):935-944) as support for _S. salar_ preying on _L. lutra_ - however, the article is actually the exact opposite, about the otters preying on the salmon.

**Comment by jhpoelen** [comment]
@Klisz thank you very much for sharing this issue. I'll check the provenance of GloBI's dubious claim otters are preyed upon by Atlantic salmon shorty.

**Comment by jhpoelen** [comment]
On checking the suspicious otter-salmon relationship with https://www.globalbioticinteractions.org/?interactionType=preyedUponBy&sourceTaxon=Lutra%20lutra , I was able to trace the source of the interaction claim to https://www.sealifebase.ca/TrophicEco/PredatorList.php?ID=71068&GenusName=Lutra&SpeciesName=lutra , a data record published by SeaLifeBase with associated predator summary at https://www.sealifebase.ca/TrophicEco/PredatorSummary.php?vpredatstage=juv.%2Fadults&genusname=Lutra&speciesname=lutra&vstockcode=9810&vpreystage=juv.%2Fadults&vpredatorgroup=Salmonidae&vpredatorname=Salmo+salar (see attached screenshots).

@Dengaloo @FIN-JBarile Deng, Skit - please confirm that the referred record is one that should be corrected in sealifebase. 

@Klisz I've sent a link to this issue to the sealifebase contributor via email using information at  https://www.sealifebase.ca/collaborators/CollaboratorSummary.php?id=1 . 

![screenshot from 2019-02-22 06-58-25](https://user-images.githubusercontent.com/1084872/53251018-84936500-3670-11e9-8b99-1b43db923c4d.png)
![screenshot from 2019-02-22 07-08-22](https://user-images.githubusercontent.com/1084872/53251165-e3f17500-3670-11e9-8f6c-b58b0ad4acac.png)

**Comment by jhpoelen** [comment]
@Klisz While SeaLifeBase folks are working on reviewer their association records, I've created a dataset https://github.com/globalbioticinteractions/refuted-interaction-data with your (refuted) claims based on ```Carss, D.N., H. Kruuk and J.W.H. Conroy 1990 Predation on adult Atlantic salmon, Salmo salar L., by otters, Lutra lutra (L.), within the River Dee system, Aberdeenshire, Scotland. J. Fish Biol. 37(6):935-944.``` at https://doi.org/10.1111/j.1095-8649.1990.tb03597.x

I've invited you as a collaborator so that your contribution can be attributed. Also, please feel free to share/ update the citation with your name at https://github.com/globalbioticinteractions/refuted-interaction-data/blob/master/globi.json of this datasets as you'd like it to appear in future references.

**Comment by jhpoelen** [comment]
Now, when folks search for predators of Otters via https://www.globalbioticinteractions.org/?interactionType=preyedUponBy&sourceTaxon=Lutra%20lutra a refuting claim appears alongside of the (incorrect) claim by Sealifebase that Salmon eat otters. Also see attached screenshot. This should give the SeaLifeBase some time to update their records while noting @Klisz refuting claim. 

@Klisz Please let me know how you'd like to be attributed. 

![screenshot from 2019-03-06 09-35-03](https://user-images.githubusercontent.com/1084872/53901178-2a40bf80-3ff3-11e9-9d78-fef7e8cbae16.png)
