### ISSUE TITLE
need to revisit EOL id mapping script

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#403]
Need to revisit http://doi.org/10.5281/zenodo.1495266 guided by observations below. Possible over greedy sed matchers.

------

xxxx

Here are five from the "Map" patch file:

https://eol.org/pages/39058
https://eol.org/pages/33972
https://eol.org/pages/254283
https://eol.org/pages/28884
https://eol.org/pages/629094

And five from the "Cache" patch file:

https://eol.org/pages/590792
https://eol.org/pages/590795
https://eol.org/pages/590796
https://eol.org/pages/590798
https://eol.org/pages/590799

All of these appear as something like "EOL_V2:590796" in one of the patch files, yet all resolve at EOL without a 500 error. 
....
XXX 

Can you please provide some of the ids that did resolve but were marked
as EOLv2?

If memory serves me, I used a copy of the "dynamic taxon hierarchy" that
was used for V3 and marked all page ids that were *not* included in that
hierarchy.

I got the hierarchy from:

  "EOL Dynamic Hierarchy with landmark taxa",
https://opendata.eol.org/dataset/b6bb0c9e-681f-4656-b6de-39aa3a82f2de/resource/bac4e11c-28ab-4038-9947-02d9f1b0329f/download/eoldynamichierarchywithlandmarks.zip

with
hash://sha256/6a26e52adf1518eebac3556c05370396251ca3ec6a9059694b91a2549fc4013a
.
Accessed on 2018-11-21 .

thx,

XXX

> XXX,
> You wrote:
>
> "...all no longer supported EOL ids were marked in taxonMap.tsv.gz and taxonCache.tsv.gz by replacing the prefix "EOL:" to "EOL_V2:". Patch files were then generated using the unix "diff" comment to document the changes between the original taxonMap/taxonCache files."
>
> Looking at the patch files themselves, I found quite a few IDs prefixed with "EOL_V2" that resolve just fine, so I assume that I am misunderstanding something.
>
> Is there a way to produce from those files just a simple list of EOL IDs that are no longer valid?  That is what I would need to clean up the EOL identifiers in BHL.  I assume there is no way to map invalid IDs to replacement IDs?
>
> Thanks,
>
> XXX

**Comment by jhammock** [comment]
Hmm... We did update the Dynamic Hierarchy recently, and that may have retrieved some of the old mappings to v2. I know some effort was made in that direction. The DH versions are a little better organized now, in [an opendata dataset](https://opendata.eol.org/dataset/tram-807-808-809-810-dh-v1-1) If you rely on the CKAN API for the ["Active Version" data resource](https://opendata.eol.org/dataset/tram-807-808-809-810-dh-v1-1/resource/00adb47b-57ed-4f6b-8f66-83bfdb5120e8) you should be able to find the current one consistently. Note that the actual file url will continue to change; we've only managed to pin down the opendata resource address.

**Comment by jhpoelen** [comment]
hi @jhammock - I have spent some time preparing a patch to GloBI's taxon mappings and found eol page id 45500469 that generates an EOL page, but is not included in the "Active Version" of the EOL dynamic hierarchy taxonomy. Is this expected?

to reproduce:

```
$ curl https://editors.eol.org/other_files/DWH/TRAM-809/DH_v1_1.tar.gz > input/eol-dh.tar.gz 
$ cat input/eol-dh.tar.gz | gunzip | tar -xO ./taxon.tab | grep 45500469
```
resulted in zero matches, however, page https://eol.org/pages/45500469/ was rendered by EOL (see attached screenshot)

![Screenshot from 2019-08-16 12-13-08](https://user-images.githubusercontent.com/1084872/63192152-407d8d80-c01f-11e9-9fe4-93661ef59922.png)

**Comment by jhammock** [comment]
Interesting! Yes and no. There are quite a few EOL pages not included in the Dynamic Hierarchy; if a provider gives us a concept we can't map to one of ours, we give it a new page anyway. So for your purposes, the distinction may not matter.

However, this page is "behaving" as though it is in the DH. We expect non-DH pages to look like [this](https://eol.org/pages/52499829) - to have an "Unresolved name" warning at the top and not show the breadcrumb immediately. This one may have slipped through because it was recognized by the previous version of the DH. We'll investigate. Thanks!

**Comment by jhpoelen** [comment]
@jhammock I've labored to create a new version of the GloBI Taxon Graph using an versioned and automated patch procedure using the Dynamic Taxon Hierachy you provided. I imagine that other collaborators can use a similar method to keep up with the dynamics of EOL pages.

Poelen, Jorrit H. (2019). Global Biotic Interactions: Taxon Graph Patches (Version 0.3) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3371634
Poelen, Jorrit H. (2019). Global Biotic Interactions: Taxon Graph (Version 0.3.14) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3371645

Am happy to adopt a more suitable method when it is available.

**Comment by jhpoelen** [comment]
GloBI upgraded to 0.3.14 taxon graph via https://github.com/jhpoelen/eol-globi-data/commit/ad95b22059e54dd6984448a9aa545f333b03ffd0 . Changes should propagate in a couple of days.

**Comment by jhammock** [comment]
paging @hyanwong  - I wonder if @jhpoelen 's method overlaps at all with your needs for OneZoom
