### ISSUE TITLE
University of California Santa Barbara Invertebrate Zoology Collection

### ISSUE THREAD

**Issue by seltmann** [jhpoelen/eol-globi-data#405]
I would like to set up a repo from my Symbiota portal for biotic interactions. The darwin core archive is here:

https://symbiota.ccber.ucsb.edu:443/content/dwca/UCSB-IZC_DwC-A.zip

This is a Symbiota portal that is also snapshot to SCAN, but like many collections on SCAN, we are not managed directly on SCAN but our data is updated to SCAN periodically (snapshot collection).

The biotic interaction information is in the associatedTaxa field, primarily as free text.

**Comment by jhpoelen** [comment]
Thanks for sharing. 

At quick glance the following values are included associatedTaxa

```
Acmispon glaber col id: ENT118-2016-1
Acmispon glaber ENT118-2016-1
Arcostaphylos
Arctostaphylos
Arctostaphylos, S. Ridge Road, A. Wenner
Artemesia californica
Asclepias
Asclepius
Atriplex lenticularis
Atriplex lentiformis
Atriplex Lentiformis
Baccharis, Avena sp.
Baccharis pillularis
Baccharis piluaris, Avena sp.
Baccharis piluaris; Avena sp.
Baccharis pilularis
Baccharis pilularis and Avena sp
Baccharis salicifolia
Bacchatis pilularis
Brassica
Brassica campesterius
Brassica campestris
Brassica sp
Brassica sp.
Bromus diandra col id: ENT 118-2016-3
Bromus diandrus
Calandrinia menziesii
Calandrinia menzisii
Calochortus
Calyystegia macrostegia
Canothus
Cascada
centaurea star thistle
Centaurrea
Centaurrea star thistle
Centaurrea Star Thistle
Centaurre star thistle
Centaurre Star Thistle
Centromadia parryi subsp. australis
Centromadia parryi subsp. australis; Voucher: UCSB050026
Centromadia parryi subsp. australis: Voucher: UCSB050026
Collensia sp.
Collinsia (bartsiifolia?)
Collinsia sp
Coreopsis
Coreopsis gigantea
Dead Hickory
Diplacus aurentiacus
Distichlis spicata
Distichlis spicata, Salicornia virginica
Distichlis spicata; Salicornia virginicar
E. Californica
Elymus condensatus
Encelia californica
Encelia Californica; Voucher: UCSB049950
Erigogonum fasciculatum in bloom
erigonium
Erigonium
Eriodictyon flowers
Eriodictyon fls
Eriogonum
Eriogonum fasciculatum
Eriogonum fasciculatum in bloom
Eriogonum fasiculatum
Eriogonum giganteum
Eriogonum sp.
Eriophyllum confertiflorum
Eriophyllum confertiflorum; Voucher UCSB49946
Eschscholzia california
Eschscholzia californica
Eschscholzia californica: Voucher: UCSB049919
ex. Baccharis salicifolia
Ex. Brassica
Fagopyrm scrub
Fagopyrum
Fagopyrum sp.
fennel
Fennel
Ficus
Ficus macrophylla
Foeniculum
Formica
Fuchsia sp
Fuchsia sp.
Golden Yarrow
Gramineae
Grass
Helianthus californicus
Heteromeles
Heteromeles arbutifolia
Heterotheca grandiflora
Hirschfeldia incana
Hypochaeris radicata
In Distichlis spicata and Salicornia virginica
inside Mus sp.
Isocoma veneta
kelp
Lasthenia
Lavandula angustifolia
Lavender Plant
Lavendula angustifolia
Lupina albifrons
Lupins bicolor
Lupinu bicolor
Lupinuc bicolor
lupinus albifrons
Lupinus albifrons
Lupinus arboreus
Lupinus arboreus: Voucher: UCSB049925
Lupinus bicolor
Lupinus Bicolor
Lupinus bocolr
Lupinus nipomensis
Madara Tree
Malacotamnus fasciculatus
Malacothamnus fasaculatus suppnesioticus
Malacothamnus fasciculatus
Malacothamnus fasciculatus suppnesioticus
Malacothamnus fasiculatus suppnesioticus
male Marrubium
Malva
Marrubium
Mentzelia involucrata; Hyptis emoryi
milkweed
Milkweed
Mimulus aurentiacus
Monarda
Murgantia histrionica
Oak near Cascades
on Ambrosia chamissonis
(On) coreupsis
On Lupinus succulentus, visiting flower
on Manzanita
Oregano, Marjoram
Parkinsonia florida
Passiflora sp.
Phacelia tanacetifolia
Phallia sp
pine
Pinus muricata
Pinus sp.
Populus tremuloides
Prunus
Prunus ilicifolia
Quercus agrifolia
Raphanus sativus
Rat
Restored coastal sage scrub
Rhus integrifolia
Rhus integrifolia; Salvia
Rosa californica
Salicornia pacifica
Salvia leucophylla
Salvia mellifera
Salvia mellifera flowers
Sambucus nigra
Scrophularia californica
Sequoia
Sequoiadendron sempervirens
Sidalcea malvaeflora
Sisyrinchium bellum
Solanum americanus
T4N R2/W S3
Tree
Tropaeolum
Umbellularia californica
under Cakile maritima
Venegasia capesioides
Venegasia carpesioides
Violacea malviflora
Voucher UCSB049924
Voucher UCSB049948
```

@seltmann how would you categorize the associations for the particular dataset. Would be a good way to describe kind of taxonomic association? Co-occurrence? Biotic interaction? Host?

**Comment by seltmann** [comment]
I would say associated with or associates with. Most of these really indicate the **on** condition, not nearby or co-occurrence. Host would not be appropriate, as that is a term usually reserved for parasitic species.

**Comment by jhpoelen** [comment]
Ok, by "on" do you mean physically connecting?

**Comment by seltmann** [comment]
Yes, physically connecting. In the past I have used http://purl.obolibrary.org/obo/RO_0002437

**Comment by jhpoelen** [comment]
Thanks for clarifying. Should we suggest to have "biotically associated with" included as a synonym of "biotically interacts with" ? It seems that the phrases "biotic association" and "biotic interaction" used interchangeably.

**Comment by seltmann** [comment]
I actually think it is an error, commonly my error. Interacts seems more specific than associates.

**Comment by jhpoelen** [comment]
Sounds like a term "biotically associated with" needs to introduced in RO. This term would be a hypernym of "biotically interacts with" . Agree?

For this particular dataset, would http://purl.obolibrary.org/obo/RO_0002437 be sufficient to describe the connection of a record with the associatedTaxa?

**Comment by seltmann** [comment]
or http://purl.obolibrary.org/obo/RO_0002618

**Comment by jhpoelen** [comment]
Thanks for clarifying.

With this, I have enough information to take a first pass at creating an integration with https://symbiota.ccber.ucsb.edu/content/dwca/UCSB-IZC_DwC-A.zip . I'll have to make some additions to account for a default interactionTypeId (in this case http://purl.obolibrary.org/obo/RO_0002437) whenever none is explicitly specified in the record itself.

**Comment by seltmann** [comment]
Excited to have these in GloBI. These are just our arthropod data, but our plant, lichen, vertebrate collections all live in different Symbiota portals. Should I open up new issues for each? That is what makes sense to me as they live in different darwin core archive files. They all contain interactions and I would like this to be an example of a small collection sharing all interaction information with GloBI. The interaction data will be similar.

**Comment by jhpoelen** [comment]
Nice to hear that there's more datasets with associatedTaxa info from UCSB! 

As RSS feeds are widely used to list collections of dwca and GloBI has some pre-existing support for RSS feeds, I was thinking it might be easier to author a static rss.xml in a github repo pointing to UCSB collection dwc archives across the various Symbiota portals? This way, you'd be able to re-use methods to lists the datasets. If you like this approach, please create a github repo with the static rss.xml file in it and I can create pull requests to add globi config. If not, please list the additional datasets you'd like to add. Am open to other ideas you have to minimize maintenance overhead.

**Comment by seltmann** [comment]
True, but the RSS feeds are generally from one publisher. These collections are from different publishers. For example, this collection is listed in this feed:
https://symbiota.ccber.ucsb.edu/webservices/dwc/rss.xml

But the lichen collection is listed in this feed:
https://lichenportal.org/cnalh/webservices/dwc/rss.xml

**Comment by jhpoelen** [comment]
The idea of composing your own RSS feeds would create a rss.xml that would look something like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>UC Santa Barbara Collection Network Darwin Core Archive with Associations rss feed</title>
    <link>https://raw.githubcontent.com/...</link>
    <description>UC Santa Barbara Collection Network Darwin Core Archive with Associations rss feed</description>
    <language>en-us</language>
    <item collid="1">
      <title>UCSB-IZC DwC-Archive</title>
      <image>http://symbiota.ccber.ucsb.edu/content/collicon/ucsb-izc.png</image>
      <description>Darwin Core Archive for University of California Santa Barbara Invertebrate Zoology Collection</description>
      <guid>https://symbiota.ccber.ucsb.edu:443/collections/misc/collprofiles.php?collid=1</guid>
      <guid>e7c51ab1-870b-4ee8-9d62-092875ffa870</guid>
      <emllink>https://symbiota.ccber.ucsb.edu:443/content/dwca/UCSB-IZC_DwC-A.eml</emllink>
      <type>DWCA</type>
      <recordType>DWCA</recordType>
      <link>https://symbiota.ccber.ucsb.edu:443/content/dwca/UCSB-IZC_DwC-A.zip</link>
      <pubDate>Wed, 28 Aug 2019 15:30:05</pubDate>
    </item>
<item collid="2">
      <title>UCSB DwC-Archive</title>
      <image>http://lichenportal.org/portal/content/collicon/ucsb.jpg</image>
      <description>Darwin Core Archive for University of California Santa Barbara Lichen Collection</description>
      <guid>https://lichenportal.org:443/cnalh/collections/misc/collprofiles.php?collid=98</guid>
      <guid>f669c4f7-69ca-444f-8b4f-7706e07b2f38</guid>
      <emllink>https://lichenportal.org:443/cnalh/content/dwca/UCSB_DwC-A.eml</emllink>
      <type>DWCA</type>
      <recordType>DWCA</recordType>
      <link>https://lichenportal.org:443/cnalh/content/dwca/UCSB_DwC-A.zip</link>
      <pubDate>Thu, 29 Aug 2019 11:37:08</pubDate>
    </item>
  </channel>
</rss>
```

If you don't like the idea of composing a list of UCSB dwca with associations across different locations, please submit a different issue for each of the darwin core archives you'd like to include.

**Comment by seltmann** [comment]
Thanks, does GloBI use the RSS feed to detect updates in the datasets? So, if the date changes on the RSS feed than the information is refreshed on GloBI. Thanks for helping me understand the process.

**Comment by jhpoelen** [comment]
GloBI uses the RSS feed to find URLs pointing to published datasets. Change is detected not by the pub date in the RSS item meta-data, but by calculating content signature of the referred datasets.

**Comment by seltmann** [comment]
How often does it check for content signature changes?

**Comment by jhpoelen** [comment]
Currently, internet weather permitting, about every other day.

**Comment by jhpoelen** [comment]
Took a stab at indexing ```https://symbiota.ccber.ucsb.edu:443/content/dwca/UCSB-IZC_DwC-A.zip``` and found a little over 800 interactions and a bunch of warnings. 

Warnings seem to stem from inconsistent usage of associateTaxa values - dwca suggests to use ```|``` for delimiter in sequences (e.g., ````Homo sapiens | Ariopsis felis```), and ```:``` for formatting (e.g., ```eats: Homo sapiens```), or missing scientificName for the primary specimen. 

I've included the warnings in the warnings.tsv.txt . Let me know there's anything unexpected. 

[warnings.tsv.txt](https://github.com/jhpoelen/eol-globi-data/files/3581530/warnings.tsv.txt)

**Comment by jhpoelen** [comment]
Here's what the ```globi.json``` would look like:

```json
{
  "format": "application/dwca",
  "citation": "some citation",
  "url": "https://symbiota.ccber.ucsb.edu:443/content/dwca/UCSB-IZC_DwC-A.zip"
}
```

**Comment by jhpoelen** [comment]
@seltmann I've created https://github.com/globalbioticinteractions/ucsb-icz with minimal configuration to help things move along. Please feel free if you'd like to move this one elsewhere.

**Comment by jhpoelen** [comment]
Please note that the UCSB-IZC collection has been indexed by GloBI. See https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fucsb-izc&interactionType=ecologicallyRelatedTo and attached screenshot. 

For specific specimen, you can do https://www.globalbioticinteractions.org/?accordingTo=https%3A%2F%2Fsymbiota.ccber.ucsb.edu%3A443%2Fcollections%2Findividual%2Findex.php%3Foccid%3D135242&interactionType=interactsWith . 

Arctos folks are using https://api.globalbioticinteractions.org/exists?accordingTo=https%3A%2F%2Fsymbiota.ccber.ucsb.edu%3A443%2Fcollections%2Findividual%2Findex.php%3Foccid%3D135242&interactionType=interactsWith and check for return codes 200 vs. 404 whether GloBI has info on a specific reference (in this case: ```https://symbiota.ccber.ucsb.edu:443/collections/individual/index.php?occid=135242```) . 

Also, individual records can be retrieved via various datasets at https://globalbioticinteractions.org/data and via api like:

https://api.globalbioticinteractions.org/interaction?accordingTo=https%3A%2F%2Fsymbiota.ccber.ucsb.edu%3A443%2Fcollections%2Findividual%2Findex.php%3Foccid%3D135242&includeObservations=T

for JSON and

https://api.globalbioticinteractions.org/interaction.tsv?accordingTo=https%3A%2F%2Fsymbiota.ccber.ucsb.edu%3A443%2Fcollections%2Findividual%2Findex.php%3Foccid%3D135242&includeObservations=T

for TSV . 

Note that both interaction directions are listed, one of which is inferred by GloBI. 

fyi @seltmann @neilcobb 

![Screenshot from 2019-09-11 15-20-34](https://user-images.githubusercontent.com/1084872/64739810-0aa9b880-d4a8-11e9-8860-b32fc401d94d.png)
