### ISSUE TITLE
suggest to integrate with  NCEAS's interaction web

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#65]
As suggested by @ahhurlbert:

Just wondering whether you all at GLOBI are familiar with the NCEAS-based effort of several years ago called [Interaction Web](http://www.nceas.ucsb.edu/interactionweb/resources.html).

I searched the first reference of Interaction Web (Ollerton et al. 2007) and it is not listed in the GLOBI references, so it seems not.

I think this effort has petered out in recent years, so it might be worth contacting them to see if they are amenable to having their datasets absorbed by GLOBI, or interested in using GLOBI as their own data repository.

**Comment by millerse** [comment]
@jhpoelen I am going to try and tackle this one.  I should get you a new set in a day or two to see how the set looks.

**Comment by jhpoelen** [comment]
@millerse sounds great! Let me know if you have any questions. I'd suggest to clone a fresh repository (with a different name) specifically dedicated to this *huge* data set.

**Comment by millerse** [comment]
@jhpoelen Sorry for the delay. I have all of the tables in a single interaction file.  The link is here: https://github.com/millerse/IWDB

Let me know if there are any concerns.

**Comment by jhpoelen** [comment]
@millerse wow! I am very impressed! If my count is correct, you've just added 38,022 interactions. I find that very impressive given the limited time that you did this in and the fact that the formats of the source were mostly all different. 

I'll run some tests and let you know what I'll find.

**Comment by jhpoelen** [comment]
@millerse I am working under the assumption that when decimalLatitude, decimalLongitude and localityId are provided, the decimals would provide most accurate info. Would you say this is a safe assumption?

**Comment by millerse** [comment]
Yes.  There were records where the lat long was included in the original publication.

**Comment by millerse** [comment]
@jhpoelen Morning Jorrit,
Hope that this dataset is looks good.  I was wondering if there were any new datasets that you can let me sink my teeth into?

Sarah

**Comment by jhpoelen** [comment]
@millerse dataset looks great so far - the GloBI ingestion process takes a while (~ 30 hours) and I am expecting that your newly added dataset will be up on http://globalbioticinteractions.org shortly. As soon as it is, I'll close the issue. Hope that makes sense, and thanks for being patient.

**Comment by millerse** [comment]
@jhpoelen 
Thank you.

**Comment by jhpoelen** [comment]
Just had a peek at GloBI and ... your IWDB data transcription looks wonderful! Some numbers: ~38k recorded interactions across ~5k distinct taxa from ~50 studies. Nice! 

Not available on eol.org yet, but that be just a matter of time. Closing issue.

snippet from http://globalbioticinteractions.org/references.html : 
![screen shot 2015-03-03 at 12 53 55 pm](https://cloud.githubusercontent.com/assets/1084872/6472058/7cc87788-c1a4-11e4-9aec-f1d54ff36bb7.png)

**Comment by jhpoelen** [comment]
@ahhurlbert thanks to @millerse IWDB is now available through GloBI!

**Comment by ahhurlbert** [comment]
Fantastic!

**Comment by jhpoelen** [comment]
@millerse @jhammock I was revisiting the IWDB dataset and noticed that the repository at https://github.com/millerse/IWDB no longer exists. Any idea why?

**Comment by jhammock** [comment]
gosh, no...

**Comment by jhpoelen** [comment]
I checked Zenodo and couldn't find an archived copy either. IWDB is an often used resource for ecological network researchers and contains trusted datasets. Are you still in touch with @millerse ?

**Comment by jhpoelen** [comment]
After some digging, it appears that the IWDB dataset was split into separate datasets: 


https://github.com/millerse/Anemonefish
https://github.com/millerse/Canadian-freshwater-fish-and-their-metazoan-parasites
https://github.com/millerse/Carpinteria-Salt-Marsh-Web
https://github.com/millerse/Clements-R.-E.-and-F.-L.-Long
https://github.com/millerse/PLANT-SEED-DISPERSER-WEBS
https://github.com/millerse/Plant-Pollinator-Web
https://github.com/millerse/Plant-Herbivore-Web
https://github.com/millerse/Plant-ant-webs

A quick and dirty count leads to about 20k nodes. which seems short of the original number of nodes ~ 2* 30k (two nodes per interaction). Perhaps I missed a few repositories. Would be great to hear the reasoning behind the split.
