### ISSUE TITLE
Provide downloadable list of all taxa in GloBI including hierarchies and taxonomies used

### ISSUE THREAD

**Issue by jemmybutton** [jhpoelen/eol-globi-data#70]
Sometimes it is difficult to make sense of data in DCA without taxonomic data on all entries, especially considering different sources where this data comes from (EOL, WoRMS). Format of taxon.csv (now almost empty) is too restrictive for this purpose, since it has fixed number of columns for ranks (kingdom/phylum/class/order/family/genus/species) and seems to be designed to represent only one taxonomy, from one provider.
Separate file with data like
```
taxonID, dataProvider, taxonomy
"EOL:913266", "Avibase - IOC World Bird Names (2011)", "{Kingdom:Animalia|Phylum:Chordata|Class:Aves…}"
"EOL:913266", "South African Vertebrates", "{Kingdom:Animalia|Phylum:Chordata|Subphylum:Vertebrata…}"
```
would solve the problem

**Comment by jhpoelen** [comment]
HI @jemmybutton . . . finally managed to create a downloadable dump of all taxa (and their links) in the form of two csv files: 

https://s3.amazonaws.com/globi/snapshot/target/data/taxa.csv.gz
and 
https://s3.amazonaws.com/globi/snapshot/target/data/linkedTaxa.csv.gz

Also, unmatched names are available in the form of a file:
https://s3.amazonaws.com/globi/snapshot/target/data/unmatchedTax.csv

I've included the links to these files in:
http://globalbioticinteractions.org/references.html (see screenshot below) 
and
https://github.com/jhpoelen/eol-globi-data/wiki/Taxonomy-Matching#list-of-resources

Please re-open this issue if you have concerns / comments.

Thanks for your patience.
-jorrit

PS 
@godfoder @mjcollin you might be able to used these resources as a starting point for name matching. The list is far from complete (it "only" includes taxa occurring in GloBI), but hey, it is a start. Hopefully, we can figure out a way to make this (or comparable archive) more comprehensive.

@jhammock let me know what I can do to help convince folks to provide all of EOL taxa in taxa.csv.gz format (or similar)? I'll use taxa.csv.gz as a starting point for https://github.com/jhpoelen/effechecka for now.

**Comment by jhpoelen** [comment]
related issue https://github.com/jhpoelen/eol-globi-data/issues/145
