### ISSUE TITLE
integrate lionfish diet data by Morris and Akins (2009)

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#85]
Potentially interesting spatiotemporal diet dataset for lionfish (_Pterois volitans_), an invasive species in Bahamian archipelago .

See http://graysreef.noaa.gov/science/publications/pdfs/morris_akins_2009.pdf

Authors not yet contacted.

**Comment by jhpoelen** [comment]
@proopnarine just checking in about lionfish data . . . are you ready to share the data?

**Comment by proopnarine** [comment]
Hi Jorrit,

I think so. I have two sets of data. The first are compiled from a number of published studies. The second is based on our predictive modelling. I will send you the first set, and the second when we eventually have it submitted. These data are integrated into the coral reef data that you've already incorporated.

Peter

Dr. Peter D. Roopnarine, Curator of Geology
Chair, Department of Invertebrate Zoology & Geology
Institute for Biodiversity Science and Sustainability
California Academy of Sciences
55 Music Concourse Drive
Golden Gate Park
San Francisco CA 94118

Phone: (415) 379-5271
FAX: (415) 379-5732
WWW: http://zeus.calacademy.org/roopnarine/peter.html
Blogs: http://www.calacademy.org/blogs/
http://proopnarine.wordpress.com
"If I could explain it to the average person, I wouldn't have been worth the Nobel Prize", R. Feynman
<http://www.brainyquote.com/quotes/quotes/r/richardpf116607.html>
________________________________

**Comment by jhpoelen** [comment]
@proopnarine  looking forward to incorporating your contribution. If you feel adventurous, you can even try to share it using a github repository. You can find some details about that there: https://github.com/globalbioticinteractions/template-dataset/ . Otherwise, please send me a link / archive.

**Comment by jhpoelen** [comment]
As mentioned before @jhammock  contributed a manually transcribed version of Layman et al. 2012 here https://github.com/jhammock/Layman-and-Allgeier-Lionfish . Closing issue.
