### ISSUE TITLE
Provide character information in charJSON format

### ISSUE THREAD

**Issue by ammatsun** [jhpoelen/eol-globi-data#93]
charJSON is being used by PhyloJIVE and its formal specification can be found at:
http://trin.github.io/phyloJIVE/charJSONFormalSpec.html

There are also some examples at:
http://trin.github.io/phyloJIVE/about_charJSON.html

**Comment by jhpoelen** [comment]
I like the idea of using character matrices as a tool for downstream analysis. In this way occurrence / specimen level species interaction data from GloBI can be summarized at the taxon level. This said, I think this representation is out-scope of GloBI. Please feel free to re-open the issue if anyone has a specific use case that would benefit GloBI consumers or contributors. Thanks for the discussion!

PS Note that #109 introduced a first pass at GloBI's jsonld support.
