### ISSUE TITLE
Interaction data from Tri-Trophic TCN project

### ISSUE THREAD

**Issue by seltmann** [jhpoelen/eol-globi-data#99]
Hoping to have the TTD_TCN DwC-A online soon with our version of an associatedTaxa Extension 

(outlined here: https://docs.google.com/spreadsheet/ccc?key=0AvHeAV_gLFNsdEhtVjRkSUdxUmk3WXJvWmtLSGVRNlE&usp=drive_web#gid=0)

We hope to merge our fields with GloBi DwC-A for a unified vision of what a formal associatedTaxa Extension might look like.

**Comment by jhpoelen** [comment]
closing this duplicate issue. See #126 instead.
